[#0000-27-dp-5-longest-common-substring]
= Longest Common Substring 最长子字符串系列

== 经典题目

. xref:0072-edit-distance.adoc[72. Edit Distance]
. xref:0097-interleaving-string.adoc[97. Interleaving String]
. xref:0300-longest-increasing-subsequence.adoc[300. Longest Increasing Subsequence]
. xref:1143-longest-common-subsequence.adoc[1143. Longest Common Subsequence]
. xref:1092-shortest-common-supersequence.adoc[1092. Shortest Common Supersequence]
. xref:0718-maximum-length-of-repeated-subarray.adoc[718. 最长重复子数组]

Longest Common Substring，最长相同子串

Longest Common Subsequence，最长相同子序列

Minimum Deletions & Insertions to Transform a String into another，字符串变换

Longest Increasing Subsequence，最长上升子序列

Maximum Sum Increasing Subsequence，最长上升子序列和

Shortest Common Super-sequence，最短超级子序列

Minimum Deletions to Make a Sequence Sorted，最少删除变换出子序列

Longest Repeating Subsequence，最长重复子序列

Subsequence Pattern Matching，子序列匹配

Longest Bitonic Subsequence，最长字节子序列

Longest Alternating Subsequence，最长交差变换子序列

Edit Distance，编辑距离

Strings Interleaving，交织字符串
