[#0068-text-justification]
= 68. 文本左右对齐

https://leetcode.cn/problems/text-justification/[LeetCode - 68. 文本左右对齐 ^]

给定一个单词数组 `words` 和一个长度 `maxWidth` ，重新排版单词，使其成为每行恰好有 `maxWidth` 个字符，且左右两端对齐的文本。

你应该使用 “*贪心算法*” 来放置给定的单词；也就是说，尽可能多地往每行中放置单词。必要时可用空格 `' '` 填充，使得每行恰好有 _``maxWidth``_ 个字符。

要求尽可能均匀分配单词间的空格数量。如果某一行单词间的空格不能均匀分配，则左侧放置的空格数要多于右侧的空格数。

文本的最后一行应为左对齐，且单词之间不插入**额外的**空格。

*注意:*

* 单词是指由非空格字符组成的字符序列。
* 每个单词的长度大于 `0`，小于等于 _``maxWidth``_。
* 输入单词数组 `words` 至少包含一个单词。

*示例 1:*

....
输入: words = ["This", "is", "an", "example", "of", "text", "justification."], maxWidth = 16
输出:
[
   "This    is    an",
   "example  of text",
   "justification.  "
]
....

*示例 2:*

....
输入:words = ["What","must","be","acknowledgment","shall","be"], maxWidth = 16
输出:
[
  "What   must   be",
  "acknowledgment  ",
  "shall be        "
]
解释: 注意最后一行的格式应为 "shall be    " 而不是 "shall     be",
     因为最后一行应为左对齐，而不是左右两端对齐。
     第二行同样为左对齐，这是因为这行只包含一个单词。
....

*示例 3:*

....
输入:words = ["Science","is","what","we","understand","well","enough","to","explain","to","a","computer.","Art","is","everything","else","we","do"]，maxWidth = 20
输出:
[
  "Science  is  what we",
  "understand      well",
  "enough to explain to",
  "a  computer.  Art is",
  "everything  else  we",
  "do                  "
]
....

*提示:*

* `+1 <= words.length <= 300+`
* `+1 <= words[i].length <= 20+`
* `words[i]` 由小写英文字母和符号组成
* `+1 <= maxWidth <= 100+`
* `+words[i].length <= maxWidth+`


== 思路分析

有思路，但是没有对思路进行分类。参考题解，分为“最后一行”、“一个单词一行”和“多个单词一行”来分别处理。

[[src-0068]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0068_TextJustification.java[tag=answer]
----
--

二刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0068_TextJustification_2.java[tag=answer]
----
--
====


== 参考资料

. https://leetcode.cn/problems/text-justification/solutions/986756/wen-ben-zuo-you-dui-qi-by-leetcode-solut-dyeg/[68. 文本左右对齐 - 官方题解^]
. https://leetcode.cn/problems/text-justification/solutions/181651/text-justification-by-ikaruga/[68. 文本左右对齐 - 平均分布额外空格^]
. https://leetcode.cn/problems/text-justification/solutions/535122/golang-jian-ji-xie-fa-by-endlesscheng-180a/[68. 文本左右对齐 - Golang 简洁写法，附详细注释^]
