= 80. Remove Duplicates from Sorted Array II

https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/[LeetCode - Remove Duplicates from Sorted Array II]

Given a sorted array `nums`, remove the duplicates in-place such that duplicates appeared at most *twice* and return the new length.

Do not allocate extra space for another array, you must do this by *modifying the input array* in-place with O(1) extra memory.

.Example 1:
----
Given nums = [1,1,1,2,2,3],

Your function should return length = 5, with the first five elements of nums being 1, 1, 2, 2 and 3 respectively.

It doesn't matter what you leave beyond the returned length.
----

.Example 2:
----
Given nums = [0,0,1,1,1,1,2,3,3],

Your function should return length = 7, with the first seven elements of nums being modified to 0, 0, 1, 1, 2, 3 and 3 respectively.

It doesn't matter what values are set beyond the returned length.
----

*Clarification:*

Confused why the returned value is an integer but your answer is an array?

Note that the input array is passed in by *reference*, which means modification to the input array will be known to the caller as well.

Internally you can think of this:

----
// nums is passed in by reference. (i.e., without making a copy)
int len = removeDuplicates(nums);

// any modification to nums in your function would be known by the caller.
// using the length returned by your function, it prints the first len elements.
for (int i = 0; i < len; i++) {
    print(nums[i]);
}
----

== 解题分析

解题思路很简单：把后面的值覆盖前面多余的值。关键是如何用简单的代码来实现这个思路。

== 参考资料

. https://leetcode-cn.com/problems/remove-duplicates-from-sorted-array-ii/solution/shan-chu-pai-xu-shu-zu-zhong-de-zhong-fu-xiang-i-7/[删除排序数组中的重复项 II - 删除排序数组中的重复项 II - 力扣（LeetCode）]

Given a sorted array _nums_, remove the duplicates https://en.wikipedia.org/wiki/In-place_algorithm[*in-place*] such that duplicates appeared at most _twice_ and return the new length.

Do not allocate extra space for another array, you must do this by *modifying the input array https://en.wikipedia.org/wiki/In-place_algorithm[in-place]* with O(1) extra memory.

*Example 1:*

[subs="verbatim,quotes,macros"]
----
Given _nums_ = *[1,1,1,2,2,3]*,

Your function should return length = *`5`*, with the first five elements of _`nums`_ being *`1, 1, 2, 2`* and *3* respectively.

It doesn't matter what you leave beyond the returned length.
----

*Example 2:*

[subs="verbatim,quotes,macros"]
----
Given _nums_ = *[0,0,1,1,1,1,2,3,3]*,

Your function should return length = *`7`*, with the first seven elements of _`nums`_ being modified to *`0`*, *0*, *1*, *1*, *2*, *3* and *3* respectively.

It doesn't matter what values are set beyond the returned length.

----

*Clarification:*

Confused why the returned value is an integer but your answer is an array?

Note that the input array is passed in by *reference*, which means modification to the input array will be known to the caller as well.

Internally you can think of this:

[subs="verbatim,quotes,macros"]
----
// *nums* is passed in by reference. (i.e., without making a copy)
int len = removeDuplicates(nums);

// any modification to *nums* in your function would be known by the caller.
// using the length returned by your function, it prints the first *len* elements.
for (int i = 0; i < len; i++) {
    print(nums[i]);
}

----


[[src-0080]]
[{java_src_attr}]
----
include::{sourcedir}/_0080_RemoveDuplicatesFromSortedArrayII.java[]
----

