[#0081-search-in-rotated-sorted-array-ii]
= 81. Search in Rotated Sorted Array II

https://leetcode.com/problems/search-in-rotated-sorted-array-ii/[LeetCode - Search in Rotated Sorted Array II]

Suppose an array sorted in ascending order is rotated at some pivot unknown to you beforehand.

(i.e., `[0,0,1,2,2,5,6]` might become `[2,5,6,0,0,1,2]`).

You are given a target value to search. If found in the array return `true`, otherwise return `false`.

.Example 1:
----
Input: nums = [2,5,6,0,0,1,2], target = 0
Output: true
----

.Example 2:
----
Input: nums = [2,5,6,0,0,1,2], target = 3
Output: false
----

*Follow up:*

* This is a follow up problem to xref:0033-search-in-rotated-sorted-array.adoc[33. Search in Rotated Sorted Array], where `nums` may contain duplicates.
* Would this affect the run-time complexity? How and why?

== 解题思路

这道题的关键是先确定哪部分有序，然后判断目标值是否在有序区间内，如果没有则再另外一部分内。

另外，需要注意的就是对重复值的处理。如果左边的值和中间值相等，直接让左边下标向前移动一下，简单有效。

== 参考资料

. https://leetcode-cn.com/problems/search-in-rotated-sorted-array-ii/solution/zai-javazhong-ji-bai-liao-100de-yong-hu-by-reedfan/[搜索旋转排序数组 II - 搜索旋转排序数组 II - 力扣（LeetCode）]

Suppose an array sorted in ascending order is rotated at some pivot unknown to you beforehand.

(i.e., `[0,0,1,2,2,5,6]` might become `[2,5,6,0,0,1,2]`).

You are given a target value to search. If found in the array return `true`, otherwise return `false`.

*Example 1:*

[subs="verbatim,quotes,macros"]
----
*Input:* nums = [2`,5,6,0,0,1,2]`, target = 0
*Output:* true

----

*Example 2:*

[subs="verbatim,quotes,macros"]
----
*Input:* nums = [2`,5,6,0,0,1,2]`, target = 3
*Output:* false
----

*Follow up:*


* This is a follow up problem to <a href="/problems/search-in-rotated-sorted-array/description/">Search in Rotated Sorted Array</a>, where `nums` may contain duplicates.
* Would this affect the run-time complexity? How and why?


[[src-0081]]
[{java_src_attr}]
----
include::{sourcedir}/_0081_SearchInRotatedSortedArrayII.java[]
----

