[#0081-search-in-rotated-sorted-array-ii]
= 81. 搜索旋转排序数组 II

https://leetcode.cn/problems/search-in-rotated-sorted-array-ii/[LeetCode - 81. 搜索旋转排序数组 II ^]

已知存在一个按非降序排列的整数数组 `+nums+` ，数组中的值不必互不相同。

在传递给函数之前，`+nums+` 在预先未知的某个下标
`+k+`（`+0 <= k < nums.length+`）上进行了 *旋转* ，使数组变为
`+[nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]]+`（下标
*从 0 开始* 计数）。例如， `+[0,1,2,4,4,4,5,6,6,7]+` 在下标 `+5+`
处经旋转后可能变为 `+[4,5,6,6,7,0,1,2,4,4]+` 。

给你 *旋转后* 的数组 `+nums+` 和一个整数 `+target+`
，请你编写一个函数来判断给定的目标值是否存在于数组中。如果 `+nums+`
中存在这个目标值 `+target+` ，则返回 `+true+` ，否则返回 `+false+` 。

你必须尽可能减少整个操作步骤。

*示例 1：*

[subs="verbatim,quotes,macros"]
----
输入：nums = [2,5,6,0,0,1,2], target = 0
输出：true
----

*示例 2：*

[subs="verbatim,quotes,macros"]
----
输入：nums = [2,5,6,0,0,1,2], target = 3
输出：false
----

*提示：*

* `+1 <= nums.length <= 5000+`
* `-10`^`4`^`+<= nums[i] <= 10+`^`4`^
* 题目数据保证 `nums` 在预先未知的某个下标上进行了旋转
* `+-10+`^`4`^`+<= target <= 10+`^`+4+`^

*Follow up:*

* This is a follow up problem to xref:0033-search-in-rotated-sorted-array.adoc[33. Search in Rotated Sorted Array], where `nums` may contain duplicates.
* Would this affect the run-time complexity? How and why?

*进阶：*

* 此题与 https://leetcode-cn.com/problems/search-in-rotated-sorted-array/description/[搜索旋转排序数组] 相似，但本题中的 `nums` 可能包含 *重复* 元素。这会影响到程序的时间复杂度吗？会有怎样的影响，为什么？

== 解题思路

这道题的关键是先确定哪部分有序，然后判断目标值是否在有序区间内，如果没有则再另外一部分内。

另外，需要注意的就是对重复值的处理。如果左边的值和中间值相等，直接让左边下标向前移动一下，简单有效。


[[src-0081]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0081_SearchInRotatedSortedArrayII.java[tag=answer]
----
--

二刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0081_SearchInRotatedSortedArrayIi_2.java[tag=answer]
----
--
====

== 参考资料

