[#0165-compare-version-numbers]
= 165. Compare Version Numbers

https://leetcode.com/problems/compare-version-numbers/[LeetCode - Compare Version Numbers]

Compare two version numbers _version1_ and _version2_.


If `_version1_ > _version2_` return `1;` if `_version1_ < _version2_` return `-1;`otherwise return `0`.

You may assume that the version strings are non-empty and contain only digits and the `.` character.
The `.` character does not represent a decimal point and is used to separate number sequences.
For instance, `2.5` is not "two and a half" or "half way to version three", it is the fifth second-level revision of the second first-level revision.
You may assume the default revision number for each level of a version number to be `0`. For example, version number `3.4` has a revision number of `3` and `4` for its first and second level revision number. Its third and fourth level revision number are both `0`.

 

*Example 1:*
[subs="verbatim,quotes,macros"]
----
*Input:* `_version1_` = "0.1", `_version2_` = "1.1"
*Output:* -1
----

*Example 2:*
[subs="verbatim,quotes,macros"]
----
*Input:* `_version1_` = "1.0.1", `_version2_` = "1"
*Output:* 1
----

*Example 3:*
[subs="verbatim,quotes,macros"]
----
*Input:* `_version1_` = "7.5.2.4", `_version2_` = "7.5.3"
*Output:* -1
----

*Example 4:*
[subs="verbatim,quotes,macros"]
----
*Input:* `_version1_` = "1.01", `_version2_` = "1.001"
*Output:* 0
*Explanation:* Ignoring leading zeroes, both “01” and “001" represent the same number “1”
----

*Example 5:*
[subs="verbatim,quotes,macros"]
----
*Input:* `_version1_` = "1.0", `_version2_` = "1.0.0"
*Output:* 0
*Explanation:* The first version number does not have a third level revision number, which means its third level revision number is default to "0"
----

 

*Note:*

. Version strings are composed of numeric strings separated by dots `.` and this numeric strings *may* have leading zeroes. 
. Version strings do not start or end with dots, and they will not be two consecutive dots.



[[src-0165]]
[{java_src_attr}]
----
include::{sourcedir}/_0165_CompareVersionNumbers.java[tag=answer]
----

