== 167. Two Sum II - Input array is sorted

https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/[LeetCode - Two Sum II - Input array is sorted]

Given an array of integers that is already **sorted in ascending order**, find two numbers such that they add up to a specific target number.

The function twoSum should return indices of the two numbers such that they add up to the target, where index1 must be less than index2.

*Note:*

* Your returned answers (both index1 and index2) are not zero-based.
* You may assume that each input would have *exactly* one solution and you may not use the *same* element twice.

.Example:
----
Input: numbers = [2,7,11,15], target = 9
Output: [1,2]
Explanation: The sum of 2 and 7 is 9. Therefore index1 = 1, index2 = 2.
----

=== 解题思路

利用输入数组的有序性，可以从两边向中级"挤压"来查找正确解。

=== 参考资料

. https://leetcode-cn.com/problems/two-sum-ii-input-array-is-sorted/solution/liang-shu-zhi-he-ii-shu-ru-you-xu-shu-zu-by-leetco/[两数之和 II - 输入有序数组 - 两数之和 II - 输入有序数组 - 力扣（LeetCode）]

Given an array of integers that is already *_sorted in ascending order_*, find two numbers such that they add up to a specific target number.

The function twoSum should return indices of the two numbers such that they add up to the target, where index1 must be less than index2.

*Note:*


* Your returned answers (both index1 and index2) are not zero-based.
* You may assume that each input would have _exactly_ one solution and you may not use the _same_ element twice.


*Example:*

[subs="verbatim,quotes,macros"]
----
*Input:* numbers = [2,7,11,15], target = 9
*Output:* [1,2]
*Explanation:* The sum of 2 and 7 is 9. Therefore index1 = 1, index2 = 2.
----



[[src-0167]]
[source,{java_source_attr}]
----
include::{sourcedir}/_0167_TwoSumIIInputArrayIsSorted.java[]
----

