[#0198-house-robber]
= 198. 打家劫舍

https://leetcode.cn/problems/house-robber/[LeetCode - 198. 打家劫舍^]

你是一个专业的小偷，计划偷窃沿街的房屋。每间房内都藏有一定的现金，影响你偷窃的唯一制约因素就是相邻的房屋装有相互连通的防盗系统，*如果两间相邻的房屋在同一晚上被小偷闯入，系统会自动报警*。

给定一个代表每个房屋存放金额的非负整数数组，计算你 *不触动警报装置的情况下* ，一夜之内能够偷窃到的最高金额。

*示例 1：*

....
输入：[1,2,3,1]
输出：4
解释：偷窃 1 号房屋 (金额 = 1) ，然后偷窃 3 号房屋 (金额 = 3)。
     偷窃到的最高金额 = 1 + 3 = 4 。
....

*示例 2：*

....
输入：[2,7,9,3,1]
输出：12
解释：偷窃 1 号房屋 (金额 = 2), 偷窃 3 号房屋 (金额 = 9)，接着偷窃 5 号房屋 (金额 = 1)。
     偷窃到的最高金额 = 2 + 9 + 1 = 12 。
....

*提示：*

* `+1 <= nums.length <= 100+`
* `+0 <= nums[i] <= 400+`


[#思路分析]
== 思路分析

假设 f(k) = 从前 k 个房屋中能抢劫到的最大数额，A~i~ = 第 i 个房屋的钱数。

当 n=1 时，显然 f(1) = A~1~。

当 n=2 时，f(2) = max(A~1~, A~2~)。

当 n=3 时，有两种选项：

. 将第三个房间金额和第一个房间金额相加；
. 不算第三个房间，保持当前最大金额。

于是，可以总结出公式: latexmath:[f(k)=\max \left(f(k-2)+A_{k}, f(k-1)\right)]。

剩下的工作就好办了。

让 D瓜哥 使用 https://www.diguage.com/post/dynamic-programming/[动态规划的模式^] 来重新解读一下：

. 刻画一个最优解的结构特征：求解抢劫金额最大值。
. 递归地定义最优解的值： latexmath:[f(k)=\max \left(f(k-2)+A_{k}, f(k-1)\right)]。
. 计算最优解的值，通常采用自底向上的方法：D瓜哥也按照动态规划（注意表格）的方式来实现，采用自底向上+备忘录的方式来求解，创建一个长度为 n+1 的数组，第 i 个元素表示到第 i 个房间为止，最大抢劫金额；则第 0 个元素为 0，第 1 个元素为 A~1~。然后根据上述公式定义，以此类推……
. 利用计算出的信息构造一个最优解。这一步不需要，暂时忽略。

使用递归、递归+备忘录、自底向上+备忘录，自底向上+简化备忘录四种方式分别实现。


[[src-0198]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0198_HouseRobber.java[tag=answer]
----
--

二刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0198_HouseRobber_2.java[tag=answer]
----
--

三刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0198_HouseRobber_3.java[tag=answer]
----
--

四刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0198_HouseRobber_4.java[tag=answer]
----
--
====

== 参考资料

. https://leetcode.cn/problems/house-robber/solutions/2102725/ru-he-xiang-chu-zhuang-tai-ding-yi-he-zh-1wt1/[198. 打家劫舍 - 动态规划入门：从记忆化搜索到递推^]
. https://leetcode.cn/problems/house-robber/solutions/138131/dong-tai-gui-hua-jie-ti-si-bu-zou-xiang-jie-cjavap/[198. 打家劫舍 - 图解动态规划的解题四步骤^]
. https://leetcode.cn/problems/house-robber/solutions/28242/da-jia-jie-she-dong-tai-gui-hua-jie-gou-hua-si-lu-/[198. 打家劫舍 - 动态规划，结构化思路，清晰图解^]
. https://leetcode.cn/problems/house-robber/solutions/263856/da-jia-jie-she-by-leetcode-solution/[198. 打家劫舍 - 官方题解^]

