[#0232-implement-queue-using-stacks]
= 232. Implement Queue using Stacks

{leetcode}/problems/implement-queue-using-stacks/[LeetCode - Implement Queue using Stacks^]

Implement the following operations of a queue using stacks.


* push(x) -- Push element x to the back of queue.
* pop() -- Removes the element from in front of queue.
* peek() -- Get the front element.
* empty() -- Return whether the queue is empty.


*Example:*

[subs="verbatim,quotes,macros"]
----
MyQueue queue = new MyQueue();

queue.push(1);
queue.push(2);  
queue.peek();  // returns 1
queue.pop();   // returns 1
queue.empty(); // returns false
----

*Notes:*


* You must use _only_ standard operations of a stack -- which means only `push to top`, `peek/pop from top`, `size`, and `is empty` operations are valid.
* Depending on your language, stack may not be supported natively. You may simulate a stack by using a list or deque (double-ended queue), as long as you use only standard operations of a stack.
* You may assume that all operations are valid (for example, no pop or peek operations will be called on an empty queue).


== 思路分析

[[src-0232]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0232_ImplementQueueUsingStacks.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_0232_ImplementQueueUsingStacks_2.java[tag=answer]
// ----
// --
====

== 参考资料

. https://leetcode.cn/problems/implement-queue-using-stacks/solutions/2363977/232-yong-zhan-shi-xian-dui-lie-qing-xi-t-pi4l/?envType=study-plan-v2&envId=selected-coding-interview[232. 用栈实现队列 - 清晰图解^]


