[#0289-game-of-life]
= 289. Game of Life

https://leetcode.com/problems/game-of-life/[LeetCode - Game of Life^]

According to the https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life[Wikipedia's article^]: "The *Game of Life*, also known simply as *Life*, is a cellular automaton devised by the British mathematician John Horton Conway in 1970."

Given a _board_ with _m_ by _n_ cells, each cell has an initial state _live_ (1) or _dead_ (0). Each cell interacts with its https://en.wikipedia.org/wiki/Moore_neighborhood[eight neighbors^] (horizontal, vertical, diagonal) using the following four rules (taken from the above Wikipedia article):


. Any live cell with fewer than two live neighbors dies, as if caused by under-population.
. Any live cell with two or three live neighbors lives on to the next generation.
. Any live cell with more than three live neighbors dies, as if by over-population..
. Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.


Write a function to compute the next state (after one update) of the board given its current state. The next state is created by applying the above rules simultaneously to every cell in the current state, where births and deaths occur simultaneously.

*Example:*

[subs="verbatim,quotes,macros"]
----
*Input:*
[
  [0,1,0],
  [0,0,1],
  [1,1,1],
  [0,0,0]
]

*Output:*
[
  [0,0,0],
  [1,0,1],
  [0,1,1],
  [0,1,0]
]
----

*Follow up*:


. Could you solve it in-place? Remember that the board needs to be updated at the same time: You cannot update some cells first and then use their updated values to update other cells.
. In this question, we represent the board using a 2D array. In principle, the board is infinite, which would cause problems when the active area encroaches the border of the array. How would you address these problems?




[[src-0289]]
[{java_src_attr}]
----
include::{sourcedir}/_0289_GameOfLife.java[tag=answer]
----

