= 297. Serialize and Deserialize Binary Tree

https://leetcode.com/problems/serialize-and-deserialize-binary-tree/[LeetCode - Serialize and Deserialize Binary Tree]

Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer, or transmitted across a network connection link to be reconstructed later in the same or another computer environment.

Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work. You just need to ensure that a binary tree can be serialized to a string and this string can be deserialized to the original tree structure.

*Example: *

[subs="verbatim,quotes,macros"]
----
You may serialize the following tree:

    1
   / \
  2   3
     / \
    4   5

as `"[1,2,3,null,null,4,5]"`
----

*Clarification:* The above format is the same as <a href="/faq/#binary-tree">how LeetCode serializes a binary tree</a>. You do not necessarily need to follow this format, so please be creative and come up with different approaches yourself.

*Note: *Do not use class member/global/static variables to store states. Your serialize and deserialize algorithms should be stateless.

== 解题分析

一个比较简单的思路是分层进行序列化。这里一个误区就是把二叉树按照满二叉树转化成一个数组形式。

一个解决办法就是：在序列化的时候，先出力父节点，然后循环调用处理子节点，这样的话，就会把父子节点的关联关系给用上，也可以正常应对极端不平衡的情况。

[[src-0297]]
[{java_src_attr}]
----
include::{sourcedir}/_0297_SerializeAndDeserializeBinaryTree.java[]
----

