== 331. Verify Preorder Serialization of a Binary Tree

https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/[LeetCode - Verify Preorder Serialization of a Binary Tree]

One way to serialize a binary tree is to use pre-order traversal. When we encounter a non-null node, we record the node's value. If it is a null node, we record using a sentinel value such as `#`.

[subs="verbatim,quotes,macros"]
----
     _9_
    /   \
   3     2
  / \   / \
 4   1  #  6
/ \ / \   / \
# # # #   # #
----

For example, the above binary tree can be serialized to the string `"9,3,4,#,#,1,#,#,2,#,6,#,#"`, where `#` represents a null node.

Given a string of comma separated values, verify whether it is a correct preorder traversal serialization of a binary tree. Find an algorithm without reconstructing the tree.

Each comma separated value in the string must be either an integer or a character `'#'` representing `null` pointer.

You may assume that the input format is always valid, for example it could never contain two consecutive commas such as `"1,,3"`.

*Example 1:*

[subs="verbatim,quotes,macros"]
----
*Input:* `"9,3,4,#,#,1,#,#,2,#,6,#,#"`
*Output:* `true`
----

*Example 2:*

[subs="verbatim,quotes,macros"]
----
*Input:* `"1,#"`
*Output:* `false`
----

*Example 3:*

[subs="verbatim,quotes,macros"]
----
*Input:* `"9,#,#,1"`
*Output:* `false`
----


[[src-0331]]
[source,{java_source_attr}]
----
include::{sourcedir}/_0331_VerifyPreorderSerializationOfABinaryTree.java[]
----

