[#0406-queue-reconstruction-by-height]
= 406. Queue Reconstruction by Height

{leetcode}/problems/queue-reconstruction-by-height/[LeetCode - Queue Reconstruction by Height^]

Suppose you have a random list of people standing in a queue. Each person is described by a pair of integers `(h, k)`, where `h` is the height of the person and `k` is the number of people in front of this person who have a height greater than or equal to `h`. Write an algorithm to reconstruct the queue.

*Note:*

The number of people is less than 1,100.


.Example
----
Input:
[[7,0], [4,4], [7,1], [5,0], [6,1], [5,2]]

Output:
[[5,0], [7,0], [5,2], [6,1], [4,4], [7,1]]
----

这道题有点不明觉厉。

== 参考资料

. https://leetcode-cn.com/problems/queue-reconstruction-by-height/solution/gen-ju-shen-gao-zhong-jian-dui-lie-by-leetcode/[根据身高重建队列 - 根据身高重建队列 - 力扣（LeetCode）^]

Suppose you have a random list of people standing in a queue. Each person is described by a pair of integers `(h, k)`, where `h` is the height of the person and `k` is the number of people in front of this person who have a height greater than or equal to `h`. Write an algorithm to reconstruct the queue.

*Note:*


The number of people is less than 1,100.
 

*Example*

[subs="verbatim,quotes,macros"]
----
Input:
[[7,0], [4,4], [7,1], [5,0], [6,1], [5,2]]

Output:
[[5,0], [7,0], [5,2], [6,1], [4,4], [7,1]]
----

 



[[src-0406]]
[{java_src_attr}]
----
include::{sourcedir}/_0406_QueueReconstructionByHeight.java[tag=answer]
----

