[#0433-minimum-genetic-mutation]
= 433. 最小基因变化

https://leetcode.cn/problems/minimum-genetic-mutation/[LeetCode - 433. 最小基因变化^]

基因序列可以表示为一条由 8 个字符组成的字符串，其中每个字符都是 `A`、 `C`、 `G` 和 `T` 之一。

假设我们需要调查从基因序列 `start` 变为 `end` 所发生的基因变化。一次基因变化就意味着这个基因序列中的一个字符发生了变化。

* 例如，`AACCGGTT --> AACCGGTA` 就是一次基因变化。

另有一个基因库 `bank` 记录了所有有效的基因变化，只有基因库中的基因才是有效的基因序列。（变化后的基因必须位于基因库 `bank` 中）

给你两个基因序列 `start` 和 `end` ，以及一个基因库 `bank`，请你找出并返回能够使 `start` 变化为 `end` 所需的最少变化次数。如果无法完成此基因变化，返回 `-1` 。

注意：起始基因序列 `start` 默认是有效的，但是它并不一定会出现在基因库中。

*示例 1：*

....
输入：start = "AACCGGTT", end = "AACCGGTA", bank = ["AACCGGTA"]
输出：1
....

*示例 2：*

....
输入：start = "AACCGGTT", end = "AAACGGTA", bank = ["AACCGGTA","AACCGCTA","AAACGGTA"]
输出：2
....

*示例 3：*

....
输入：start = "AAAAACCC", end = "AACCCCCC", bank = ["AAAACCCC","AAACCCCC","AACCCCCC"]
输出：3
....


*提示：*

* `start.length == 8`
* `end.length == 8`
* `0 \<= bank.length \<= 10`
* `bank[i].length == 8`
* `start`、`end` 和 `bank[i]` 仅由字符 `['A', 'C', 'G', 'T']` 组成


== 思路分析

广度优先遍历，与 xref:0127-word-ladder.adoc[127. Word Ladder] 解题思路是一样的。

[[src-0433]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0433_MinimumGeneticMutation.java[tag=answer]
----
--

二刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0433_MinimumGeneticMutation_2.java[tag=answer]
----
--
====


== 参考资料

. https://leetcode.cn/problems/minimum-genetic-mutation/solutions/1474617/by-fuxuemingzhu-t1mv/[433. 最小基因变化 - 分享 BFS 模板，秒杀同类题目^]
. https://leetcode.cn/problems/minimum-genetic-mutation/solutions/1474582/by-ac_oier-74b4/[433. 最小基因变化 - 图论搜索 : 「BFS」&「双向 BFS」&「A* 算法」&「建图 + DFS」^]
. https://leetcode.cn/problems/minimum-genetic-mutation/solutions/39701/javadan-xiang-yan-du-you-xian-sou-suo-he-shuang-xi/[433. 最小基因变化 - Java单向广度优先搜索和双向广度优先搜索^]
