[#0452-minimum-number-of-arrows-to-burst-balloons]
= 452. Minimum Number of Arrows to Burst Balloons

https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/[LeetCode - Minimum Number of Arrows to Burst Balloons^]

There are a number of spherical balloons spread in two-dimensional space. For each balloon, provided input is the start and end coordinates of the horizontal diameter. Since it's horizontal, y-coordinates don't matter and hence the x-coordinates of start and end of the diameter suffice. Start is always smaller than end. There will be at most 10^4^ balloons.

An arrow can be shot up exactly vertically from different points along the x-axis. A balloon with x~start~ and x~end~ bursts by an arrow shot at x if x~start~ ≤ x ≤ x~end~. There is no limit to the number of arrows that can be shot. An arrow once shot keeps travelling up infinitely. The problem is to find the minimum number of arrows that must be shot to burst all balloons.

*Example:*

[subs="verbatim,quotes,macros"]
----
*Input:*
[[10,16], [2,8], [1,6], [7,12]]

*Output:*
2

*Explanation:*
One way is to shoot one arrow for example at x = 6 (bursting the balloons [2,8] and [1,6]) and another arrow at x = 11 (bursting the other two balloons).
----

 



[[src-0452]]
[{java_src_attr}]
----
include::{sourcedir}/_0452_MinimumNumberOfArrowsToBurstBalloons.java[tag=answer]
----

