[#0458-poor-pigs]
= 458. Poor Pigs

https://leetcode.com/problems/poor-pigs/[LeetCode - Poor Pigs]

There are 1000 buckets, one and only one of them is poisonous, while the rest are filled with water. They all look identical. If a pig drinks the poison it will die within 15 minutes. What is the minimum amount of pigs you need to figure out which bucket is poisonous within one hour?

Answer this question, and write an algorithm for the general case.

 

*General case: *

If there are `n` buckets and a pig drinking poison will die within `m` minutes, how many pigs (`x`) you need to figure out the *poisonous* bucket within `p` minutes? There is exactly one bucket with poison.

 

*Note:*


. A pig can be allowed to drink simultaneously on as many buckets as one would like, and the feeding takes no time.
. After a pig has instantly finished drinking buckets, there has to be a *cool down time* of _m _minutes. During this time, only observation is allowed and no feedings at all.
. Any given bucket can be sampled an infinite number of times (by an unlimited number of pigs).



[[src-0458]]
[{java_src_attr}]
----
include::{sourcedir}/_0458_PoorPigs.java[tag=answer]
----

