[#0494-target-sum]
= 494. Target Sum

{leetcode}/problems/target-sum/[LeetCode - Target Sum^]

You are given a list of non-negative integers, a1, a2, ..., an, and a target, S. Now you have 2 symbols `+` and `-`. For each integer, you should choose one from `+` and `-` as its new symbol.

Find out how many ways to assign symbols to make sum of integers equal to target S.

.Example 1:
----
Input: nums is [1, 1, 1, 1, 1], S is 3.
Output: 5
Explanation:

-1+1+1+1+1 = 3
+1-1+1+1+1 = 3
+1+1-1+1+1 = 3
+1+1+1-1+1 = 3
+1+1+1+1-1 = 3

There are 5 ways to assign symbols to make the sum of nums be target 3.
----

*Note:*

. The length of the given array is positive and will not exceed 20.
. The sum of elements in the given array will not exceed 1000.
. Your output answer is guaranteed to be fitted in a 32-bit integer.

== 解题分析

这道题可以使用 DFS 解决。不过，需要注意的是，只需要保存关键变量即可。另外，也可以增加实例变量。

== 思考题

. 再推敲一下动态规划的解法；
. 学习背包问题！

== 参考资料

. https://leetcode-cn.com/problems/target-sum/solution/mu-biao-he-by-leetcode/[目标和 - 目标和 - 力扣（LeetCode）^]
. https://leetcode-cn.com/problems/target-sum/solution/dong-tai-gui-hua-ji-bai-liao-98de-javayong-hu-by-r/[动态规划击败了98%的java用户 - 目标和 - 力扣（LeetCode）^]



You are given a list of non-negative integers, a1, a2, ..., an, and a target, S. Now you have 2 symbols `+` and `-`. For each integer, you should choose one from `+` and `-` as its new symbol.
 

Find out how many ways to assign symbols to make sum of integers equal to target S.  


*Example 1:*


[subs="verbatim,quotes,macros"]
----
*Input:* nums is [1, 1, 1, 1, 1], S is 3. 
*Output:* 5
*Explanation:* 

-1+1+1+1+1 = 3
+1-1+1+1+1 = 3
+1+1-1+1+1 = 3
+1+1+1-1+1 = 3
+1+1+1+1-1 = 3

There are 5 ways to assign symbols to make the sum of nums be target 3.
----


*Note:*

. The length of the given array is positive and will not exceed 20. 
. The sum of elements in the given array will not exceed 1000.
. Your output answer is guaranteed to be fitted in a 32-bit integer.




[[src-0494]]
[{java_src_attr}]
----
include::{sourcedir}/_0494_TargetSum.java[tag=answer]
----

