== 543. Diameter of Binary Tree

https://leetcode.com/problems/diameter-of-binary-tree/[LeetCode - Diameter of Binary Tree]

Given a binary tree, you need to compute the length of the diameter of the tree. The diameter of a binary tree is the length of the *longest* path between any two nodes in a tree. This path may or may not pass through the root.

.Example:
----
Given a binary tree
        1
       / \
      2   3
     / \
    4   5
Return 3, which is the length of the path [4,2,1,3] or [5,2,1,3].
----

*Note:* The length of path between two nodes is represented by the number of edges between them.

=== 解题分析

这道题就是一个深度优先搜索。不同之处在于，要在遍历过程中，把直径的最大值保存下来。同时，还要返回子树中最长的路径。

=== 参考资料

. https://leetcode-cn.com/problems/diameter-of-binary-tree/solution/er-cha-shu-de-zhi-jing-by-leetcode/[二叉树的直径 - 二叉树的直径 - 力扣（LeetCode）]


Given a binary tree, you need to compute the length of the diameter of the tree. The diameter of a binary tree is the length of the *longest* path between any two nodes in a tree. This path may or may not pass through the root.



*Example:*


Given a binary tree 


[subs="verbatim,quotes,macros"]
----
          1
         / \
        2   3
       / \     
      4   5    
----


Return *3*, which is the length of the path [4,2,1,3] or [5,2,1,3].


*Note:*
The length of path between two nodes is represented by the number of edges between them.



[[src-0543]]
[source,{java_source_attr}]
----
include::{sourcedir}/_0543_DiameterOfBinaryTree.java[]
----

