[#0581-shortest-unsorted-continuous-subarray]
= 581. Shortest Unsorted Continuous Subarray

https://leetcode.com/problems/shortest-unsorted-continuous-subarray/[LeetCode - Shortest Unsorted Continuous Subarray^]

Given an integer array, you need to find one *continuous subarray* that if you only sort this subarray in ascending order, then the whole array will be sorted in ascending order, too.

You need to find the *shortest* such subarray and output its length.

.Example 1:
----
Input: [2, 6, 4, 8, 10, 9, 15]
Output: 5
Explanation: You need to sort [6, 4, 8, 10, 9] in ascending order to make the whole array sorted in ascending order.
----

*Note:*

. Then length of the input array is in range [1, 10,000].
. The input array may contain duplicates, so ascending order here means **<=**.

== 解题分析

第一种办法就是对数组进行排序，然后跟原数组进行对比，看看那个元素变化了。

第二种办法就是从两边找逆序的小和大，然后再从两段寻找需要调整的元素。

== 思考题

再推敲一下从两段两段夹逼的阶梯方法。

== 参考资料

. https://leetcode-cn.com/problems/shortest-unsorted-continuous-subarray/solution/zui-duan-wu-xu-lian-xu-zi-shu-zu-by-leetcode/[最短无序连续子数组 - 最短无序连续子数组 - 力扣（LeetCode）^]

Given an integer array, you need to find one *continuous subarray* that if you only sort this subarray in ascending order, then the whole array will be sorted in ascending order, too.  

You need to find the *shortest* such subarray and output its length.

*Example 1:*


[subs="verbatim,quotes,macros"]
----
*Input:* [2, 6, 4, 8, 10, 9, 15]
*Output:* 5
*Explanation:* You need to sort [6, 4, 8, 10, 9] in ascending order to make the whole array sorted in ascending order.
----


*Note:*

. Then length of the input array is in range [1, 10,000].
. The input array may contain duplicates, so ascending order here means *<=*. 




[[src-0581]]
[{java_src_attr}]
----
include::{sourcedir}/_0581_ShortestUnsortedContinuousSubarray.java[tag=answer]
----

