[#0691-stickers-to-spell-word]
= 691. Stickers to Spell Word

https://leetcode.com/problems/stickers-to-spell-word/[LeetCode - Stickers to Spell Word^]


We are given N different types of stickers.  Each sticker has a lowercase English word on it.

You would like to spell out the given `target` string by cutting individual letters from your collection of stickers and rearranging them.

You can use each sticker more than once if you want, and you have infinite quantities of each sticker.

What is the minimum number of stickers that you need to spell out the `target`?  If the task is impossible, return -1.


*Example 1:*
Input:[subs="verbatim,quotes,macros"]
----
["with", "example", "science"], "thehat"
----

Output:[subs="verbatim,quotes,macros"]
----
3
----

Explanation:[subs="verbatim,quotes,macros"]
----
We can use 2 "with" stickers, and 1 "example" sticker.
After cutting and rearrange the letters of those stickers, we can form the target "thehat".
Also, this is the minimum number of stickers necessary to form the target string.
----

*Example 2:*
Input:[subs="verbatim,quotes,macros"]
----
["notice", "possible"], "basicbasic"
----

Output:[subs="verbatim,quotes,macros"]
----
-1
----

Explanation:[subs="verbatim,quotes,macros"]
----
We can't form the target "basicbasic" from cutting letters from the given stickers.
----

*Note:*
. `stickers` has length in the range `[1, 50]`.</li>
. `stickers` consists of lowercase English words (without apostrophes).</li>
. `target` has length in the range `[1, 15]`, and consists of lowercase English letters.</li>
. In all test cases, all words were chosen [.underline]#randomly# from the 1000 most common US English words, and the target was chosen as a concatenation of two random words.</li>
. The time limit may be more challenging than usual.  It is expected that a 50 sticker test case can be solved within 35ms on average.</li>



[[src-0691]]
[{java_src_attr}]
----
include::{sourcedir}/_0691_StickersToSpellWord.java[tag=answer]
----

