[#0714-best-time-to-buy-and-sell-stock-with-transaction-fee]
= 714. Best Time to Buy and Sell Stock with Transaction Fee

https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/[LeetCode - Best Time to Buy and Sell Stock with Transaction Fee]

Your are given an array of integers `prices`, for which the _i^th^_ element is the price of a given stock on day i; and a non-negative integer `fee` representing a transaction fee.

You may complete as many transactions as you like, but you need to pay the transaction fee for each transaction. You may not buy more than 1 share of a stock at a time (ie. you must sell the stock share before you buy again.)

Return the maximum profit you can make.

.Example 1:
[subs="verbatim,quotes,macros"]
----
Input: prices = [1, 3, 2, 8, 4, 9], fee = 2
Output: 8
*Explanation:* The maximum profit can be achieved by:
* Buying at prices[0] = 1
* Selling at prices[3] = 8
* Buying at prices[4] = 4
* Selling at prices[5] = 9
The total profit is ((8 - 1) - 2) + ((9 - 4) - 2) = 8.
----

*Note:*

* `0 < prices.length <= 50000`.
* `0 < prices[i] < 50000`.
* `0 <= fee < 50000`.

针对 https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/solution/yi-ge-fang-fa-tuan-mie-6-dao-gu-piao-wen-ti-by-lab/[一个方法团灭 6 道股票问题 - 最佳买卖股票时机含冷冻期 - 力扣（LeetCode）] 这个解题框架，进行小试牛刀。

== 参考资料

. https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/solution/yi-ge-fang-fa-tuan-mie-6-dao-gu-piao-wen-ti-by-lab/[一个方法团灭 6 道股票问题 - 最佳买卖股票时机含冷冻期 - 力扣（LeetCode）]
. https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/solution/dong-tai-gui-hua-shen-ru-fen-xi-by-wang-yan-19/[动态规划深入分析 - 最佳买卖股票时机含冷冻期 - 力扣（LeetCode）]

Your are given an array of integers `prices`, for which the `i`-th element is the price of a given stock on day `i`; and a non-negative integer `fee` representing a transaction fee.
You may complete as many transactions as you like, but you need to pay the transaction fee for each transaction.  You may not buy more than 1 share of a stock at a time (ie. you must sell the stock share before you buy again.)
Return the maximum profit you can make.

*Example 1:*


[subs="verbatim,quotes,macros"]
----
*Input:* prices = [1, 3, 2, 8, 4, 9], fee = 2
*Output:* 8
*Explanation:* The maximum profit can be achieved by:
. Buying at prices[0] = 1</li>. Selling at prices[3] = 8</li>. Buying at prices[4] = 4</li>. Selling at prices[5] = 9</li>The total profit is ((8 - 1) - 2) + ((9 - 4) - 2) = 8.
----


*Note:*
. `0 < prices.length <= 50000`.</li>
. `0 < prices[i] < 50000`.</li>
. `0 <= fee < 50000`.</li>



[[src-0714]]
[{java_src_attr}]
----
include::{sourcedir}/_0714_BestTimeToBuyAndSellStockWithTransactionFee.java[]
----

