[#0826-most-profit-assigning-work]
= 826. 安排工作以达到最大收益

https://leetcode.cn/problems/most-profit-assigning-work/[LeetCode - 826. 安排工作以达到最大收益^]

你有 `n` 个工作和 `m` 个工人。给定三个数组： `difficulty`, `profit` 和 `worker`，其中:

* `difficulty[i]` 表示第 `i` 个工作的难度，`profit[i]` 表示第 `i` 个工作的收益。
* `worker[i]` 是第 `i` 个工人的能力，即该工人只能完成难度小于等于 `worker[i]` 的工作。

每个工人 *最多* 只能安排 *一个* 工作，但是一个工作可以 *完成多次* 。

* 举个例子，如果 3 个工人都尝试完成一份报酬为 `$1` 的同样工作，那么总收益为 `$3` 。如果一个工人不能完成任何工作，他的收益为 `$0`。

返回 _在把工人分配到工作岗位后，我们所能获得的最大利润_。

*示例 1：*

....
输入: difficulty = [2,4,6,8,10], profit = [10,20,30,40,50], worker = [4,5,6,7]
输出: 100
解释: 工人被分配的工作难度是 [4,4,6,6] ，分别获得 [20,20,30,30] 的收益。
....

*示例 2:*

....
输入: difficulty = [85,47,57], profit = [24,66,99], worker = [40,25,25]
输出: 0
....

*提示:*

* `n == difficulty.length`
* `n == profit.length`
* `m == worker.length`
* `1 \<= n, m \<= 10^4^`
* `1 \<= difficulty[i], profit[i], worker[i] \<= 10^5^`



== 思路分析

先将 `worker` 排序，然后对 `profit` 和 `difficulty` 排序： `profit` 优先，相同则再根据 `difficulty` 排序。从后向前遍历 `worker`，只要 `difficulty` 满足，优先取获利最大的工作。

TIP: 有点蒙对的感觉。不如题解更有说服力。

[[src-0826]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0826_MostProfitAssigningWork.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_0826_MostProfitAssigningWork_2.java[tag=answer]
// ----
// --
====


== 参考资料

. https://leetcode.cn/problems/most-profit-assigning-work/solutions/2780326/pai-xu-shuang-zhi-zhen-pythonjavacgojsru-gthg/[826. 安排工作以达到最大收益 - 排序+双指针^]
. https://leetcode.cn/problems/most-profit-assigning-work/solutions/2776977/an-pai-gong-zuo-yi-da-dao-zui-da-shou-yi-c0s1/[826. 安排工作以达到最大收益 - 官方题解^]
