[#0855-exam-room]
= 855. 考场就座

https://leetcode.cn/problems/exam-room/[LeetCode - 855. 考场就座^]

在考场里，一排有 `N` 个座位，分别编号为 `0, 1, 2, ..., N-1` 。

当学生进入考场后，他必须坐在能够使他与离他最近的人之间的距离达到最大化的座位上。如果有多个这样的座位，他会坐在编号最小的座位上。(另外，如果考场里没有人，那么学生就坐在 0 号座位上。)

返回 `ExamRoom(int N)` 类，它有两个公开的函数：其中，函数 `ExamRoom.seat()` 会返回一个 `int`（整型数据），代表学生坐的位置；函数 `ExamRoom.leave(int p)` 代表坐在座位 `p` 上的学生现在离开了考场。每次调用 `ExamRoom.leave(p)` 时都保证有学生坐在座位 `p` 上。

*示例：*

....
输入：["ExamRoom","seat","seat","seat","seat","leave","seat"], [[10],[],[],[],[],[4],[]]
输出：[null,0,9,4,2,null,5]
解释：
ExamRoom(10) -> null
seat() -> 0，没有人在考场里，那么学生坐在 0 号座位上。
seat() -> 9，学生最后坐在 9 号座位上。
seat() -> 4，学生最后坐在 4 号座位上。
seat() -> 2，学生最后坐在 2 号座位上。
leave(4) -> null
seat() -> 5，学生最后坐在 5 号座位上。
....

*提示：*

. `1 \<= N \<= 10^9^`
. 在所有的测试样例中 `ExamRoom.seat()` 和 `ExamRoom.leave()` 最多被调用 `10^4` 次。
. 保证在调用 `ExamRoom.leave(p)` 时有学生正坐在座位 `p` 上。


== 思路分析

有序集合+优先队列：有序集合保存已选位置，优先队列保存下一个符合要求的位置。

TIP: 延迟删除的技巧，还需要再琢磨一下。

[[src-0855]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0855_ExamRoom.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_0855_ExamRoom_2.java[tag=answer]
// ----
// --
====


== 参考资料

. https://leetcode.cn/problems/exam-room/solutions/2036518/kao-chang-jiu-zuo-by-leetcode-solution-074y/[855. 考场就座 - 官方题解^]
. https://leetcode.cn/problems/exam-room/solutions/2037447/by-lcbin-tstp/[855. 考场就座 - 一题一解：有序集合 + 哈希表^]
. https://leetcode.cn/problems/exam-room/solutions/2037441/liang-chong-jie-fa-you-xu-ji-he-you-xian-bjrv/[855. 考场就座 - 有序集合 & 优先队列优化^]
