[#0875-koko-eating-bananas]
= 875. Koko Eating Bananas

https://leetcode.com/problems/koko-eating-bananas/[LeetCode - Koko Eating Bananas^]

Koko loves to eat bananas.  There are `N` piles of bananas, the `i`-th pile has `piles[i]` bananas.  The guards have gone and will come back in `H` hours.

Koko can decide her bananas-per-hour eating speed of `K`.  Each hour, she chooses some pile of bananas, and eats K bananas from that pile.  If the pile has less than `K` bananas, she eats all of them instead, and won't eat any more bananas during this hour.

Koko likes to eat slowly, but still wants to finish eating all the bananas before the guards come back.

Return the minimum integer `K` such that she can eat all the bananas within `H` hours.


*Example 1:*

[subs="verbatim,quotes,macros"]
----
*Input:* piles = [3,6,7,11], H = 8
*Output:* 4
----

*Example 2:*

[subs="verbatim,quotes,macros"]
----
*Input:* piles = [30,11,23,4,20], H = 5
*Output:* 30
----

*Example 3:*

[subs="verbatim,quotes,macros"]
----
*Input:* piles = [30,11,23,4,20], H = 6
*Output:* 23
----

 

*Note:*


* `1 <= piles.length <= 10^4`
* `piles.length <= H <= 10^9`
* `1 <= piles[i] <= 10^9`



== 思路分析


[[src-0875]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_0875_KokoEatingBananas.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_0098_ValidateBinarySearchTree_2.java[tag=answer]
// ----
// --
====

== 参考资料

. https://leetcode.cn/problems/koko-eating-bananas/solutions/1537914/ai-chi-xiang-jiao-de-ke-ke-by-leetcode-s-z4rt/[875. 爱吃香蕉的珂珂 - 官方题解^]
. https://leetcode.cn/problems/koko-eating-bananas/solutions/51963/er-fen-cha-zhao-ding-wei-su-du-by-liweiwei1419/[875. 爱吃香蕉的珂珂 - 二分查找定位速度（最大值最小化问题，Java）^]
. https://leetcode.cn/problems/binary-search/solutions/8337/er-fen-cha-zhao-xiang-jie-by-labuladong/[704. 二分查找 - 二分查找细节详解，顺便赋诗一首^]

