== 888. Fair Candy Swap

https://leetcode.com/problems/fair-candy-swap/[LeetCode - Fair Candy Swap]

Alice and Bob have candy bars of different sizes: `A[i]` is the size of the `i`-th bar of candy that Alice has, and `B[j]` is the size of the `j`-th bar of candy that Bob has.

Since they are friends, they would like to exchange one candy bar each so that after the exchange, they both have the same total amount of candy.  (_The total amount of candy a person has is the sum of the sizes of candy bars they have._)

Return an integer array `ans` where `ans[0]` is the size of the candy bar that Alice must exchange, and `ans[1]` is the size of the candy bar that Bob must exchange.

If there are multiple answers, you may return any one of them.  It is guaranteed an answer exists.

 


*Example 1:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-1-1">[1,1], B = <span id="example-input-1-2">[2,2]
*Output: *<span id="example-output-1">[1,2]
----


*Example 2:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-2-1">[1,2], B = <span id="example-input-2-2">[2,3]
*Output: *<span id="example-output-2">[1,2]
----


*Example 3:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-3-1">[2], B = <span id="example-input-3-2">[1,3]
*Output: *<span id="example-output-3">[2,3]
----


*Example 4:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-4-1">[1,2,5], B = <span id="example-input-4-2">[2,4]
*Output: *<span id="example-output-4">[5,4]
----

 

*Note:*


* `1 <= A.length <= 10000`
* `1 <= B.length <= 10000`
* `1 <= A[i] <= 100000`
* `1 <= B[i] <= 100000`
* It is guaranteed that Alice and Bob have different total amounts of candy.
* It is guaranteed there exists an answer.






