[#0904-fruit-into-baskets]
= 904. Fruit Into Baskets

{leetcode}/problems/fruit-into-baskets/[LeetCode - Fruit Into Baskets^]

In a row of trees, the `i`-th tree produces fruit with type `tree[i]`.

You *start at any tree of your choice*, then repeatedly perform the following steps:


. Add one piece of fruit from this tree to your baskets.  If you cannot, stop.
. Move to the next tree to the right of the current tree.  If there is no tree to the right, stop.


Note that you do not have any choice after the initial choice of starting tree: you must perform step 1, then step 2, then back to step 1, then step 2, and so on until you stop.

You have two baskets, and each basket can carry any quantity of fruit, but you want each basket to only carry one type of fruit each.

What is the total amount of fruit you can collect with this procedure?

 

*Example 1:*

[subs="verbatim,quotes,macros"]
----
*Input:* [1,2,1]
*Output:* 3
*Explanation:* We can collect [1,2,1].
----


*Example 2:*

[subs="verbatim,quotes,macros"]
----
*Input:* [0,1,2,2]
*Output:* 3
*Explanation:* We can collect [1,2,2].
If we started at the first tree, we would only collect [0, 1].
----


*Example 3:*

[subs="verbatim,quotes,macros"]
----
*Input:* [1,2,3,2,2]
*Output:* 4
*Explanation:* We can collect [2,3,2,2].
If we started at the first tree, we would only collect [1, 2].
----


*Example 4:*

[subs="verbatim,quotes,macros"]
----
*Input:* [3,3,3,1,2,1,1,2,3,3,4]
*Output:* 5 
*Explanation:* We can collect [1,2,1,1,2].
If we started at the first tree or the eighth tree, we would only collect 4 fruits.
----

 




*Note:*


. `1 \<= tree.length \<= 40000`
. `0 \<= tree[i] \< tree.length`

== 思路分析


[[src-0904]]
[{java_src_attr}]
----
include::{sourcedir}/_0904_FruitIntoBaskets.java[tag=answer]
----

== 参考资料

. https://leetcode.cn/problems/fruit-into-baskets/solutions/1893352/shui-guo-cheng-lan-by-leetcode-solution-1uyu/[904. 水果成篮 - 官方题解^]
. https://leetcode.cn/problems/fruit-into-baskets/solutions/1437444/shen-du-jie-xi-zhe-dao-ti-he-by-linzeyin-6crr/[904. 水果成篮 - 【深度解析】这道题和76. 最小覆盖子串的区别^]
. https://leetcode.cn/problems/fruit-into-baskets/solutions/1897490/by-ac_oier-skgk/[904. 水果成篮 - 【宫水三叶】简单滑动窗口运用题^]

