== 972. Equal Rational Numbers

https://leetcode.com/problems/equal-rational-numbers/[LeetCode - Equal Rational Numbers]

Given two strings `S` and `T`, each of which represents a non-negative rational number, return *True* if and only if they represent the same number. The strings may use parentheses to denote the repeating part of the rational number.

In general a rational number can be represented using up to three parts: an _integer part_, a _non-repeating part,_ and a _repeating part_. The number will be represented in one of the following three ways:


* `<IntegerPart>` (e.g. 0, 12, 123)
* `<IntegerPart><.><NonRepeatingPart>`  (e.g. 0.5, 1., 2.12, 2.0001)
* `<IntegerPart><.><NonRepeatingPart><(><RepeatingPart><)>` (e.g. 0.1(6), 0.9(9), 0.00(1212))


The repeating portion of a decimal expansion is conventionally denoted within a pair of round brackets.  For example:

1 / 6 = 0.16666666... = 0.1(6) = 0.1666(6) = 0.166(66)

Both 0.1(6) or 0.1666(6) or 0.166(66) are correct representations of 1 / 6.

 

*Example 1:*

[subs="verbatim,quotes"]
----
*Input: *S = <span id="example-input-1-1">"0.(52)", T = <span id="example-input-1-2">"0.5(25)"
*Output: *<span id="example-output-1">true
*Explanation:
*Because "0.(52)" represents 0.52525252..., and "0.5(25)" represents 0.52525252525..... , the strings represent the same number.

----


*Example 2:*

[subs="verbatim,quotes"]
----
*Input: *S = <span id="example-input-2-1">"0.1666(6)", T = <span id="example-input-2-2">"0.166(66)"
*Output: *<span id="example-output-2">true

----


*Example 3:*

[subs="verbatim,quotes"]
----
*Input: *S = <span id="example-input-3-1">"0.9(9)", T = <span id="example-input-3-2">"1."
*Output: *<span id="example-output-3">true
*Explanation: *
"0.9(9)" represents 0.999999999... repeated forever, which equals 1.  [https://en.wikipedia.org/wiki/0.999...[See this link for an explanation.]]
"1." represents the number 1, which is formed correctly: (IntegerPart) = "1" and (NonRepeatingPart) = "".
----

 



*Note:*


* Each part consists only of digits.
* The `<IntegerPart>` will not begin with 2 or more zeros.  (There is no other restriction on the digits of each part.)
* `1 <= <IntegerPart>.length <= 4 `
* `0 <= <NonRepeatingPart>.length <= 4 `
* `1 <= <RepeatingPart>.length <= 4`


