== 992. Subarrays with K Different Integers

https://leetcode.com/problems/subarrays-with-k-different-integers/[LeetCode - Subarrays with K Different Integers]

Given an array `A` of positive integers, call a (contiguous, not necessarily distinct) subarray of `A` good if the number of different integers in that subarray is exactly `K`.

(For example, `[1,2,3,1,2]` has `3` different integers: `1`, `2`, and `3`.)

Return the number of good subarrays of `A`.

.Example 1:
----
Input: A = [1,2,1,2,3], K = 2
Output: 7
Explanation: Subarrays formed with exactly 2 different integers: [1,2], [2,1], [1,2], [2,3], [1,2,1], [2,1,2], [1,2,1,2].
----

.Example 2:
----
Input: A = [1,2,1,3,4], K = 3
Output: 3
Explanation: Subarrays formed with exactly 3 different integers: [1,2,1,3], [2,1,3], [1,3,4].
----

*Note:*

* `1 <= A.length <= 20000`
* `1 <= A[i] <= A.length`
* `1 <= K <= A.length`

=== 解题分析

解题中心思路是滑动窗口。

=== 思考题

这个解题方案怎么理解？

=== 参考资料

. https://mp.weixin.qq.com/s/6YeZUCYj5ft-OGa85sQegw[面试官，你再问我滑动窗口问题试试？我有解题模板，不怕！]
. https://leetcode-cn.com/problems/subarrays-with-k-different-integers/solution/k-ge-bu-tong-zheng-shu-de-zi-shu-zu-by-leetcode/[K 个不同整数的子数组 - K 个不同整数的子数组 - 力扣（LeetCode）]
. https://leetcode-cn.com/problems/subarrays-with-k-different-integers/solution/fang-zhao-guan-fang-ti-jie-ti-gong-geng-jia-qing-x/[仿照官方题解 提供更加清晰直观的解释 - K 个不同整数的子数组 - 力扣（LeetCode）]

Given an array `A` of positive integers, call a (contiguous, not necessarily distinct) subarray of `A` _good_ if the number of different integers in that subarray is exactly `K`.

(For example, `[1,2,3,1,2]` has `3` different integers: `1`, `2`, and `3`.)

Return the number of good subarrays of `A`.

 

*Example 1:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-1-1">[1,2,1,2,3], K = <span id="example-input-1-2">2
*Output: *<span id="example-output-1">7
*Explanation: *Subarrays formed with exactly 2 different integers: [1,2], [2,1], [1,2], [2,3], [1,2,1], [2,1,2], [1,2,1,2].
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input: *A = <span id="example-input-2-1">[1,2,1,3,4], K = <span id="example-input-2-2">3
*Output: *<span id="example-output-2">3
*Explanation: *Subarrays formed with exactly 3 different integers: [1,2,1,3], [2,1,3], [1,3,4].
----

 

*Note:*


. `1 <= A.length <= 20000`
. `1 <= A[i] <= A.length`
. `1 <= K <= A.length`

