[#1006-clumsy-factorial]
= 1006. Clumsy Factorial

https://leetcode.com/problems/clumsy-factorial/[LeetCode - Clumsy Factorial^]

Normally, the factorial of a positive integer `n` is the product of all positive integers less than or equal to `n`.  For example, `factorial(10) = 10 * 9 * 8 * 7 * 6 * 5 * 4 * 3 * 2 * 1`.

We instead make a _clumsy factorial:_ using the integers in decreasing order, we swap out the multiply operations for a fixed rotation of operations: multiply (*), divide (/), add (+) and subtract (-) in this order.

For example, `clumsy(10) = 10 * 9 / 8 + 7 - 6 * 5 / 4 + 3 - 2 * 1`.  However, these operations are still applied using the usual order of operations of arithmetic: we do all multiplication and division steps before any addition or subtraction steps, and multiplication and division steps are processed left to right.

Additionally, the division that we use is _floor division_ such that `10 * 9 / 8` equals `11`.  This guarantees the result is an integer.

`<font face="sans-serif, Arial, Verdana, Trebuchet MS">Implement the clumsy` function as defined above: given an integer `N`, it returns the clumsy factorial of `N`.

 

*Example 1:*

[subs="verbatim,quotes,macros"]
----
*Input:* 4
*Output:* 7
*Explanation:* 7 = 4 * 3 / 2 + 1
----

*Example 2:*

[subs="verbatim,quotes,macros"]
----
*Input:* 10
*Output:* 12
*Explanation:* 12 = 10 * 9 / 8 + 7 - 6 * 5 / 4 + 3 - 2 * 1
----

 

*Note:*


. `1 <= N <= 10000`
. `-2^31 <= answer <= 2^31 - 1`  (The answer is guaranteed to fit within a 32-bit integer.)




[[src-1006]]
[{java_src_attr}]
----
include::{sourcedir}/_1006_ClumsyFactorial.java[tag=answer]
----

