[#1023-camelcase-matching]
= 1023. 驼峰式匹配

https://leetcode.cn/problems/camelcase-matching/[LeetCode - 1023. 驼峰式匹配 ^]

给你一个字符串数组 `queries`，和一个表示模式的字符串 `pattern`，请你返回一个布尔数组 `answer` 。只有在待查项 `queries[i]` 与模式串 `pattern` 匹配时， `answer[i]` 才为 `true`，否则为 `false`。

如果可以将**小写字母**插入模式串 `pattern` 得到待查询项 `queries[i]`，那么待查询项与给定模式串匹配。可以在任何位置插入每个字符，也可以不插入字符。

*示例 1：*

....
输入：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FB"
输出：[true,false,true,true,false]
示例：
"FooBar" 可以这样生成："F" + "oo" + "B" + "ar"。
"FootBall" 可以这样生成："F" + "oot" + "B" + "all".
"FrameBuffer" 可以这样生成："F" + "rame" + "B" + "uffer".
....

*示例 2：*

....
输入：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FoBa"
输出：[true,false,true,false,false]
解释：
"FooBar" 可以这样生成："Fo" + "o" + "Ba" + "r".
"FootBall" 可以这样生成："Fo" + "ot" + "Ba" + "ll".
....

*示例 3：*

....
输入：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FoBaT"
输出：[false,true,false,false,false]
解释：
"FooBarTest" 可以这样生成："Fo" + "o" + "Ba" + "r" + "T" + "est".
....


*提示：*

* `+1 <= pattern.length, queries.length <= 100+`
* `+1 <= queries[i].length <= 100+`
* `queries[i]` 和 `pattern` 由英文字母组成


== 思路分析

逐个字符去遍历，相同则添加到 `sb` 中，如果不同，是大写就直接返回 `false`，如果是小写就把原字符添加到 `sb` 中。匹配结束，如果 `pattern` 没有到结尾就 `false`。遍历字符串剩余字符，如果有大写字符就判错，否则添加到 `sb`，最后判断 `sb` 和原字符串是否相同。

[[src-1023]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1023_CamelcaseMatching.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1023_CamelcaseMatching_2.java[tag=answer]
// ----
// --
====


== 参考资料

. https://leetcode.cn/problems/camelcase-matching/solutions/2225856/python3javacgotypescript-yi-ti-yi-jie-sh-vr5x/[1023. 驼峰式匹配 - 一题一解：双指针（清晰题解）^]
. https://leetcode.cn/problems/camelcase-matching/solutions/2224532/tuo-feng-shi-pi-pei-by-leetcode-solution-pwq7/[1023. 驼峰式匹配 - 官方题解^]
