== 1034. Coloring A Border

https://leetcode.com/problems/coloring-a-border/[LeetCode - Coloring A Border]

Given a 2-dimensional `grid` of integers, each value in the grid represents the color of the grid square at that location.

Two squares belong to the same _connected component_ if and only if they have the same color and are next to each other in any of the 4 directions.

The _border_ of a connected component is all the squares in the connected component that are either 4-directionally adjacent to a square not in the component, or on the boundary of the grid (the first or last row or column).

Given a square at location `(r0, c0)` in the grid and a `color`, color the border of the connected component of that square with the given `color`, and return the final `grid`.

 

*Example 1:*

[subs="verbatim,quotes"]
----
*Input: *grid = <span id="example-input-1-1">[[1,1],[1,2]], r0 = <span id="example-input-1-2">0, c0 = <span id="example-input-1-3">0, color = <span id="example-input-1-4">3
*Output: *<span id="example-output-1">[[3, 3], [3, 2]]
----


*Example 2:*

[subs="verbatim,quotes"]
----
*Input: *grid = <span id="example-input-2-1">[[1,2,2],[2,3,2]], r0 = <span id="example-input-2-2">0, c0 = <span id="example-input-2-3">1, color = <span id="example-input-2-4">3
*Output: *<span id="example-output-2">[[1, 3, 3], [2, 3, 3]]
----


*Example 3:*

[subs="verbatim,quotes"]
----
*Input: *grid = <span id="example-input-3-1">[[1,1,1],[1,1,1],[1,1,1]], r0 = <span id="example-input-3-2">1, c0 = <span id="example-input-3-3">1, color = <span id="example-input-3-4">2
*Output: *<span id="example-output-3">[[2, 2, 2], [2, 1, 2], [2, 2, 2]]
----



 

*Note:*


. `1 <= grid.length <= 50`
. `1 <= grid[0].length <= 50`
. `1 <= grid[i][j] <= 1000`
. `0 <= r0 < grid.length`
. `0 <= c0 < grid[0].length`
. `1 <= color <= 1000`

