[#1370-increasing-decreasing-string]
= 1370. Increasing Decreasing String

{leetcode}/problems/increasing-decreasing-string/[LeetCode - 1370. Increasing Decreasing String ^]

You are given a string `s`. Reorder the string using the following algorithm:


* Pick the *smallest* character from `s` and *append* it to the result.
* Pick the *smallest* character from `s` which is greater than the last appended character to the result and *append* it.
* Repeat step 2 until you cannot pick more characters.
* Pick the *largest* character from `s` and *append* it to the result.
* Pick the *largest* character from `s` which is smaller than the last appended character to the result and *append* it.
* Repeat step 5 until you cannot pick more characters.
* Repeat the steps from 1 to 6 until you pick all characters from `s`.


In each step, If the smallest or the largest character appears more than once you can choose any occurrence and append it to the result.

Return _the result string after sorting _`s`_ with this algorithm_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "aaaabbbbcccc"
*Output:* "abccbaabccba"
*Explanation:* After steps 1, 2 and 3 of the first iteration, result = "abc"
After steps 4, 5 and 6 of the first iteration, result = "abccba"
First iteration is done. Now s = "aabbcc" and we go back to step 1
After steps 1, 2 and 3 of the second iteration, result = "abccbaabc"
After steps 4, 5 and 6 of the second iteration, result = "abccbaabccba"
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "rat"
*Output:* "art"
*Explanation:* The word "rat" becomes "art" after re-ordering it with the mentioned algorithm.
----

 
*Constraints:*


* `1 <= s.length <= 500`
* `s` consists of only lowercase English letters.




== 思路分析


[[src-1370]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1370_IncreasingDecreasingString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1370_IncreasingDecreasingString_2.java[tag=answer]
// ----
// --
====


== 参考资料


