[#1383-maximum-performance-of-a-team]
= 1383. Maximum Performance of a Team

{leetcode}/problems/maximum-performance-of-a-team/[LeetCode - 1383. Maximum Performance of a Team ^]

You are given two integers `n` and `k` and two integer arrays `speed` and `efficiency` both of length `n`. There are `n` engineers numbered from `1` to `n`. `speed[i]` and `efficiency[i]` represent the speed and efficiency of the `i^th^` engineer respectively.

Choose *at most* `k` different engineers out of the `n` engineers to form a team with the maximum *performance*.

The performance of a team is the sum of its engineers' speeds multiplied by the minimum efficiency among its engineers.

Return _the maximum performance of this team_. Since the answer can be a huge number, return it *modulo* `10^9^ + 7`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 6, speed = [2,10,3,1,5,8], efficiency = [5,4,3,9,7,2], k = 2
*Output:* 60
*Explanation:* 
We have the maximum performance of the team by selecting engineer 2 (with speed=10 and efficiency=4) and engineer 5 (with speed=5 and efficiency=7). That is, performance = (10 + 5) * min(4, 7) = 60.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 6, speed = [2,10,3,1,5,8], efficiency = [5,4,3,9,7,2], k = 3
*Output:* 68
*Explanation:
*This is the same example as the first but k = 3. We can select engineer 1, engineer 2 and engineer 5 to get the maximum performance of the team. That is, performance = (2 + 10 + 5) * min(5, 4, 7) = 68.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = 6, speed = [2,10,3,1,5,8], efficiency = [5,4,3,9,7,2], k = 4
*Output:* 72
----

 
*Constraints:*


* `1 <= k <= n <= 10^5^`
* `speed.length == n`
* `efficiency.length == n`
* `1 <= speed[i] <= 10^5^`
* `1 <= efficiency[i] <= 10^8^`




== 思路分析


[[src-1383]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1383_MaximumPerformanceOfATeam.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1383_MaximumPerformanceOfATeam_2.java[tag=answer]
// ----
// --
====


== 参考资料


