[#1419-minimum-number-of-frogs-croaking]
= 1419. Minimum Number of Frogs Croaking

https://leetcode.com/problems/minimum-number-of-frogs-croaking/[LeetCode - 1419. Minimum Number of Frogs Croaking ^]

You are given the string `croakOfFrogs`, which represents a combination of the string `"croak"` from different frogs, that is, multiple frogs can croak at the same time, so multiple `"croak"` are mixed.

_Return the minimum number of _different_ frogs to finish all the croaks in the given string._

A valid `"croak"` means a frog is printing five letters `'c'`, `'r'`, `'o'`, `'a'`, and `'k'` *sequentially*. The frogs have to print all five letters to finish a croak. If the given string is not a combination of a valid `"croak"` return `-1`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* croakOfFrogs = "croakcroak"
*Output:* 1 
*Explanation:* One frog yelling "croak*"* twice.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* croakOfFrogs = "crcoakroak"
*Output:* 2 
*Explanation:* The minimum number of frogs is two. 
The first frog could yell "*cr*c*oak*roak".
The second frog could yell later "cr*c*oak*roak*".
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* croakOfFrogs = "croakcrook"
*Output:* -1
*Explanation:* The given string is an invalid combination of "croak*"* from different frogs.
----

 
*Constraints:*


* `1 <= croakOfFrogs.length <= 10^5^`
* `croakOfFrogs` is either `'c'`, `'r'`, `'o'`, `'a'`, or `'k'`.




== 思路分析


[[src-1419]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1419_MinimumNumberOfFrogsCroaking.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1419_MinimumNumberOfFrogsCroaking_2.java[tag=answer]
// ----
// --
====


== 参考资料


