[#1455-check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence]
= 1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence

{leetcode}/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/[LeetCode - 1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence ^]

Given a `sentence` that consists of some words separated by a *single space*, and a `searchWord`, check if `searchWord` is a prefix of any word in `sentence`.

Return _the index of the word in _`sentence`_ (*1-indexed*) where _`searchWord`_ is a prefix of this word_. If `searchWord` is a prefix of more than one word, return the index of the first word *(minimum index)*. If there is no such word return `-1`.

A *prefix* of a string `s` is any leading contiguous substring of `s`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "i love eating burger", searchWord = "burg"
*Output:* 4
*Explanation:* "burg" is prefix of "burger" which is the 4th word in the sentence.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "this problem is an easy problem", searchWord = "pro"
*Output:* 2
*Explanation:* "pro" is prefix of "problem" which is the 2nd and the 6th word in the sentence, but we return 2 as it's the minimal index.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "i am tired", searchWord = "you"
*Output:* -1
*Explanation:* "you" is not a prefix of any word in the sentence.
----

 
*Constraints:*


* `1 <= sentence.length <= 100`
* `1 <= searchWord.length <= 10`
* `sentence` consists of lowercase English letters and spaces.
* `searchWord` consists of lowercase English letters.




== 思路分析


[[src-1455]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1455_CheckIfAWordOccursAsAPrefixOfAnyWordInASentence.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1455_CheckIfAWordOccursAsAPrefixOfAnyWordInASentence_2.java[tag=answer]
// ----
// --
====


== 参考资料


