[#1529-minimum-suffix-flips]
= 1529. Minimum Suffix Flips

{leetcode}/problems/minimum-suffix-flips/[LeetCode - 1529. Minimum Suffix Flips ^]

You are given a *0-indexed* binary string `target` of length `n`. You have another binary string `s` of length `n` that is initially set to all zeros. You want to make `s` equal to `target`.

In one operation, you can pick an index `i` where `0 <= i < n` and flip all bits in the *inclusive* range `[i, n - 1]`. Flip means changing `'0'` to `'1'` and `'1'` to `'0'`.

Return _the minimum number of operations needed to make _`s`_ equal to _`target`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* target = "10111"
*Output:* 3
*Explanation:* Initially, s = "00000".
Choose index i = 2: "00[.underline]#000#" -> "00[.underline]#111#"
Choose index i = 0: "[.underline]#00111#" -> "[.underline]#11000#"
Choose index i = 1: "1[.underline]#1000#" -> "1[.underline]#0111#"
We need at least 3 flip operations to form target.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* target = "101"
*Output:* 3
*Explanation:* Initially, s = "000".
Choose index i = 0: "[.underline]#000#" -> "[.underline]#111#"
Choose index i = 1: "1[.underline]#11#" -> "1[.underline]#00#"
Choose index i = 2: "10[.underline]#0#" -> "10[.underline]#1#"
We need at least 3 flip operations to form target.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* target = "00000"
*Output:* 0
*Explanation:* We do not need any operations since the initial s already equals target.
----

 
*Constraints:*


* `n == target.length`
* `1 <= n <= 10^5^`
* `target[i]` is either `'0'` or `'1'`.




== 思路分析


[[src-1529]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1529_MinimumSuffixFlips.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1529_MinimumSuffixFlips_2.java[tag=answer]
// ----
// --
====


== 参考资料


