[#1541-minimum-insertions-to-balance-a-parentheses-string]
= 1541. Minimum Insertions to Balance a Parentheses String

https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/[LeetCode - 1541. Minimum Insertions to Balance a Parentheses String ^]

Given a parentheses string `s` containing only the characters `'('` and `')'`. A parentheses string is *balanced* if:


* Any left parenthesis `'('` must have a corresponding two consecutive right parenthesis `'))'`.
* Left parenthesis `'('` must go before the corresponding two consecutive right parenthesis `'))'`.


In other words, we treat `'('` as an opening parenthesis and `'))'` as a closing parenthesis.


* For example, `"())"`, `"())(())))"` and `"(())())))"` are balanced, `")()"`, `"()))"` and `"(()))"` are not balanced.


You can insert the characters `'('` and `')'` at any position of the string to balance it if needed.

Return _the minimum number of insertions_ needed to make `s` balanced.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "(()))"
*Output:* 1
*Explanation:* The second '(' has two matching '))', but the first '(' has only ')' matching. We need to add one more ')' at the end of the string to be "(())))" which is balanced.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "())"
*Output:* 0
*Explanation:* The string is already balanced.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "))())("
*Output:* 3
*Explanation:* Add '(' to match the first '))', Add '))' to match the last '('.
----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consists of `'('` and `')'` only.




== 思路分析


[[src-1541]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1541_MinimumInsertionsToBalanceAParenthesesString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1541_MinimumInsertionsToBalanceAParenthesesString_2.java[tag=answer]
// ----
// --
====


== 参考资料


