[#1585-check-if-string-is-transformable-with-substring-sort-operations]
= 1585. Check If String Is Transformable With Substring Sort Operations

https://leetcode.com/problems/check-if-string-is-transformable-with-substring-sort-operations/[LeetCode - 1585. Check If String Is Transformable With Substring Sort Operations ^]

Given two strings `s` and `t`, transform string `s` into string `t` using the following operation any number of times:


* Choose a *non-empty* substring in `s` and sort it in place so the characters are in *ascending order*.

	
	* For example, applying the operation on the underlined substring in `"1[.underline]#4234#"` results in `"1[.underline]#2344#"`.
	
	


Return `true` if _it is possible to transform `s` into `t`_. Otherwise, return `false`.

A *substring* is a contiguous sequence of characters within a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "84532", t = "34852"
*Output:* true
*Explanation:* You can transform s into t using the following sort operations:
"84[.underline]#53#2" (from index 2 to 3) -> "84[.underline]#35#2"
"[.underline]#843#52" (from index 0 to 2) -> "[.underline]#348#52"
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "34521", t = "23415"
*Output:* true
*Explanation:* You can transform s into t using the following sort operations:
"[.underline]#3452#1" -> "[.underline]#2345#1"
"234[.underline]#51#" -> "234[.underline]#15#"
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "12345", t = "12435"
*Output:* false
----

 
*Constraints:*


* `s.length == t.length`
* `1 <= s.length <= 10^5^`
* `s` and `t` consist of only digits.




== 思路分析


[[src-1585]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1585_CheckIfStringIsTransformableWithSubstringSortOperations.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1585_CheckIfStringIsTransformableWithSubstringSortOperations_2.java[tag=answer]
// ----
// --
====


== 参考资料


