[#1639-number-of-ways-to-form-a-target-string-given-a-dictionary]
= 1639. Number of Ways to Form a Target String Given a Dictionary

https://leetcode.com/problems/number-of-ways-to-form-a-target-string-given-a-dictionary/[LeetCode - 1639. Number of Ways to Form a Target String Given a Dictionary ^]

You are given a list of strings of the *same length* `words` and a string `target`.

Your task is to form `target` using the given `words` under the following rules:


* `target` should be formed from left to right.
* To form the `i^th^` character (*0-indexed*) of `target`, you can choose the `k^th^` character of the `j^th^` string in `words` if `target[i] = words[j][k]`.
* Once you use the `k^th^` character of the `j^th^` string of `words`, you *can no longer* use the `x^th^` character of any string in `words` where `x <= k`. In other words, all characters to the left of or at index `k` become unusuable for every string.
* Repeat the process until you form the string `target`.


*Notice* that you can use *multiple characters* from the *same string* in `words` provided the conditions above are met.

Return _the number of ways to form `target` from `words`_. Since the answer may be too large, return it *modulo* `10^9^ + 7`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* words = ["acca","bbbb","caca"], target = "aba"
*Output:* 6
*Explanation:* There are 6 ways to form target.
"aba" -> index 0 ("[.underline]#a#cca"), index 1 ("b[.underline]#b#bb"), index 3 ("cac[.underline]#a#")
"aba" -> index 0 ("[.underline]#a#cca"), index 2 ("bb[.underline]#b#b"), index 3 ("cac[.underline]#a#")
"aba" -> index 0 ("[.underline]#a#cca"), index 1 ("b[.underline]#b#bb"), index 3 ("acc[.underline]#a#")
"aba" -> index 0 ("[.underline]#a#cca"), index 2 ("bb[.underline]#b#b"), index 3 ("acc[.underline]#a#")
"aba" -> index 1 ("c[.underline]#a#ca"), index 2 ("bb[.underline]#b#b"), index 3 ("acc[.underline]#a#")
"aba" -> index 1 ("c[.underline]#a#ca"), index 2 ("bb[.underline]#b#b"), index 3 ("cac[.underline]#a#")
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* words = ["abba","baab"], target = "bab"
*Output:* 4
*Explanation:* There are 4 ways to form target.
"bab" -> index 0 ("[.underline]#b#aab"), index 1 ("b[.underline]#a#ab"), index 2 ("ab[.underline]#b#a")
"bab" -> index 0 ("[.underline]#b#aab"), index 1 ("b[.underline]#a#ab"), index 3 ("baa[.underline]#b#")
"bab" -> index 0 ("[.underline]#b#aab"), index 2 ("ba[.underline]#a#b"), index 3 ("baa[.underline]#b#")
"bab" -> index 1 ("a[.underline]#b#ba"), index 2 ("ba[.underline]#a#b"), index 3 ("baa[.underline]#b#")
----

 
*Constraints:*


* `1 <= words.length <= 1000`
* `1 <= words[i].length <= 1000`
* All strings in `words` have the same length.
* `1 <= target.length <= 1000`
* `words[i]` and `target` contain only lowercase English letters.




== 思路分析


[[src-1639]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1639_NumberOfWaysToFormATargetStringGivenADictionary.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1639_NumberOfWaysToFormATargetStringGivenADictionary_2.java[tag=answer]
// ----
// --
====


== 参考资料


