[#1674-minimum-moves-to-make-array-complementary]
= 1674. Minimum Moves to Make Array Complementary

{leetcode}/problems/minimum-moves-to-make-array-complementary/[LeetCode - 1674. Minimum Moves to Make Array Complementary ^]

You are given an integer array `nums` of *even* length `n` and an integer `limit`. In one move, you can replace any integer from `nums` with another integer between `1` and `limit`, inclusive.

The array `nums` is *complementary* if for all indices `i` (*0-indexed*), `nums[i] + nums[n - 1 - i]` equals the same number. For example, the array `[1,2,3,4]` is complementary because for all indices `i`, `nums[i] + nums[n - 1 - i] = 5`.

Return the _*minimum* number of moves required to make _`nums`_ *complementary*_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,4,3], limit = 4
*Output:* 1
*Explanation:* In 1 move, you can change nums to [1,2,[.underline]#2#,3] (underlined elements are changed).
nums[0] + nums[3] = 1 + 3 = 4.
nums[1] + nums[2] = 2 + 2 = 4.
nums[2] + nums[1] = 2 + 2 = 4.
nums[3] + nums[0] = 3 + 1 = 4.
Therefore, nums[i] + nums[n-1-i] = 4 for every i, so nums is complementary.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,2,1], limit = 2
*Output:* 2
*Explanation:* In 2 moves, you can change nums to [[.underline]#2#,2,2,[.underline]#2#]. You cannot change any number to 3 since 3 > limit.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,1,2], limit = 2
*Output:* 0
*Explanation:* nums is already complementary.
----

 
*Constraints:*


* `n == nums.length`
* `2 <= n <= 10^5^`
* `1 <= nums[i] <= limit <= 10^5^`
* `n` is even.




== 思路分析


[[src-1674]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1674_MinimumMovesToMakeArrayComplementary.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1674_MinimumMovesToMakeArrayComplementary_2.java[tag=answer]
// ----
// --
====


== 参考资料


