[#1675-minimize-deviation-in-array]
= 1675. Minimize Deviation in Array

{leetcode}/problems/minimize-deviation-in-array/[LeetCode - 1675. Minimize Deviation in Array ^]

You are given an array `nums` of `n` positive integers.

You can perform two types of operations on any element of the array any number of times:


* If the element is *even*, *divide* it by `2`.

	
	* For example, if the array is `[1,2,3,4]`, then you can do this operation on the last element, and the array will be `[1,2,3,[.underline]#2#].`
	
	
* If the element is *odd*, *multiply* it by `2`.
	
	* For example, if the array is `[1,2,3,4]`, then you can do this operation on the first element, and the array will be `[[.underline]#2#,2,3,4].`
	
	


The *deviation* of the array is the *maximum difference* between any two elements in the array.

Return _the *minimum deviation* the array can have after performing some number of operations._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3,4]
*Output:* 1
*Explanation:* You can transform the array to [1,2,3,[.underline]#2#], then to [[.underline]#2#,2,3,2], then the deviation will be 3 - 2 = 1.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [4,1,5,20,3]
*Output:* 3
*Explanation:* You can transform the array after two operations to [4,[.underline]#2#,5,[.underline]#5#,3], then the deviation will be 5 - 2 = 3.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,10,8]
*Output:* 3
----

 
*Constraints:*


* `n == nums.length`
* `2 <= n <= 5 * 10^<span style="font-size: 10.8333px;">4^`
* `1 <= nums[i] <= 10^9^`




== 思路分析


[[src-1675]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1675_MinimizeDeviationInArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1675_MinimizeDeviationInArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


