[#1689-partitioning-into-minimum-number-of-deci-binary-numbers]
= 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

{leetcode}/problems/partitioning-into-minimum-number-of-deci-binary-numbers/[LeetCode - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers ^]

A decimal number is called *deci-binary* if each of its digits is either `0` or `1` without any leading zeros. For example, `101` and `1100` are *deci-binary*, while `112` and `3001` are not.

Given a string `n` that represents a positive decimal integer, return _the *minimum* number of positive *deci-binary* numbers needed so that they sum up to _`n`_._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = "32"
*Output:* 3
*Explanation:* 10 + 11 + 11 = 32
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = "82734"
*Output:* 8
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = "27346209830709182346"
*Output:* 9
----

 
*Constraints:*


* `1 <= n.length <= 10^5^`
* `n` consists of only digits.
* `n` does not contain any leading zeros and represents a positive integer.




== 思路分析


[[src-1689]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1689_PartitioningIntoMinimumNumberOfDeciBinaryNumbers.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1689_PartitioningIntoMinimumNumberOfDeciBinaryNumbers_2.java[tag=answer]
// ----
// --
====


== 参考资料


