[#1702-maximum-binary-string-after-change]
= 1702. Maximum Binary String After Change

{leetcode}/problems/maximum-binary-string-after-change/[LeetCode - 1702. Maximum Binary String After Change ^]

You are given a binary string `binary` consisting of only `0`'s or `1`'s. You can apply each of the following operations any number of times:


* Operation 1: If the number contains the substring `"00"`, you can replace it with `"10"`.

	
	* For example, `"[.underline]#00#010" -> "[.underline]#10#010`"
	
	
* Operation 2: If the number contains the substring `"10"`, you can replace it with `"01"`.
	
	* For example, `"000[.underline]#10#" -> "000[.underline]#01#"`
	
	


_Return the *maximum binary string* you can obtain after any number of operations. Binary string `x` is greater than binary string `y` if `x`'s decimal representation is greater than `y`'s decimal representation._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* binary = "000110"
*Output:* "111011"
*Explanation:* A valid transformation sequence can be:
"0001[.underline]#10#" -> "0001[.underline]#01#" 
"[.underline]#00#0101" -> "[.underline]#10#0101" 
"1[.underline]#00#101" -> "1[.underline]#10#101" 
"110[.underline]#10#1" -> "110[.underline]#01#1" 
"11[.underline]#00#11" -> "11[.underline]#10#11"
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* binary = "01"
*Output:* "01"
*Explanation:* "01" cannot be transformed any further.
----

 
*Constraints:*


* `1 <= binary.length <= 10^5^`
* `binary` consist of `'0'` and `'1'`.




== 思路分析


[[src-1702]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1702_MaximumBinaryStringAfterChange.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1702_MaximumBinaryStringAfterChange_2.java[tag=answer]
// ----
// --
====


== 参考资料


