[#1707-maximum-xor-with-an-element-from-array]
= 1707. Maximum XOR With an Element From Array

{leetcode}/problems/maximum-xor-with-an-element-from-array/[LeetCode - 1707. Maximum XOR With an Element From Array ^]

You are given an array `nums` consisting of non-negative integers. You are also given a `queries` array, where `queries[i] = [x<sub>i</sub>, m<sub>i</sub>]`.

The answer to the `i^th^` query is the maximum bitwise `XOR` value of `x<sub>i</sub>` and any element of `nums` that does not exceed `m<sub>i</sub>`. In other words, the answer is `max(nums[j] XOR x<sub>i</sub>)` for all `j` such that `nums[j] <= m<sub>i</sub>`. If all elements in `nums` are larger than `m<sub>i</sub>`, then the answer is `-1`.

Return _an integer array _`answer`_ where _`answer.length == queries.length`_ and _`answer[i]`_ is the answer to the _`i^th^`_ query._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [0,1,2,3,4], queries = [[3,1],[1,3],[5,6]]
*Output:* [3,3,7]
*Explanation:*
1) 0 and 1 are the only two integers not greater than 1. 0 XOR 3 = 3 and 1 XOR 3 = 2. The larger of the two is 3.
2) 1 XOR 2 = 3.
3) 5 XOR 2 = 7.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [5,2,4,6,6,3], queries = [[12,4],[8,1],[6,3]]
*Output:* [15,-1,5]
----

 
*Constraints:*


* `1 <= nums.length, queries.length <= 10^5^`
* `queries[i].length == 2`
* `0 <= nums[j], x<sub>i</sub>, m<sub>i</sub> <= 10^9^`




== 思路分析


[[src-1707]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1707_MaximumXorWithAnElementFromArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1707_MaximumXorWithAnElementFromArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


