[#1712-ways-to-split-array-into-three-subarrays]
= 1712. Ways to Split Array Into Three Subarrays

{leetcode}/problems/ways-to-split-array-into-three-subarrays/[LeetCode - 1712. Ways to Split Array Into Three Subarrays ^]

A split of an integer array is *good* if:


* The array is split into three *non-empty* contiguous subarrays - named `left`, `mid`, `right` respectively from left to right.
* The sum of the elements in `left` is less than or equal to the sum of the elements in `mid`, and the sum of the elements in `mid` is less than or equal to the sum of the elements in `right`.


Given `nums`, an array of *non-negative* integers, return _the number of *good* ways to split_ `nums`. As the number may be too large, return it *modulo* `10^9 ^+ 7`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,1,1]
*Output:* 1
*Explanation:* The only good way to split nums is [1] [1] [1].
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,2,2,5,0]
*Output:* 3
*Explanation:* There are three good ways of splitting nums:
[1] [2] [2,2,5,0]
[1] [2,2] [2,5,0]
[1,2] [2,2] [5,0]

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [3,2,1]
*Output:* 0
*Explanation:* There is no good way to split nums.
----

 
*Constraints:*


* `3 <= nums.length <= 10^5^`
* `0 <= nums[i] <= 10^4^`




== 思路分析


[[src-1712]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1712_WaysToSplitArrayIntoThreeSubarrays.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1712_WaysToSplitArrayIntoThreeSubarrays_2.java[tag=answer]
// ----
// --
====


== 参考资料


