[#1713-minimum-operations-to-make-a-subsequence]
= 1713. Minimum Operations to Make a Subsequence

{leetcode}/problems/minimum-operations-to-make-a-subsequence/[LeetCode - 1713. Minimum Operations to Make a Subsequence ^]

You are given an array `target` that consists of *distinct* integers and another integer array `arr` that *can* have duplicates.

In one operation, you can insert any integer at any position in `arr`. For example, if `arr = [1,4,1,2]`, you can add `3` in the middle and make it `[1,4,[.underline]#3#,1,2]`. Note that you can insert the integer at the very beginning or end of the array.

Return _the *minimum* number of operations needed to make _`target`_ a *subsequence* of _`arr`_._

A *subsequence* of an array is a new array generated from the original array by deleting some elements (possibly none) without changing the remaining elements' relative order. For example, `[2,7,4]` is a subsequence of `[4,[.underline]#2#,3,[.underline]#7#,2,1,[.underline]#4#]` (the underlined elements), while `[2,4,2]` is not.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* target = [5,1,3], `arr` = [9,4,2,3,4]
*Output:* 2
*Explanation:* You can add 5 and 1 in such a way that makes `arr` = [[.underline]#5#,9,4,[.underline]#1#,2,3,4], then target will be a subsequence of `arr`.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* target = [6,4,8,1,3,2], `arr` = [4,7,6,2,3,8,6,1]
*Output:* 3
----

 
*Constraints:*


* `1 <= target.length, arr.length <= 10^5^`
* `1 <= target[i], arr[i] <= 10^9^`
* `target` contains no duplicates.




== 思路分析


[[src-1713]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1713_MinimumOperationsToMakeASubsequence.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1713_MinimumOperationsToMakeASubsequence_2.java[tag=answer]
// ----
// --
====


== 参考资料


