[#1725-number-of-rectangles-that-can-form-the-largest-square]
= 1725. Number Of Rectangles That Can Form The Largest Square

{leetcode}/problems/number-of-rectangles-that-can-form-the-largest-square/[LeetCode - 1725. Number Of Rectangles That Can Form The Largest Square ^]

You are given an array `rectangles` where `rectangles[i] = [l<sub>i</sub>, w<sub>i</sub>]` represents the `i^th^` rectangle of length `l<sub>i</sub>` and width `w<sub>i</sub>`.

You can cut the `i^th^` rectangle to form a square with a side length of `k` if both `k <= l<sub>i</sub>` and `k <= w<sub>i</sub>`. For example, if you have a rectangle `[4,6]`, you can cut it to get a square with a side length of at most `4`.

Let `maxLen` be the side length of the *largest* square you can obtain from any of the given rectangles.

Return _the *number* of rectangles that can make a square with a side length of _`maxLen`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* rectangles = [[5,8],[3,9],[5,12],[16,5]]
*Output:* 3
*Explanation:* The largest squares you can get from each rectangle are of lengths [5,3,5,5].
The largest possible square is of length 5, and you can get it out of 3 rectangles.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* rectangles = [[2,3],[3,7],[4,3],[3,7]]
*Output:* 3
----

 
*Constraints:*


* `1 <= rectangles.length <= 1000`
* `rectangles[i].length == 2`
* `1 <= l<sub>i</sub>, w<sub>i</sub> <= 10^9^`
* `l<sub>i</sub> != w<sub>i</sub>`



== 思路分析


[[src-1725]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1725_NumberOfRectanglesThatCanFormTheLargestSquare.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1725_NumberOfRectanglesThatCanFormTheLargestSquare_2.java[tag=answer]
// ----
// --
====


== 参考资料


