[#1733-minimum-number-of-people-to-teach]
= 1733. Minimum Number of People to Teach

https://leetcode.com/problems/minimum-number-of-people-to-teach/[LeetCode - 1733. Minimum Number of People to Teach ^]

On a social network consisting of `m` users and some friendships between users, two users can communicate with each other if they know a common language.

You are given an integer `n`, an array `languages`, and an array `friendships` where:


* There are `n` languages numbered `1` through `n`,
* `languages[i]` is the set of languages the `i^​​​​​​th^`​​​​ user knows, and
* `friendships[i] = [u<sub>​​​​​​i</sub>​​​, v<sub>​​​​​​i</sub>]` denotes a friendship between the users `u^​​​​​^<sub>​​​​​​i</sub>`​​​​​ and `v<sub>i</sub>`.


You can choose *one* language and teach it to some users so that all friends can communicate with each other. Return <i data-stringify-type="italic">the_ _*minimum* _<i data-stringify-type="italic">number of users you need to teach._
Note that friendships are not transitive, meaning if `x` is a friend of `y` and `y` is a friend of `z`, this doesn't guarantee that `x` is a friend of `z`.
 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 2, languages = [[1],[2],[1,2]], friendships = [[1,2],[1,3],[2,3]]
*Output:* 1
*Explanation:* You can either teach user 1 the second language or user 2 the first language.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, languages = [[2],[1,3],[1,2],[3]], friendships = [[1,4],[1,2],[3,4],[2,3]]
*Output:* 2
*Explanation:* Teach the third language to users 1 and 3, yielding two users to teach.
----

 
*Constraints:*


* `2 <= n <= 500`
* `languages.length == m`
* `1 <= m <= 500`
* `1 <= languages[i].length <= n`
* `1 <= languages[i][j] <= n`
* `1 <= u<sub>​​​​​​i</sub> < v<sub>​​​​​​i</sub> <= languages.length`
* `1 <= friendships.length <= 500`
* All tuples `(u<sub>​​​​​i, </sub>v<sub>​​​​​​i</sub>)` are unique
* `languages[i]` contains only unique values




== 思路分析


[[src-1733]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1733_MinimumNumberOfPeopleToTeach.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1733_MinimumNumberOfPeopleToTeach_2.java[tag=answer]
// ----
// --
====


== 参考资料


