[#1743-restore-the-array-from-adjacent-pairs]
= 1743. Restore the Array From Adjacent Pairs

{leetcode}/problems/restore-the-array-from-adjacent-pairs/[LeetCode - 1743. Restore the Array From Adjacent Pairs ^]

There is an integer array `nums` that consists of `n` *unique *elements, but you have forgotten it. However, you do remember every pair of adjacent elements in `nums`.

You are given a 2D integer array `adjacentPairs` of size `n - 1` where each `adjacentPairs[i] = [u<sub>i</sub>, v<sub>i</sub>]` indicates that the elements `u<sub>i</sub>` and `v<sub>i</sub>` are adjacent in `nums`.

It is guaranteed that every adjacent pair of elements `nums[i]` and `nums[i+1]` will exist in `adjacentPairs`, either as `[nums[i], nums[i+1]]` or `[nums[i+1], nums[i]]`. The pairs can appear *in any order*.

Return _the original array _`nums`_. If there are multiple solutions, return *any of them*_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* adjacentPairs = [[2,1],[3,4],[3,2]]
*Output:* [1,2,3,4]
*Explanation:* This array has all its adjacent pairs in adjacentPairs.
Notice that adjacentPairs[i] may not be in left-to-right order.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* adjacentPairs = [[4,-2],[1,4],[-3,1]]
*Output:* [-2,4,1,-3]
*Explanation:* There can be negative numbers.
Another solution is [-3,1,4,-2], which would also be accepted.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* adjacentPairs = [[100000,-100000]]
*Output:* [100000,-100000]
----

 
*Constraints:*


* `nums.length == n`
* `adjacentPairs.length == n - 1`
* `adjacentPairs[i].length == 2`
* `2 <= n <= 10^5^`
* `-10^5^ <= nums[i], u<sub>i</sub>, v<sub>i</sub> <= 10^5^`
* There exists some `nums` that has `adjacentPairs` as its pairs.




== 思路分析


[[src-1743]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1743_RestoreTheArrayFromAdjacentPairs.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1743_RestoreTheArrayFromAdjacentPairs_2.java[tag=answer]
// ----
// --
====


== 参考资料


