[#1750-minimum-length-of-string-after-deleting-similar-ends]
= 1750. Minimum Length of String After Deleting Similar Ends

{leetcode}/problems/minimum-length-of-string-after-deleting-similar-ends/[LeetCode - 1750. Minimum Length of String After Deleting Similar Ends ^]

Given a string `s` consisting only of characters `'a'`, `'b'`, and `'c'`. You are asked to apply the following algorithm on the string any number of times:


* Pick a *non-empty* prefix from the string `s` where all the characters in the prefix are equal.
* Pick a *non-empty* suffix from the string `s` where all the characters in this suffix are equal.
* The prefix and the suffix should not intersect at any index.
* The characters from the prefix and suffix must be the same.
* Delete both the prefix and the suffix.


Return _the *minimum length* of _`s` _after performing the above operation any number of times (possibly zero times)_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "ca"
*Output:* 2
*Explanation: *You can't remove any characters, so the string stays as is.

----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "cabaabac"
*Output:* 0
*Explanation:* An optimal sequence of operations is:
- Take prefix = "c" and suffix = "c" and remove them, s = "abaaba".
- Take prefix = "a" and suffix = "a" and remove them, s = "baab".
- Take prefix = "b" and suffix = "b" and remove them, s = "aa".
- Take prefix = "a" and suffix = "a" and remove them, s = "".
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "aabccabba"
*Output:* 3
*Explanation:* An optimal sequence of operations is:
- Take prefix = "aa" and suffix = "a" and remove them, s = "bccabb".
- Take prefix = "b" and suffix = "bb" and remove them, s = "cca".

----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` only consists of characters `'a'`, `'b'`, and `'c'`.




== 思路分析


[[src-1750]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1750_MinimumLengthOfStringAfterDeletingSimilarEnds.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1750_MinimumLengthOfStringAfterDeletingSimilarEnds_2.java[tag=answer]
// ----
// --
====


== 参考资料


