[#1760-minimum-limit-of-balls-in-a-bag]
= 1760. Minimum Limit of Balls in a Bag

https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/[LeetCode - 1760. Minimum Limit of Balls in a Bag ^]

You are given an integer array `nums` where the `i^th^` bag contains `nums[i]` balls. You are also given an integer `maxOperations`.

You can perform the following operation at most `maxOperations` times:


* Take any bag of balls and divide it into two new bags with a *positive *number of balls.

	
	* For example, a bag of `5` balls can become two new bags of `1` and `4` balls, or two new bags of `2` and `3` balls.
	
	


Your penalty is the *maximum* number of balls in a bag. You want to *minimize* your penalty after the operations.

Return _the minimum possible penalty after performing the operations_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [9], maxOperations = 2
*Output:* 3
*Explanation:* 
- Divide the bag with 9 balls into two bags of sizes 6 and 3. [*[.underline]#9#*] -> [6,3].
- Divide the bag with 6 balls into two bags of sizes 3 and 3. [*[.underline]#6#*,3] -> [3,3,3].
The bag with the most number of balls has 3 balls, so your penalty is 3 and you should return 3.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,4,8,2], maxOperations = 4
*Output:* 2
*Explanation:*
- Divide the bag with 8 balls into two bags of sizes 4 and 4. [2,4,*[.underline]#8#*,2] -> [2,4,4,4,2].
- Divide the bag with 4 balls into two bags of sizes 2 and 2. [2,*[.underline]#4#*,4,4,2] -> [2,2,2,4,4,2].
- Divide the bag with 4 balls into two bags of sizes 2 and 2. [2,2,2,*[.underline]#4#*,4,2] -> [2,2,2,2,2,4,2].
- Divide the bag with 4 balls into two bags of sizes 2 and 2. [2,2,2,2,2,*[.underline]#4#*,2] -> [2,2,2,2,2,2,2,2].
The bag with the most number of balls has 2 balls, so your penalty is 2, and you should return 2.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= maxOperations, nums[i] <= 10^9^`




== 思路分析


[[src-1760]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1760_MinimumLimitOfBallsInABag.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1760_MinimumLimitOfBallsInABag_2.java[tag=answer]
// ----
// --
====


== 参考资料


