[#1770-maximum-score-from-performing-multiplication-operations]
= 1770. Maximum Score from Performing Multiplication Operations

https://leetcode.com/problems/maximum-score-from-performing-multiplication-operations/[LeetCode - 1770. Maximum Score from Performing Multiplication Operations ^]

You are given two *0-indexed* integer arrays `nums` and `multipliers`* *of size `n` and `m` respectively, where `n >= m`.

You begin with a score of `0`. You want to perform *exactly* `m` operations. On the `i^th^` operation (*0-indexed*) you will:


    <li>Choose one integer `x` from *either the start or the end *of the array `nums`.
    <li>Add `multipliers[i] * x` to your score.
    
        <li>Note that `multipliers[0]` corresponds to the first operation, `multipliers[1]` to the second operation, and so on.
    
    
    <li>Remove `x` from `nums`.


Return _the *maximum* score after performing _`m` _operations._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3], multipliers = [3,2,1]
*Output:* 14
*Explanation:* An optimal solution is as follows:
- Choose from the end, [1,2,*[.underline]#3#*], adding 3 * 3 = 9 to the score.
- Choose from the end, [1,*[.underline]#2#*], adding 2 * 2 = 4 to the score.
- Choose from the end, [*[.underline]#1#*], adding 1 * 1 = 1 to the score.
The total score is 9 + 4 + 1 = 14.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [-5,-3,-3,-2,7,1], multipliers = [-10,-5,3,4,6]
*Output:* 102
*Explanation: *An optimal solution is as follows:
- Choose from the start, [[.underline]#*-5*#,-3,-3,-2,7,1], adding -5 * -10 = 50 to the score.
- Choose from the start, [*[.underline]#-3#*,-3,-2,7,1], adding -3 * -5 = 15 to the score.
- Choose from the start, [*[.underline]#-3#*,-2,7,1], adding -3 * 3 = -9 to the score.
- Choose from the end, [-2,7,*[.underline]#1#*], adding 1 * 4 = 4 to the score.
- Choose from the end, [-2,*[.underline]#7#*], adding 7 * 6 = 42 to the score. 
The total score is 50 + 15 - 9 + 4 + 42 = 102.

----

 
*Constraints:*


* `n == nums.length`
* `m == multipliers.length`
* `1 <= m <= 300`
* `m <= n <= 10^5^`` `
* `-1000 <= nums[i], multipliers[i] <= 1000`




== 思路分析


[[src-1770]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1770_MaximumScoreFromPerformingMultiplicationOperations.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1770_MaximumScoreFromPerformingMultiplicationOperations_2.java[tag=answer]
// ----
// --
====


== 参考资料


