[#1773-count-items-matching-a-rule]
= 1773. Count Items Matching a Rule

https://leetcode.com/problems/count-items-matching-a-rule/[LeetCode - 1773. Count Items Matching a Rule ^]

You are given an array `items`, where each `items[i] = [type<sub>i</sub>, color<sub>i</sub>, name<sub>i</sub>]` describes the type, color, and name of the `i^th^` item. You are also given a rule represented by two strings, `ruleKey` and `ruleValue`.

The `i^th^` item is said to match the rule if *one* of the following is true:


* `ruleKey == "type"` and `ruleValue == type<sub>i</sub>`.
* `ruleKey == "color"` and `ruleValue == color<sub>i</sub>`.
* `ruleKey == "name"` and `ruleValue == name<sub>i</sub>`.


Return _the number of items that match the given rule_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* items = [["phone","blue","pixel"],["computer","silver","lenovo"],["phone","gold","iphone"]], ruleKey = "color", ruleValue = "silver"
*Output:* 1
*Explanation:* There is only one item matching the given rule, which is ["computer","silver","lenovo"].

----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* items = [["phone","blue","pixel"],["computer","silver","phone"],["phone","gold","iphone"]], ruleKey = "type", ruleValue = "phone"
*Output:* 2
*Explanation:* There are only two items matching the given rule, which are ["phone","blue","pixel"] and ["phone","gold","iphone"]. Note that the item ["computer","silver","phone"] does not match.
----

 
*Constraints:*


* `1 <= items.length <= 10^4^`
* `1 <= type<sub>i</sub>.length, color<sub>i</sub>.length, name<sub>i</sub>.length, ruleValue.length <= 10`
* `ruleKey` is equal to either `"type"`, `"color"`, or `"name"`.
* All strings consist only of lowercase letters.




== 思路分析


[[src-1773]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1773_CountItemsMatchingARule.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1773_CountItemsMatchingARule_2.java[tag=answer]
// ----
// --
====


== 参考资料


