[#1779-find-nearest-point-that-has-the-same-x-or-y-coordinate]
= 1779. Find Nearest Point That Has the Same X or Y Coordinate

{leetcode}/problems/find-nearest-point-that-has-the-same-x-or-y-coordinate/[LeetCode - 1779. Find Nearest Point That Has the Same X or Y Coordinate ^]

You are given two integers, `x` and `y`, which represent your current location on a Cartesian grid: `(x, y)`. You are also given an array `points` where each `points[i] = [a<sub>i</sub>, b<sub>i</sub>]` represents that a point exists at `(a<sub>i</sub>, b<sub>i</sub>)`. A point is *valid* if it shares the same x-coordinate or the same y-coordinate as your location.

Return _the index *(0-indexed)* of the *valid* point with the smallest *Manhattan distance* from your current location_. If there are multiple, return _the valid point with the *smallest* index_. If there are no valid points, return `-1`.

The *Manhattan distance* between two points `(x<sub>1</sub>, y<sub>1</sub>)` and `(x<sub>2</sub>, y<sub>2</sub>)` is `abs(x<sub>1</sub> - x<sub>2</sub>) + abs(y<sub>1</sub> - y<sub>2</sub>)`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* x = 3, y = 4, points = [[1,2],[3,1],[2,4],[2,3],[4,4]]
*Output:* 2
*Explanation:* Of all the points, only [3,1], [2,4] and [4,4] are valid. Of the valid points, [2,4] and [4,4] have the smallest Manhattan distance from your current location, with a distance of 1. [2,4] has the smallest index, so return 2.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* x = 3, y = 4, points = [[3,4]]
*Output:* 0
*Explanation:* The answer is allowed to be on the same location as your current location.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* x = 3, y = 4, points = [[2,3]]
*Output:* -1
*Explanation:* There are no valid points.
----

 
*Constraints:*


* `1 <= points.length <= 10^4^`
* `points[i].length == 2`
* `1 <= x, y, a<sub>i</sub>, b<sub>i</sub> <= 10^4^`




== 思路分析


[[src-1779]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1779_FindNearestPointThatHasTheSameXOrYCoordinate.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1779_FindNearestPointThatHasTheSameXOrYCoordinate_2.java[tag=answer]
// ----
// --
====


== 参考资料


