[#1790-check-if-one-string-swap-can-make-strings-equal]
= 1790. Check if One String Swap Can Make Strings Equal

{leetcode}/problems/check-if-one-string-swap-can-make-strings-equal/[LeetCode - 1790. Check if One String Swap Can Make Strings Equal ^]

You are given two strings `s1` and `s2` of equal length. A *string swap* is an operation where you choose two indices in a string (not necessarily different) and swap the characters at these indices.

Return `true` _if it is possible to make both strings equal by performing *at most one string swap *on *exactly one* of the strings. _Otherwise, return `false`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "bank", s2 = "kanb"
*Output:* true
*Explanation:* For example, swap the first character with the last character of s2 to make "bank".
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "attack", s2 = "defend"
*Output:* false
*Explanation:* It is impossible to make them equal with one string swap.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "kelb", s2 = "kelb"
*Output:* true
*Explanation:* The two strings are already equal, so no string swap operation is required.
----

 
*Constraints:*


* `1 <= s1.length, s2.length <= 100`
* `s1.length == s2.length`
* `s1` and `s2` consist of only lowercase English letters.




== 思路分析


[[src-1790]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1790_CheckIfOneStringSwapCanMakeStringsEqual.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1790_CheckIfOneStringSwapCanMakeStringsEqual_2.java[tag=answer]
// ----
// --
====


== 参考资料


