[#1798-maximum-number-of-consecutive-values-you-can-make]
= 1798. Maximum Number of Consecutive Values You Can Make

{leetcode}/problems/maximum-number-of-consecutive-values-you-can-make/[LeetCode - 1798. Maximum Number of Consecutive Values You Can Make ^]

You are given an integer array `coins` of length `n` which represents the `n` coins that you own. The value of the `i^th^` coin is `coins[i]`. You can *make* some value `x` if you can choose some of your `n` coins such that their values sum up to `x`.

Return the _maximum number of consecutive integer values that you *can* *make* with your coins *starting* from and *including* _`0`.

Note that you may have multiple coins of the same value.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* coins = [1,3]
*Output:* 2
*Explanation: *You can make the following values:
- 0: take []
- 1: take [1]
You can make 2 consecutive integer values starting from 0.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* coins = [1,1,1,4]
*Output:* 8
*Explanation: *You can make the following values:
- 0: take []
- 1: take [1]
- 2: take [1,1]
- 3: take [1,1,1]
- 4: take [4]
- 5: take [4,1]
- 6: take [4,1,1]
- 7: take [4,1,1,1]
You can make 8 consecutive integer values starting from 0.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,4,10,3,1]
*Output:* 20
----

 
*Constraints:*


* `coins.length == n`
* `1 <= n <= 4 * 10^4^`
* `1 <= coins[i] <= 4 * 10^4^`




== 思路分析


[[src-1798]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1798_MaximumNumberOfConsecutiveValuesYouCanMake.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1798_MaximumNumberOfConsecutiveValuesYouCanMake_2.java[tag=answer]
// ----
// --
====


== 参考资料


