[#1807-evaluate-the-bracket-pairs-of-a-string]
= 1807. Evaluate the Bracket Pairs of a String

{leetcode}/problems/evaluate-the-bracket-pairs-of-a-string/[LeetCode - 1807. Evaluate the Bracket Pairs of a String ^]

You are given a string `s` that contains some bracket pairs, with each pair containing a *non-empty* key.


* For example, in the string `"(name)is(age)yearsold"`, there are *two* bracket pairs that contain the keys `"name"` and `"age"`.


You know the values of a wide range of keys. This is represented by a 2D string array `knowledge` where each `knowledge[i] = [key<sub>i</sub>, value<sub>i</sub>]` indicates that key `key<sub>i</sub>` has a value of `value<sub>i</sub>`.

You are tasked to evaluate *all* of the bracket pairs. When you evaluate a bracket pair that contains some key `key<sub>i</sub>`, you will:


* Replace `key<sub>i</sub>` and the bracket pair with the key's corresponding `value<sub>i</sub>`.
* If you do not know the value of the key, you will replace `key<sub>i</sub>` and the bracket pair with a question mark `"?"` (without the quotation marks).


Each key will appear at most once in your `knowledge`. There will not be any nested brackets in `s`.

Return _the resulting string after evaluating *all* of the bracket pairs._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "(name)is(age)yearsold", knowledge = [["name","bob"],["age","two"]]
*Output:* "bobistwoyearsold"
*Explanation:*
The key "name" has a value of "bob", so replace "(name)" with "bob".
The key "age" has a value of "two", so replace "(age)" with "two".
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "hi(name)", knowledge = [["a","b"]]
*Output:* "hi?"
*Explanation:* As you do not know the value of the key "name", replace "(name)" with "?".
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "(a)(a)(a)aaa", knowledge = [["a","yes"]]
*Output:* "yesyesyesaaa"
*Explanation:* The same key can appear multiple times.
The key "a" has a value of "yes", so replace all occurrences of "(a)" with "yes".
Notice that the "a"s not in a bracket pair are not evaluated.
----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `0 <= knowledge.length <= 10^5^`
* `knowledge[i].length == 2`
* `1 <= key<sub>i</sub>.length, value<sub>i</sub>.length <= 10`
* `s` consists of lowercase English letters and round brackets `'('` and `')'`.
* Every open bracket `'('` in `s` will have a corresponding close bracket `')'`.
* The key in each bracket pair of `s` will be non-empty.
* There will not be any nested bracket pairs in `s`.
* `key<sub>i</sub>` and `value<sub>i</sub>` consist of lowercase English letters.
* Each `key<sub>i</sub>` in `knowledge` is unique.




== 思路分析


[[src-1807]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1807_EvaluateTheBracketPairsOfAString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1807_EvaluateTheBracketPairsOfAString_2.java[tag=answer]
// ----
// --
====


== 参考资料


