[#1808-maximize-number-of-nice-divisors]
= 1808. Maximize Number of Nice Divisors

{leetcode}/problems/maximize-number-of-nice-divisors/[LeetCode - 1808. Maximize Number of Nice Divisors ^]

You are given a positive integer `primeFactors`. You are asked to construct a positive integer `n` that satisfies the following conditions:


  <li>The number of prime factors of `n` (not necessarily distinct) is *at most* `primeFactors`.
  <li>The number of nice divisors of `n` is maximized. Note that a divisor of `n` is *nice* if it is divisible by every prime factor of `n`. For example, if `n = 12`, then its prime factors are `[2,2,3]`, then `6` and `12` are nice divisors, while `3` and `4` are not.


Return _the number of nice divisors of_ `n`. Since that number can be too large, return it *modulo* `10^9^ + 7`.

Note that a prime number is a natural number greater than `1` that is not a product of two smaller natural numbers. The prime factors of a number `n` is a list of prime numbers such that their product equals `n`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* primeFactors = 5
*Output:* 6
*Explanation:* 200 is a valid value of n.
It has 5 prime factors: [2,2,2,5,5], and it has 6 nice divisors: [10,20,40,50,100,200].
There is not other value of n that has at most 5 prime factors and more nice divisors.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* primeFactors = 8
*Output:* 18
----

 
*Constraints:*


* `1 <= primeFactors <= 10^9^`



== 思路分析


[[src-1808]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1808_MaximizeNumberOfNiceDivisors.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1808_MaximizeNumberOfNiceDivisors_2.java[tag=answer]
// ----
// --
====


== 参考资料


