[#1816-truncate-sentence]
= 1816. Truncate Sentence

https://leetcode.com/problems/truncate-sentence/[LeetCode - 1816. Truncate Sentence ^]

A *sentence* is a list of words that are separated by a single space with no leading or trailing spaces. Each of the words consists of *only* uppercase and lowercase English letters (no punctuation).


* For example, `"Hello World"`, `"HELLO"`, and `"hello world hello world"` are all sentences.


You are given a sentence `s`​​​​​​ and an integer `k`​​​​​​. You want to *truncate* `s`​​​​​​ such that it contains only the *first* `k`​​​​​​ words. Return `s`​​​​_​​ after *truncating* it._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "Hello how are you Contestant", k = 4
*Output:* "Hello how are you"
*Explanation:*
The words in s are ["Hello", "how" "are", "you", "Contestant"].
The first 4 words are ["Hello", "how", "are", "you"].
Hence, you should return "Hello how are you".

----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "What is the solution to this problem", k = 4
*Output:* "What is the solution"
*Explanation:*
The words in s are ["What", "is" "the", "solution", "to", "this", "problem"].
The first 4 words are ["What", "is", "the", "solution"].
Hence, you should return "What is the solution".
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "chopper is not a tanuki", k = 5
*Output:* "chopper is not a tanuki"

----

 
*Constraints:*


* `1 <= s.length <= 500`
* `k` is in the range `[1, the number of words in s]`.
* `s` consist of only lowercase and uppercase English letters and spaces.
* The words in `s` are separated by a single space.
* There are no leading or trailing spaces.




== 思路分析


[[src-1816]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1816_TruncateSentence.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1816_TruncateSentence_2.java[tag=answer]
// ----
// --
====


== 参考资料


