[#1844-replace-all-digits-with-characters]
= 1844. Replace All Digits with Characters

{leetcode}/problems/replace-all-digits-with-characters/[LeetCode - 1844. Replace All Digits with Characters ^]

You are given a *0-indexed* string `s` that has lowercase English letters in its *even* indices and digits in its *odd* indices.

There is a function `shift(c, x)`, where `c` is a character and `x` is a digit, that returns the `x^th^` character after `c`.


* For example, `shift('a', 5) = 'f'` and `shift('x', 0) = 'x'`.


For every *odd* index `i`, you want to replace the digit `s[i]` with `shift(s[i-1], s[i])`.

Return `s`_ after replacing all digits. It is *guaranteed* that _`shift(s[i-1], s[i])`_ will never exceed _`'z'`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "a1c1e1"
*Output:* "abcdef"
*Explanation: *The digits are replaced as follows:
- s[1] -> shift('a',1) = 'b'
- s[3] -> shift('c',1) = 'd'
- s[5] -> shift('e',1) = 'f'----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "a1b2c3d4e"
*Output:* "abbdcfdhe"
*Explanation: *The digits are replaced as follows:
- s[1] -> shift('a',1) = 'b'
- s[3] -> shift('b',2) = 'd'
- s[5] -> shift('c',3) = 'f'
- s[7] -> shift('d',4) = 'h'----

 
*Constraints:*


* `1 <= s.length <= 100`
* `s` consists only of lowercase English letters and digits.
* `shift(s[i-1], s[i]) <= 'z'` for all *odd* indices `i`.




== 思路分析


[[src-1844]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1844_ReplaceAllDigitsWithCharacters.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1844_ReplaceAllDigitsWithCharacters_2.java[tag=answer]
// ----
// --
====


== 参考资料


