[#1856-maximum-subarray-min-product]
= 1856. Maximum Subarray Min-Product

{leetcode}/problems/maximum-subarray-min-product/[LeetCode - 1856. Maximum Subarray Min-Product ^]

The *min-product* of an array is equal to the *minimum value* in the array *multiplied by* the array's *sum*.


* For example, the array `[3,2,5]` (minimum value is `2`) has a min-product of `2 * (3+2+5) = 2 * 10 = 20`.


Given an array of integers `nums`, return _the *maximum min-product* of any *non-empty subarray* of _`nums`. Since the answer may be large, return it *modulo* `10^9^ + 7`.

Note that the min-product should be maximized *before* performing the modulo operation. Testcases are generated such that the maximum min-product *without* modulo will fit in a *64-bit signed integer*.

A *subarray* is a *contiguous* part of an array.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,[.underline]#2,3,2#]
*Output:* 14
*Explanation:* The maximum min-product is achieved with the subarray [2,3,2] (minimum value is 2).
2 * (2+3+2) = 2 * 7 = 14.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,[.underline]#3,3#,1,2]
*Output:* 18
*Explanation:* The maximum min-product is achieved with the subarray [3,3] (minimum value is 3).
3 * (3+3) = 3 * 6 = 18.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [3,1,[.underline]#5,6,4#,2]
*Output:* 60
*Explanation:* The maximum min-product is achieved with the subarray [5,6,4] (minimum value is 4).
4 * (5+6+4) = 4 * 15 = 60.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^7^`




== 思路分析


[[src-1856]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1856_MaximumSubarrayMinProduct.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1856_MaximumSubarrayMinProduct_2.java[tag=answer]
// ----
// --
====


== 参考资料


