[#1859-sorting-the-sentence]
= 1859. Sorting the Sentence

{leetcode}/problems/sorting-the-sentence/[LeetCode - 1859. Sorting the Sentence ^]

A *sentence* is a list of words that are separated by a single space with no leading or trailing spaces. Each word consists of lowercase and uppercase English letters.

A sentence can be *shuffled* by appending the *1-indexed word position* to each word then rearranging the words in the sentence.


* For example, the sentence `"This is a sentence"` can be shuffled as `"sentence4 a3 is2 This1"` or `"is2 sentence4 This1 a3"`.


Given a *shuffled sentence* `s` containing no more than `9` words, reconstruct and return _the original sentence_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "is2 sentence4 This1 a3"
*Output:* "This is a sentence"
*Explanation:* Sort the words in s to their original positions "This1 is2 a3 sentence4", then remove the numbers.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "Myself2 Me1 I4 and3"
*Output:* "Me Myself and I"
*Explanation:* Sort the words in s to their original positions "Me1 Myself2 and3 I4", then remove the numbers.
----

 
*Constraints:*


* `2 <= s.length <= 200`
* `s` consists of lowercase and uppercase English letters, spaces, and digits from `1` to `9`.
* The number of words in `s` is between `1` and `9`.
* The words in `s` are separated by a single space.
* `s` contains no leading or trailing spaces.



== 思路分析


[[src-1859]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1859_SortingTheSentence.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1859_SortingTheSentence_2.java[tag=answer]
// ----
// --
====


== 参考资料


