[#1860-incremental-memory-leak]
= 1860. Incremental Memory Leak

{leetcode}/problems/incremental-memory-leak/[LeetCode - 1860. Incremental Memory Leak ^]

You are given two integers `memory1` and `memory2` representing the available memory in bits on two memory sticks. There is currently a faulty program running that consumes an increasing amount of memory every second.

At the `i^th^` second (starting from 1), `i` bits of memory are allocated to the stick with *more available memory* (or from the first memory stick if both have the same available memory). If neither stick has at least `i` bits of available memory, the program *crashes*.

Return _an array containing _`[crashTime, memory1<sub>crash</sub>, memory2<sub>crash</sub>]`_, where _`crashTime`_ is the time (in seconds) when the program crashed and _`memory1<sub>crash</sub>`_ and _`memory2<sub>crash</sub>`_ are the available bits of memory in the first and second sticks respectively_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* memory1 = 2, memory2 = 2
*Output:* [3,1,0]
*Explanation:* The memory is allocated as follows:
- At the 1^st^ second, 1 bit of memory is allocated to stick 1. The first stick now has 1 bit of available memory.
- At the 2^nd^ second, 2 bits of memory are allocated to stick 2. The second stick now has 0 bits of available memory.
- At the 3^rd^ second, the program crashes. The sticks have 1 and 0 bits available respectively.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* memory1 = 8, memory2 = 11
*Output:* [6,0,4]
*Explanation:* The memory is allocated as follows:
- At the 1^st^ second, 1 bit of memory is allocated to stick 2. The second stick now has 10 bit of available memory.
- At the 2^nd^ second, 2 bits of memory are allocated to stick 2. The second stick now has 8 bits of available memory.
- At the 3^rd^ second, 3 bits of memory are allocated to stick 1. The first stick now has 5 bits of available memory.
- At the 4^th^ second, 4 bits of memory are allocated to stick 2. The second stick now has 4 bits of available memory.
- At the 5^th^ second, 5 bits of memory are allocated to stick 1. The first stick now has 0 bits of available memory.
- At the 6^th^ second, the program crashes. The sticks have 0 and 4 bits available respectively.
----

 
*Constraints:*


* `0 <= memory1, memory2 <= 2^31^ - 1`




== 思路分析


[[src-1860]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1860_IncrementalMemoryLeak.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1860_IncrementalMemoryLeak_2.java[tag=answer]
// ----
// --
====


== 参考资料


