[#1866-number-of-ways-to-rearrange-sticks-with-k-sticks-visible]
= 1866. Number of Ways to Rearrange Sticks With K Sticks Visible

https://leetcode.com/problems/number-of-ways-to-rearrange-sticks-with-k-sticks-visible/[LeetCode - 1866. Number of Ways to Rearrange Sticks With K Sticks Visible ^]

There are `n` uniquely-sized sticks whose lengths are integers from `1` to `n`. You want to arrange the sticks such that *exactly* `k` sticks are *visible* from the left. A stick is *visible* from the left if there are no *longer* sticks to the *left* of it.


* For example, if the sticks are arranged `[[.underline]#1#,[.underline]#3#,2,[.underline]#5#,4]`, then the sticks with lengths `1`, `3`, and `5` are visible from the left.


Given `n` and `k`, return _the *number* of such arrangements_. Since the answer may be large, return it *modulo* `10^9^ + 7`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, k = 2
*Output:* 3
*Explanation:* [[.underline]#1#,[.underline]#3#,2], [[.underline]#2#,[.underline]#3#,1], and [[.underline]#2#,1,[.underline]#3#] are the only arrangements such that exactly 2 sticks are visible.
The visible sticks are underlined.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 5, k = 5
*Output:* 1
*Explanation:* [[.underline]#1#,[.underline]#2#,[.underline]#3#,[.underline]#4#,[.underline]#5#] is the only arrangement such that all 5 sticks are visible.
The visible sticks are underlined.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = 20, k = 11
*Output:* 647427950
*Explanation:* There are 647427950 (mod 10^9 ^+ 7) ways to rearrange the sticks such that exactly 11 sticks are visible.
----

 
*Constraints:*


* `1 <= n <= 1000`
* `1 <= k <= n`




== 思路分析


[[src-1866]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1866_NumberOfWaysToRearrangeSticksWithKSticksVisible.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1866_NumberOfWaysToRearrangeSticksWithKSticksVisible_2.java[tag=answer]
// ----
// --
====


== 参考资料


