[#1880-check-if-word-equals-summation-of-two-words]
= 1880. Check if Word Equals Summation of Two Words

{leetcode}/problems/check-if-word-equals-summation-of-two-words/[LeetCode - 1880. Check if Word Equals Summation of Two Words ^]

The *letter value* of a letter is its position in the alphabet *starting from 0* (i.e. `'a' -> 0`, `'b' -> 1`, `'c' -> 2`, etc.).

The *numerical value* of some string of lowercase English letters `s` is the *concatenation* of the *letter values* of each letter in `s`, which is then *converted* into an integer.


* For example, if `s = "acb"`, we concatenate each letter's letter value, resulting in `"021"`. After converting it, we get `21`.


You are given three strings `firstWord`, `secondWord`, and `targetWord`, each consisting of lowercase English letters `'a'` through `'j'` *inclusive*.

Return `true` _if the *summation* of the *numerical values* of _`firstWord`_ and _`secondWord`_ equals the *numerical value* of _`targetWord`_, or _`false`_ otherwise._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* firstWord = "acb", secondWord = "cba", targetWord = "cdb"
*Output:* true
*Explanation:*
The numerical value of firstWord is "acb" -> "021" -> 21.
The numerical value of secondWord is "cba" -> "210" -> 210.
The numerical value of targetWord is "cdb" -> "231" -> 231.
We return true because 21 + 210 == 231.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* firstWord = "aaa", secondWord = "a", targetWord = "aab"
*Output:* false
*Explanation:* 
The numerical value of firstWord is "aaa" -> "000" -> 0.
The numerical value of secondWord is "a" -> "0" -> 0.
The numerical value of targetWord is "aab" -> "001" -> 1.
We return false because 0 + 0 != 1.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* firstWord = "aaa", secondWord = "a", targetWord = "aaaa"
*Output:* true
*Explanation:* 
The numerical value of firstWord is "aaa" -> "000" -> 0.
The numerical value of secondWord is "a" -> "0" -> 0.
The numerical value of targetWord is "aaaa" -> "0000" -> 0.
We return true because 0 + 0 == 0.
----

 
*Constraints:*


* `1 <= firstWord.length, ``secondWord.length, ``targetWord.length <= 8`
* `firstWord`, `secondWord`, and `targetWord` consist of lowercase English letters from `'a'` to `'j'` *inclusive*.




== 思路分析


[[src-1880]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1880_CheckIfWordEqualsSummationOfTwoWords.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1880_CheckIfWordEqualsSummationOfTwoWords_2.java[tag=answer]
// ----
// --
====


== 参考资料


