[#1888-minimum-number-of-flips-to-make-the-binary-string-alternating]
= 1888. Minimum Number of Flips to Make the Binary String Alternating

{leetcode}/problems/minimum-number-of-flips-to-make-the-binary-string-alternating/[LeetCode - 1888. Minimum Number of Flips to Make the Binary String Alternating ^]

You are given a binary string `s`. You are allowed to perform two types of operations on the string in any sequence:


* *Type-1: Remove* the character at the start of the string `s` and *append* it to the end of the string.
* *Type-2: Pick* any character in `s` and *flip* its value, i.e., if its value is `'0'` it becomes `'1'` and vice-versa.


Return _the *minimum* number of *type-2* operations you need to perform_ _such that _`s` _becomes *alternating*._

The string is called *alternating* if no two adjacent characters are equal.


* For example, the strings `"010"` and `"1010"` are alternating, while the string `"0100"` is not.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "111000"
*Output:* 2
*Explanation*: Use the first operation two times to make s = "100011".
Then, use the second operation on the third and sixth elements to make s = "10[.underline]#1#01[.underline]#0#".
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "010"
*Output:* 0
*Explanation*: The string is already alternating.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "1110"
*Output:* 1
*Explanation*: Use the second operation on the second element to make s = "1[.underline]#0#10".
----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s[i]` is either `'0'` or `'1'`.




== 思路分析


[[src-1888]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1888_MinimumNumberOfFlipsToMakeTheBinaryStringAlternating.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1888_MinimumNumberOfFlipsToMakeTheBinaryStringAlternating_2.java[tag=answer]
// ----
// --
====


== 参考资料


