[#1911-maximum-alternating-subsequence-sum]
= 1911. Maximum Alternating Subsequence Sum

{leetcode}/problems/maximum-alternating-subsequence-sum/[LeetCode - 1911. Maximum Alternating Subsequence Sum ^]

The *alternating sum* of a *0-indexed* array is defined as the *sum* of the elements at *even* indices *minus* the *sum* of the elements at *odd* indices.


* For example, the alternating sum of `[4,2,5,3]` is `(4 + 5) - (2 + 3) = 4`.


Given an array `nums`, return _the *maximum alternating sum* of any subsequence of _`nums`_ (after *reindexing* the elements of the subsequence)_.




A *subsequence* of an array is a new array generated from the original array by deleting some elements (possibly none) without changing the remaining elements' relative order. For example, `[2,7,4]` is a subsequence of `[4,[.underline]#2#,3,[.underline]#7#,2,1,[.underline]#4#]` (the underlined elements), while `[2,4,2]` is not.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [[.underline]#4#,[.underline]#2#,[.underline]#5#,3]
*Output:* 7
*Explanation:* It is optimal to choose the subsequence [4,2,5] with alternating sum (4 + 5) - 2 = 7.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [5,6,7,[.underline]#8#]
*Output:* 8
*Explanation:* It is optimal to choose the subsequence [8] with alternating sum 8.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [[.underline]#6#,2,[.underline]#1#,2,4,[.underline]#5#]
*Output:* 10
*Explanation:* It is optimal to choose the subsequence [6,1,5] with alternating sum (6 + 5) - 1 = 10.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^5^`



== 思路分析


[[src-1911]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1911_MaximumAlternatingSubsequenceSum.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1911_MaximumAlternatingSubsequenceSum_2.java[tag=answer]
// ----
// --
====


== 参考资料


