[#1923-longest-common-subpath]
= 1923. Longest Common Subpath

https://leetcode.com/problems/longest-common-subpath/[LeetCode - 1923. Longest Common Subpath ^]

There is a country of `n` cities numbered from `0` to `n - 1`. In this country, there is a road connecting *every pair* of cities.

There are `m` friends numbered from `0` to `m - 1` who are traveling through the country. Each one of them will take a path consisting of some cities. Each path is represented by an integer array that contains the visited cities in order. The path may contain a city *more than once*, but the same city will not be listed consecutively.

Given an integer `n` and a 2D integer array `paths` where `paths[i]` is an integer array representing the path of the `i^th^` friend, return _the length of the *longest common subpath* that is shared by *every* friend's path, or _`0`_ if there is no common subpath at all_.

A *subpath* of a path is a contiguous sequence of cities within that path.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 5, paths = [[0,1,[.underline]#2,3#,4],
                       [[.underline]#2,3#,4],
                       [4,0,1,[.underline]#2,3#]]
*Output:* 2
*Explanation:* The longest common subpath is [2,3].

----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, paths = [[0],[1],[2]]
*Output:* 0
*Explanation:* There is no common subpath shared by the three paths.

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = 5, paths = [[[.underline]#0#,1,2,3,4],
                       [4,3,2,1,[.underline]#0#]]
*Output:* 1
*Explanation:* The possible longest common subpaths are [0], [1], [2], [3], and [4]. All have a length of 1.
----

 
*Constraints:*


* `1 <= n <= 10^5^`
* `m == paths.length`
* `2 <= m <= 10^5^`
* `sum(paths[i].length) <= 10^5^`
* `0 <= paths[i][j] < n`
* The same city is not listed multiple times consecutively in `paths[i]`.




== 思路分析


[[src-1923]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1923_LongestCommonSubpath.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1923_LongestCommonSubpath_2.java[tag=answer]
// ----
// --
====


== 参考资料


