[#1930-unique-length-3-palindromic-subsequences]
= 1930. Unique Length-3 Palindromic Subsequences

{leetcode}/problems/unique-length-3-palindromic-subsequences/[LeetCode - 1930. Unique Length-3 Palindromic Subsequences ^]

Given a string `s`, return _the number of *unique palindromes of length three* that are a *subsequence* of _`s`.

Note that even if there are multiple ways to obtain the same subsequence, it is still only counted *once*.

A *palindrome* is a string that reads the same forwards and backwards.

A *subsequence* of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.


* For example, `"ace"` is a subsequence of `"[.underline]#a#b[.underline]#c#d[.underline]#e#"`.


 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "aabca"
*Output:* 3
*Explanation:* The 3 palindromic subsequences of length 3 are:
- "aba" (subsequence of "[.underline]#a#a[.underline]#b#c[.underline]#a#")
- "aaa" (subsequence of "[.underline]#aa#bc[.underline]#a#")
- "aca" (subsequence of "[.underline]#a#ab[.underline]#ca#")
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "adc"
*Output:* 0
*Explanation:* There are no palindromic subsequences of length 3 in "adc".
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "bbcbaba"
*Output:* 4
*Explanation:* The 4 palindromic subsequences of length 3 are:
- "bbb" (subsequence of "[.underline]#bb#c[.underline]#b#aba")
- "bcb" (subsequence of "[.underline]#b#b[.underline]#cb#aba")
- "bab" (subsequence of "[.underline]#b#bcb[.underline]#ab#a")
- "aba" (subsequence of "bbcb[.underline]#aba#")
----

 
*Constraints:*


* `3 <= s.length <= 10^5^`
* `s` consists of only lowercase English letters.




== 思路分析


[[src-1930]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1930_UniqueLength3PalindromicSubsequences.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1930_UniqueLength3PalindromicSubsequences_2.java[tag=answer]
// ----
// --
====


== 参考资料


