[#1935-maximum-number-of-words-you-can-type]
= 1935. Maximum Number of Words You Can Type

https://leetcode.com/problems/maximum-number-of-words-you-can-type/[LeetCode - 1935. Maximum Number of Words You Can Type ^]

There is a malfunctioning keyboard where some letter keys do not work. All other keys on the keyboard work properly.

Given a string `text` of words separated by a single space (no leading or trailing spaces) and a string `brokenLetters` of all *distinct* letter keys that are broken, return _the *number of words* in_ `text` _you can fully type using this keyboard_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* text = "hello world", brokenLetters = "ad"
*Output:* 1
*Explanation:* We cannot type "world" because the 'd' key is broken.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* text = "leet code", brokenLetters = "lt"
*Output:* 1
*Explanation:* We cannot type "leet" because the 'l' and 't' keys are broken.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* text = "leet code", brokenLetters = "e"
*Output:* 0
*Explanation:* We cannot type either word because the 'e' key is broken.
----

 
*Constraints:*


* `1 <= text.length <= 10^4^`
* `0 <= brokenLetters.length <= 26`
* `text` consists of words separated by a single space without any leading or trailing spaces.
* Each word only consists of lowercase English letters.
* `brokenLetters` consists of *distinct* lowercase English letters.




== 思路分析


[[src-1935]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1935_MaximumNumberOfWordsYouCanType.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1935_MaximumNumberOfWordsYouCanType_2.java[tag=answer]
// ----
// --
====


== 参考资料


