[#1936-add-minimum-number-of-rungs]
= 1936. Add Minimum Number of Rungs

{leetcode}/problems/add-minimum-number-of-rungs/[LeetCode - 1936. Add Minimum Number of Rungs ^]

You are given a *strictly increasing* integer array `rungs` that represents the *height* of rungs on a ladder. You are currently on the *floor* at height `0`, and you want to reach the last rung.

You are also given an integer `dist`. You can only climb to the next highest rung if the distance between where you are currently at (the floor or on a rung) and the next rung is *at most* `dist`. You are able to insert rungs at any positive *integer* height if a rung is not already there.

Return _the *minimum* number of rungs that must be added to the ladder in order for you to climb to the last rung._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* rungs = [1,3,5,10], dist = 2
*Output:* 2
*Explanation:
*You currently cannot reach the last rung.
Add rungs at heights 7 and 8 to climb this ladder. 
The ladder will now have rungs at [1,3,5,[.underline]#7#,[.underline]#8#,10].
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* rungs = [3,6,8,10], dist = 3
*Output:* 0
*Explanation:*
This ladder can be climbed without adding additional rungs.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* rungs = [3,4,6,7], dist = 2
*Output:* 1
*Explanation:*
You currently cannot reach the first rung from the ground.
Add a rung at height 1 to climb this ladder.
The ladder will now have rungs at [[.underline]#1#,3,4,6,7].
----

 
*Constraints:*


* `1 <= rungs.length <= 10^5^`
* `1 <= rungs[i] <= 10^9^`
* `1 <= dist <= 10^9^`
* `rungs` is *strictly increasing*.




== 思路分析


[[src-1936]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1936_AddMinimumNumberOfRungs.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1936_AddMinimumNumberOfRungs_2.java[tag=answer]
// ----
// --
====


== 参考资料


