[#1955-count-number-of-special-subsequences]
= 1955. Count Number of Special Subsequences

https://leetcode.com/problems/count-number-of-special-subsequences/[LeetCode - 1955. Count Number of Special Subsequences ^]

A sequence is *special* if it consists of a *positive* number of `0`s, followed by a *positive* number of `1`s, then a *positive* number of `2`s.


* For example, `[0,1,2]` and `[0,0,1,1,1,2]` are special.
* In contrast, `[2,1,0]`, `[1]`, and `[0,1,2,0]` are not special.


Given an array `nums` (consisting of *only* integers `0`, `1`, and `2`), return_ the *number of different subsequences* that are special_. Since the answer may be very large, *return it modulo *`10^9^ + 7`.

A *subsequence* of an array is a sequence that can be derived from the array by deleting some or no elements without changing the order of the remaining elements. Two subsequences are *different* if the *set of indices* chosen are different.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [0,1,2,2]
*Output:* 3
*Explanation:* The special subsequences are bolded [*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*,2], [*[.underline]#0#*,*[.underline]#1#*,2,*[.underline]#2#*], and [*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*,*[.underline]#2#*].
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,2,0,0]
*Output:* 0
*Explanation:* There are no special subsequences in [2,2,0,0].
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [0,1,2,0,1,2]
*Output:* 7
*Explanation:* The special subsequences are bolded:
- [*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*,0,1,2]
- [*[.underline]#0#*,*[.underline]#1#*,2,0,1,*[.underline]#2#*]
- [*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*,0,1,*[.underline]#2#*]
- [*[.underline]#0#*,*[.underline]#1#*,2,0,*[.underline]#1#*,*[.underline]#2#*]
- [*[.underline]#0#*,1,2,*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*]
- [*[.underline]#0#*,1,2,0,*[.underline]#1#*,*[.underline]#2#*]
- [0,1,2,*[.underline]#0#*,*[.underline]#1#*,*[.underline]#2#*]
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `0 <= nums[i] <= 2`




== 思路分析


[[src-1955]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1955_CountNumberOfSpecialSubsequences.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1955_CountNumberOfSpecialSubsequences_2.java[tag=answer]
// ----
// --
====


== 参考资料


