[#1964-find-the-longest-valid-obstacle-course-at-each-position]
= 1964. Find the Longest Valid Obstacle Course at Each Position

{leetcode}/problems/find-the-longest-valid-obstacle-course-at-each-position/[LeetCode - 1964. Find the Longest Valid Obstacle Course at Each Position ^]

You want to build some obstacle courses. You are given a *0-indexed* integer array `obstacles` of length `n`, where `obstacles[i]` describes the height of the `i^th^` obstacle.

For every index `i` between `0` and `n - 1` (*inclusive*), find the length of the *longest obstacle course* in `obstacles` such that:


* You choose any number of obstacles between `0` and `i` *inclusive*.
* You must include the `i^th^` obstacle in the course.
* You must put the chosen obstacles in the *same order* as they appear in `obstacles`.
* Every obstacle (except the first) is *taller* than or the *same height* as the obstacle immediately before it.


Return _an array_ `ans` _of length_ `n`, _where_ `ans[i]` _is the length of the *longest obstacle course* for index_ `i`_ as described above_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* obstacles = [1,2,3,2]
*Output:* [1,2,3,3]
*Explanation:* The longest valid obstacle course at each position is:
- i = 0: [[.underline]#1#], [1] has length 1.
- i = 1: [[.underline]#1#,[.underline]#2#], [1,2] has length 2.
- i = 2: [[.underline]#1#,[.underline]#2#,[.underline]#3#], [1,2,3] has length 3.
- i = 3: [[.underline]#1#,[.underline]#2#,3,[.underline]#2#], [1,2,2] has length 3.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* obstacles = [2,2,1]
*Output:* [1,2,1]
*Explanation: *The longest valid obstacle course at each position is:
- i = 0: [[.underline]#2#], [2] has length 1.
- i = 1: [[.underline]#2#,[.underline]#2#], [2,2] has length 2.
- i = 2: [2,2,[.underline]#1#], [1] has length 1.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* obstacles = [3,1,5,6,4,2]
*Output:* [1,1,2,3,2,2]
*Explanation:* The longest valid obstacle course at each position is:
- i = 0: [[.underline]#3#], [3] has length 1.
- i = 1: [3,[.underline]#1#], [1] has length 1.
- i = 2: [[.underline]#3#,1,[.underline]#5#], [3,5] has length 2. [1,5] is also valid.
- i = 3: [[.underline]#3#,1,[.underline]#5#,[.underline]#6#], [3,5,6] has length 3. [1,5,6] is also valid.
- i = 4: [[.underline]#3#,1,5,6,[.underline]#4#], [3,4] has length 2. [1,4] is also valid.
- i = 5: [3,[.underline]#1#,5,6,4,[.underline]#2#], [1,2] has length 2.
----

 
*Constraints:*


* `n == obstacles.length`
* `1 <= n <= 10^5^`
* `1 <= obstacles[i] <= 10^7^`




== 思路分析


[[src-1964]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1964_FindTheLongestValidObstacleCourseAtEachPosition.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1964_FindTheLongestValidObstacleCourseAtEachPosition_2.java[tag=answer]
// ----
// --
====


== 参考资料


