[#1969-minimum-non-zero-product-of-the-array-elements]
= 1969. Minimum Non-Zero Product of the Array Elements

{leetcode}/problems/minimum-non-zero-product-of-the-array-elements/[LeetCode - 1969. Minimum Non-Zero Product of the Array Elements ^]

You are given a positive integer `p`. Consider an array `nums` (*1-indexed*) that consists of the integers in the *inclusive* range `[1, 2^p^ - 1]` in their binary representations. You are allowed to do the following operation *any* number of times:


* Choose two elements `x` and `y` from `nums`.
* Choose a bit in `x` and swap it with its corresponding bit in `y`. Corresponding bit refers to the bit that is in the *same position* in the other integer.


For example, if `x = 11[.underline]#0#1` and `y = 00[.underline]#1#1`, after swapping the `2^nd^` bit from the right, we have `x = 11[.underline]#1#1` and `y = 00[.underline]#0#1`.

Find the *minimum non-zero* product of `nums` after performing the above operation *any* number of times. Return _this product__ *modulo* _`10^9^ + 7`.

*Note:* The answer should be the minimum product *before* the modulo operation is done.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* p = 1
*Output:* 1
*Explanation:* nums = [1].
There is only one element, so the product equals that element.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* p = 2
*Output:* 6
*Explanation:* nums = [01, 10, 11].
Any swap would either make the product 0 or stay the same.
Thus, the array product of 1 * 2 * 3 = 6 is already minimized.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* p = 3
*Output:* 1512
*Explanation:* nums = [001, 010, 011, 100, 101, 110, 111]
- In the first operation we can swap the leftmost bit of the second and fifth elements.
    - The resulting array is [001, [.underline]#1#10, 011, 100, [.underline]#0#01, 110, 111].
- In the second operation we can swap the middle bit of the third and fourth elements.
    - The resulting array is [001, 110, 0[.underline]#0#1, 1[.underline]#1#0, 001, 110, 111].
The array product is 1 * 6 * 1 * 6 * 1 * 6 * 7 = 1512, which is the minimum possible product.
----

 
*Constraints:*


* `1 <= p <= 60`




== 思路分析


[[src-1969]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1969_MinimumNonZeroProductOfTheArrayElements.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1969_MinimumNonZeroProductOfTheArrayElements_2.java[tag=answer]
// ----
// --
====


== 参考资料


