[#1982-find-array-given-subset-sums]
= 1982. Find Array Given Subset Sums

https://leetcode.com/problems/find-array-given-subset-sums/[LeetCode - 1982. Find Array Given Subset Sums ^]

You are given an integer `n` representing the length of an unknown array that you are trying to recover. You are also given an array `sums` containing the values of all `2^n^` *subset sums* of the unknown array (in no particular order).

Return _the array _`ans`_ of length _`n`_ representing the unknown array. If *multiple* answers exist, return *any* of them_.

An array `sub` is a *subset* of an array `arr` if `sub` can be obtained from `arr` by deleting some (possibly zero or all) elements of `arr`. The sum of the elements in `sub` is one possible *subset sum* of `arr`. The sum of an empty array is considered to be `0`.

*Note:* Test cases are generated such that there will *always* be at least one correct answer.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, sums = [-3,-2,-1,0,0,1,2,3]
*Output:* [1,2,-3]
*Explanation: *[1,2,-3] is able to achieve the given subset sums:
- []: sum is 0
- [1]: sum is 1
- [2]: sum is 2
- [1,2]: sum is 3
- [-3]: sum is -3
- [1,-3]: sum is -2
- [2,-3]: sum is -1
- [1,2,-3]: sum is 0
Note that any permutation of [1,2,-3] and also any permutation of [-1,-2,3] will also be accepted.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 2, sums = [0,0,0,0]
*Output:* [0,0]
*Explanation:* The only correct answer is [0,0].
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = 4, sums = [0,0,5,5,4,-1,4,9,9,-1,4,3,4,8,3,8]
*Output:* [0,-1,4,5]
*Explanation:* [0,-1,4,5] is able to achieve the given subset sums.
----

 
*Constraints:*


* `1 <= n <= 15`
* `sums.length == 2^n^`
* `-10^4^ <= sums[i] <= 10^4^`




== 思路分析


[[src-1982]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1982_FindArrayGivenSubsetSums.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1982_FindArrayGivenSubsetSums_2.java[tag=answer]
// ----
// --
====


== 参考资料


