[#1991-find-the-middle-index-in-array]
= 1991. Find the Middle Index in Array

{leetcode}/problems/find-the-middle-index-in-array/[LeetCode - 1991. Find the Middle Index in Array ^]

Given a *0-indexed* integer array `nums`, find the *leftmost* `middleIndex` (i.e., the smallest amongst all the possible ones).

A `middleIndex` is an index where `nums[0] + nums[1] + ... + nums[middleIndex-1] == nums[middleIndex+1] + nums[middleIndex+2] + ... + nums[nums.length-1]`.

If `middleIndex == 0`, the left side sum is considered to be `0`. Similarly, if `middleIndex == nums.length - 1`, the right side sum is considered to be `0`.

Return _the *leftmost* _`middleIndex`_ that satisfies the condition, or _`-1`_ if there is no such index_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,3,-1,[.underline]#8#,4]
*Output:* 3
*Explanation:* The sum of the numbers before index 3 is: 2 + 3 + -1 = 4
The sum of the numbers after index 3 is: 4 = 4
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,-1,[.underline]#4#]
*Output:* 2
*Explanation:* The sum of the numbers before index 2 is: 1 + -1 = 0
The sum of the numbers after index 2 is: 0
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,5]
*Output:* -1
*Explanation:* There is no valid middleIndex.
----

 
*Constraints:*


* `1 <= nums.length <= 100`
* `-1000 <= nums[i] <= 1000`


 
*Note:* This question is the same as 724: <a href="{leetcode}/problems/find-pivot-index/" target="_blank">{leetcode}/problems/find-pivot-index/</a>



== 思路分析


[[src-1991]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1991_FindTheMiddleIndexInArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1991_FindTheMiddleIndexInArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


