[#1996-the-number-of-weak-characters-in-the-game]
= 1996. The Number of Weak Characters in the Game

https://leetcode.com/problems/the-number-of-weak-characters-in-the-game/[LeetCode - 1996. The Number of Weak Characters in the Game ^]

You are playing a game that contains multiple characters, and each of the characters has *two* main properties: *attack* and *defense*. You are given a 2D integer array `properties` where `properties[i] = [attack<sub>i</sub>, defense<sub>i</sub>]` represents the properties of the `i^th^` character in the game.

A character is said to be *weak* if any other character has *both* attack and defense levels *strictly greater* than this character's attack and defense levels. More formally, a character `i` is said to be *weak* if there exists another character `j` where `attack<sub>j</sub> > attack<sub>i</sub>` and `defense<sub>j</sub> > defense<sub>i</sub>`.

Return _the number of *weak* characters_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* properties = [[5,5],[6,3],[3,6]]
*Output:* 0
*Explanation:* No character has strictly greater attack and defense than the other.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* properties = [[2,2],[3,3]]
*Output:* 1
*Explanation:* The first character is weak because the second character has a strictly greater attack and defense.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* properties = [[1,5],[10,4],[4,3]]
*Output:* 1
*Explanation:* The third character is weak because the second character has a strictly greater attack and defense.
----

 
*Constraints:*


* `2 <= properties.length <= 10^5^`
* `properties[i].length == 2`
* `1 <= attack<sub>i</sub>, defense<sub>i</sub> <= 10^5^`




== 思路分析


[[src-1996]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_1996_TheNumberOfWeakCharactersInTheGame.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_1996_TheNumberOfWeakCharactersInTheGame_2.java[tag=answer]
// ----
// --
====


== 参考资料


