[#2009-minimum-number-of-operations-to-make-array-continuous]
= 2009. Minimum Number of Operations to Make Array Continuous

{leetcode}/problems/minimum-number-of-operations-to-make-array-continuous/[LeetCode - 2009. Minimum Number of Operations to Make Array Continuous ^]

You are given an integer array `nums`. In one operation, you can replace *any* element in `nums` with *any* integer.

`nums` is considered *continuous* if both of the following conditions are fulfilled:


* All elements in `nums` are *unique*.
* The difference between the *maximum* element and the *minimum* element in `nums` equals `nums.length - 1`.


For example, `nums = [4, 2, 5, 3]` is *continuous*, but `nums = [1, 2, 3, 5, 6]` is *not continuous*.

Return _the *minimum* number of operations to make _`nums`_ _*_continuous_*.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [4,2,5,3]
*Output:* 0
*Explanation:* nums is already continuous.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3,5,6]
*Output:* 1
*Explanation:* One possible solution is to change the last element to 4.
The resulting array is [1,2,3,5,4], which is continuous.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,10,100,1000]
*Output:* 3
*Explanation:* One possible solution is to:
- Change the second element to 2.
- Change the third element to 3.
- Change the fourth element to 4.
The resulting array is [1,2,3,4], which is continuous.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^9^`




== 思路分析


[[src-2009]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2009_MinimumNumberOfOperationsToMakeArrayContinuous.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2009_MinimumNumberOfOperationsToMakeArrayContinuous_2.java[tag=answer]
// ----
// --
====


== 参考资料


