[#2011-final-value-of-variable-after-performing-operations]
= 2011. Final Value of Variable After Performing Operations

{leetcode}/problems/final-value-of-variable-after-performing-operations/[LeetCode - 2011. Final Value of Variable After Performing Operations ^]

There is a programming language with only *four* operations and *one* variable `X`:


* `++X` and `X++` *increments* the value of the variable `X` by `1`.
* `--X` and `X--` *decrements* the value of the variable `X` by `1`.


Initially, the value of `X` is `0`.

Given an array of strings `operations` containing a list of operations, return _the *final *value of _`X` _after performing all the operations_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* operations = ["--X","X++","X++"]
*Output:* 1
*Explanation:* The operations are performed as follows:
Initially, X = 0.
--X: X is decremented by 1, X =  0 - 1 = -1.
X++: X is incremented by 1, X = -1 + 1 =  0.
X++: X is incremented by 1, X =  0 + 1 =  1.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* operations = ["++X","++X","X++"]
*Output:* 3
*Explanation: *The operations are performed as follows:
Initially, X = 0.
++X: X is incremented by 1, X = 0 + 1 = 1.
++X: X is incremented by 1, X = 1 + 1 = 2.
X++: X is incremented by 1, X = 2 + 1 = 3.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* operations = ["X++","++X","--X","X--"]
*Output:* 0
*Explanation:* The operations are performed as follows:
Initially, X = 0.
X++: X is incremented by 1, X = 0 + 1 = 1.
++X: X is incremented by 1, X = 1 + 1 = 2.
--X: X is decremented by 1, X = 2 - 1 = 1.
X--: X is decremented by 1, X = 1 - 1 = 0.
----

 
*Constraints:*


* `1 <= operations.length <= 100`
* `operations[i]` will be either `"++X"`, `"X++"`, `"--X"`, or `"X--"`.




== 思路分析


[[src-2011]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2011_FinalValueOfVariableAfterPerformingOperations.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2011_FinalValueOfVariableAfterPerformingOperations_2.java[tag=answer]
// ----
// --
====


== 参考资料


