[#2024-maximize-the-confusion-of-an-exam]
= 2024. Maximize the Confusion of an Exam

{leetcode}/problems/maximize-the-confusion-of-an-exam/[LeetCode - 2024. Maximize the Confusion of an Exam ^]

A teacher is writing a test with `n` true/false questions, with `'T'` denoting true and `'F'` denoting false. He wants to confuse the students by *maximizing* the number of *consecutive* questions with the *same* answer (multiple trues or multiple falses in a row).

You are given a string `answerKey`, where `answerKey[i]` is the original answer to the `i^th^` question. In addition, you are given an integer `k`, the maximum number of times you may perform the following operation:


* Change the answer key for any question to `'T'` or `'F'` (i.e., set `answerKey[i]` to `'T'` or `'F'`).


Return _the *maximum* number of consecutive_ `'T'`s or `'F'`s _in the answer key after performing the operation at most_ `k` _times_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* answerKey = "TTFF", k = 2
*Output:* 4
*Explanation:* We can replace both the 'F's with 'T's to make answerKey = "[.underline]#TTTT#".
There are four consecutive 'T's.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* answerKey = "TFFT", k = 1
*Output:* 3
*Explanation:* We can replace the first 'T' with an 'F' to make answerKey = "[.underline]#FFF#T".
Alternatively, we can replace the second 'T' with an 'F' to make answerKey = "T[.underline]#FFF#".
In both cases, there are three consecutive 'F's.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* answerKey = "TTFTTFTT", k = 1
*Output:* 5
*Explanation:* We can replace the first 'F' to make answerKey = "[.underline]#TTTTT#FTT"
Alternatively, we can replace the second 'F' to make answerKey = "TTF[.underline]#TTTTT#". 
In both cases, there are five consecutive 'T's.
----

 
*Constraints:*


* `n == answerKey.length`
* `1 <= n <= 5 * 10^4^`
* `answerKey[i]` is either `'T'` or `'F'`
* `1 <= k <= n`




== 思路分析


[[src-2024]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2024_MaximizeTheConfusionOfAnExam.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2024_MaximizeTheConfusionOfAnExam_2.java[tag=answer]
// ----
// --
====


== 参考资料


