[#2028-find-missing-observations]
= 2028. Find Missing Observations

https://leetcode.com/problems/find-missing-observations/[LeetCode - 2028. Find Missing Observations ^]

You have observations of `n + m` *6-sided* dice rolls with each face numbered from `1` to `6`. `n` of the observations went missing, and you only have the observations of `m` rolls. Fortunately, you have also calculated the *average value* of the `n + m` rolls.

You are given an integer array `rolls` of length `m` where `rolls[i]` is the value of the `i^th^` observation. You are also given the two integers `mean` and `n`.

Return _an array of length _`n`_ containing the missing observations such that the *average value *of the _`n + m`_ rolls is *exactly* _`mean`. If there are multiple valid answers, return _any of them_. If no such array exists, return _an empty array_.

The *average value* of a set of `k` numbers is the sum of the numbers divided by `k`.

Note that `mean` is an integer, so the sum of the `n + m` rolls should be divisible by `n + m`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* rolls = [3,2,4,3], mean = 4, n = 2
*Output:* [6,6]
*Explanation:* The mean of all n + m rolls is (3 + 2 + 4 + 3 + 6 + 6) / 6 = 4.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* rolls = [1,5,6], mean = 3, n = 4
*Output:* [2,3,2,2]
*Explanation:* The mean of all n + m rolls is (1 + 5 + 6 + 2 + 3 + 2 + 2) / 7 = 3.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* rolls = [1,2,3,4], mean = 6, n = 4
*Output:* []
*Explanation:* It is impossible for the mean to be 6 no matter what the 4 missing rolls are.
----

 
*Constraints:*


* `m == rolls.length`
* `1 <= n, m <= 10^5^`
* `1 <= rolls[i], mean <= 6`




== 思路分析


[[src-2028]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2028_FindMissingObservations.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2028_FindMissingObservations_2.java[tag=answer]
// ----
// --
====


== 参考资料


