[#2071-maximum-number-of-tasks-you-can-assign]
= 2071. Maximum Number of Tasks You Can Assign

https://leetcode.com/problems/maximum-number-of-tasks-you-can-assign/[LeetCode - 2071. Maximum Number of Tasks You Can Assign ^]

You have `n` tasks and `m` workers. Each task has a strength requirement stored in a *0-indexed* integer array `tasks`, with the `i^th^` task requiring `tasks[i]` strength to complete. The strength of each worker is stored in a *0-indexed* integer array `workers`, with the `j^th^` worker having `workers[j]` strength. Each worker can only be assigned to a *single* task and must have a strength *greater than or equal* to the task's strength requirement (i.e., `workers[j] >= tasks[i]`).

Additionally, you have `pills` magical pills that will *increase a worker's strength* by `strength`. You can decide which workers receive the magical pills, however, you may only give each worker *at most one* magical pill.

Given the *0-indexed *integer arrays `tasks` and `workers` and the integers `pills` and `strength`, return _the *maximum* number of tasks that can be completed._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* tasks = [[.underline]#*3*#,[.underline]#*2*#,[.underline]#*1*#], workers = [[.underline]#*0*#,[.underline]#*3*#,[.underline]#*3*#], pills = 1, strength = 1
*Output:* 3
*Explanation:*
We can assign the magical pill and tasks as follows:
- Give the magical pill to worker 0.
- Assign worker 0 to task 2 (0 + 1 >= 1)
- Assign worker 1 to task 1 (3 >= 2)
- Assign worker 2 to task 0 (3 >= 3)
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* tasks = [[.underline]#*5*#,4], workers = [[.underline]#*0*#,0,0], pills = 1, strength = 5
*Output:* 1
*Explanation:*
We can assign the magical pill and tasks as follows:
- Give the magical pill to worker 0.
- Assign worker 0 to task 0 (0 + 5 >= 5)
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* tasks = [[.underline]#*10*#,[.underline]#*15*#,30], workers = [[.underline]#*0*#,[.underline]#*10*#,10,10,10], pills = 3, strength = 10
*Output:* 2
*Explanation:*
We can assign the magical pills and tasks as follows:
- Give the magical pill to worker 0 and worker 1.
- Assign worker 0 to task 0 (0 + 10 >= 10)
- Assign worker 1 to task 1 (10 + 10 >= 15)
The last pill is not given because it will not make any worker strong enough for the last task.
----

 
*Constraints:*


* `n == tasks.length`
* `m == workers.length`
* `1 <= n, m <= 5 * 10^4^`
* `0 <= pills <= m`
* `0 <= tasks[i], workers[j], strength <= 10^9^`




== 思路分析


[[src-2071]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2071_MaximumNumberOfTasksYouCanAssign.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2071_MaximumNumberOfTasksYouCanAssign_2.java[tag=answer]
// ----
// --
====


== 参考资料


