[#2109-adding-spaces-to-a-string]
= 2109. Adding Spaces to a String

{leetcode}/problems/adding-spaces-to-a-string/[LeetCode - 2109. Adding Spaces to a String ^]

You are given a *0-indexed* string `s` and a *0-indexed* integer array `spaces` that describes the indices in the original string where spaces will be added. Each space should be inserted *before* the character at the given index.


* For example, given `s = "EnjoyYourCoffee"` and `spaces = [5, 9]`, we place spaces before `'Y'` and `'C'`, which are at indices `5` and `9` respectively. Thus, we obtain `"Enjoy *[.underline]#Y#*our [.underline]#*C*#offee"`.


Return* *_the modified string *after* the spaces have been added._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "LeetcodeHelpsMeLearn", spaces = [8,13,15]
*Output:* "Leetcode Helps Me Learn"
*Explanation:* 
The indices 8, 13, and 15 correspond to the underlined characters in "Leetcode[.underline]#*H*#elps[.underline]#*M*#e[.underline]#*L*#earn".
We then place spaces before those characters.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "icodeinpython", spaces = [1,5,7,9]
*Output:* "i code in py thon"
*Explanation:*
The indices 1, 5, 7, and 9 correspond to the underlined characters in "i[.underline]#*c*#ode[.underline]#*i*#n[.underline]#*p*#y[.underline]#*t*#hon".
We then place spaces before those characters.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "spacing", spaces = [0,1,2,3,4,5,6]
*Output:* " s p a c i n g"
*Explanation:*
We are also able to place spaces before the first character of the string.
----

 
*Constraints:*


* `1 <= s.length <= 3 * 10^5^`
* `s` consists only of lowercase and uppercase English letters.
* `1 <= spaces.length <= 3 * 10^5^`
* `0 <= spaces[i] <= s.length - 1`
* All the values of `spaces` are *strictly increasing*.




== 思路分析


[[src-2109]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2109_AddingSpacesToAString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2109_AddingSpacesToAString_2.java[tag=answer]
// ----
// --
====


== 参考资料


