[#2131-longest-palindrome-by-concatenating-two-letter-words]
= 2131. Longest Palindrome by Concatenating Two Letter Words

{leetcode}/problems/longest-palindrome-by-concatenating-two-letter-words/[LeetCode - 2131. Longest Palindrome by Concatenating Two Letter Words ^]

You are given an array of strings `words`. Each element of `words` consists of *two* lowercase English letters.

Create the *longest possible palindrome* by selecting some elements from `words` and concatenating them in *any order*. Each element can be selected *at most once*.

Return _the *length* of the longest palindrome that you can create_. If it is impossible to create any palindrome, return `0`.

A *palindrome* is a string that reads the same forward and backward.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* words = ["lc","cl","gg"]
*Output:* 6
*Explanation:* One longest palindrome is "lc" + "gg" + "cl" = "lcggcl", of length 6.
Note that "clgglc" is another longest palindrome that can be created.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* words = ["ab","ty","yt","lc","cl","ab"]
*Output:* 8
*Explanation:* One longest palindrome is "ty" + "lc" + "cl" + "yt" = "tylcclyt", of length 8.
Note that "lcyttycl" is another longest palindrome that can be created.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* words = ["cc","ll","xx"]
*Output:* 2
*Explanation:* One longest palindrome is "cc", of length 2.
Note that "ll" is another longest palindrome that can be created, and so is "xx".
----

 
*Constraints:*


* `1 <= words.length <= 10^5^`
* `words[i].length == 2`
* `words[i]` consists of lowercase English letters.




== 思路分析


[[src-2131]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2131_LongestPalindromeByConcatenatingTwoLetterWords.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2131_LongestPalindromeByConcatenatingTwoLetterWords_2.java[tag=answer]
// ----
// --
====


== 参考资料


