[#2149-rearrange-array-elements-by-sign]
= 2149. Rearrange Array Elements by Sign

{leetcode}/problems/rearrange-array-elements-by-sign/[LeetCode - 2149. Rearrange Array Elements by Sign ^]

You are given a *0-indexed* integer array `nums` of *even* length consisting of an *equal* number of positive and negative integers.

You should return the array of nums such that the the array follows the given conditions:


* Every *consecutive pair* of integers have *opposite signs*.
* For all integers with the same sign, the *order* in which they were present in `nums` is *preserved*.
* The rearranged array begins with a positive integer.


Return _the modified array after rearranging the elements to satisfy the aforementioned conditions_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [3,1,-2,-5,2,-4]
*Output:* [3,-2,1,-5,2,-4]
*Explanation:*
The positive integers in nums are [3,1,2]. The negative integers are [-2,-5,-4].
The only possible way to rearrange them such that they satisfy all conditions is [3,-2,1,-5,2,-4].
Other ways such as [1,-2,2,-5,3,-4], [3,1,2,-2,-5,-4], [-2,3,-5,1,-4,2] are incorrect because they do not satisfy one or more conditions.  
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [-1,1]
*Output:* [1,-1]
*Explanation:*
1 is the only positive integer and -1 the only negative integer in nums.
So nums is rearranged to [1,-1].
----

 
*Constraints:*


* `2 <= nums.length <= 2 * 10^5^`
* `nums.length` is *even*
* `1 <= |nums[i]| <= 10^5^`
* `nums` consists of *equal* number of positive and negative integers.


 
It is not required to do the modifications in-place.


== 思路分析


[[src-2149]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2149_RearrangeArrayElementsBySign.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2149_RearrangeArrayElementsBySign_2.java[tag=answer]
// ----
// --
====


== 参考资料


