[#2155-all-divisions-with-the-highest-score-of-a-binary-array]
= 2155. All Divisions With the Highest Score of a Binary Array

{leetcode}/problems/all-divisions-with-the-highest-score-of-a-binary-array/[LeetCode - 2155. All Divisions With the Highest Score of a Binary Array ^]

You are given a *0-indexed* binary array `nums` of length `n`. `nums` can be divided at index `i` (where `0 <= i <= n)` into two arrays (possibly empty) `nums<sub>left</sub>` and `nums<sub>right</sub>`:


* `nums<sub>left</sub>` has all the elements of `nums` between index `0` and `i - 1` *(inclusive)*, while `nums<sub>right</sub>` has all the elements of nums between index `i` and `n - 1` *(inclusive)*.
* If `i == 0`, `nums<sub>left</sub>` is *empty*, while `nums<sub>right</sub>` has all the elements of `nums`.
* If `i == n`, `nums<sub>left</sub>` has all the elements of nums, while `nums<sub>right</sub>` is *empty*.


The *division score* of an index `i` is the *sum* of the number of `0`'s in `nums<sub>left</sub>` and the number of `1`'s in `nums<sub>right</sub>`.

Return _*all distinct indices* that have the *highest* possible *division score*_. You may return the answer in *any order*.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [0,0,1,0]
*Output:* [2,4]
*Explanation:* Division at index
- 0: nums<sub>left</sub> is []. nums<sub>right</sub> is [0,0,[.underline]#*1*#,0]. The score is 0 + 1 = 1.
- 1: nums<sub>left</sub> is [[.underline]#*0*#]. nums<sub>right</sub> is [0,[.underline]#*1*#,0]. The score is 1 + 1 = 2.
- 2: nums<sub>left</sub> is [[.underline]#*0*#,[.underline]#*0*#]. nums<sub>right</sub> is [[.underline]#*1*#,0]. The score is 2 + 1 = 3.
- 3: nums<sub>left</sub> is [[.underline]#*0*#,[.underline]#*0*#,1]. nums<sub>right</sub> is [0]. The score is 2 + 0 = 2.
- 4: nums<sub>left</sub> is [[.underline]#*0*#,[.underline]#*0*#,1,[.underline]#*0*#]. nums<sub>right</sub> is []. The score is 3 + 0 = 3.
Indices 2 and 4 both have the highest possible division score 3.
Note the answer [4,2] would also be accepted.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [0,0,0]
*Output:* [3]
*Explanation:* Division at index
- 0: nums<sub>left</sub> is []. nums<sub>right</sub> is [0,0,0]. The score is 0 + 0 = 0.
- 1: nums<sub>left</sub> is [[.underline]#*0*#]. nums<sub>right</sub> is [0,0]. The score is 1 + 0 = 1.
- 2: nums<sub>left</sub> is [[.underline]#*0*#,[.underline]#*0*#]. nums<sub>right</sub> is [0]. The score is 2 + 0 = 2.
- 3: nums<sub>left</sub> is [[.underline]#*0*#,[.underline]#*0*#,[.underline]#*0*#]. nums<sub>right</sub> is []. The score is 3 + 0 = 3.
Only index 3 has the highest possible division score 3.

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,1]
*Output:* [0]
*Explanation:* Division at index
- 0: nums<sub>left</sub> is []. nums<sub>right</sub> is [[.underline]#*1*#,[.underline]#*1*#]. The score is 0 + 2 = 2.
- 1: nums<sub>left</sub> is [1]. nums<sub>right</sub> is [[.underline]#*1*#]. The score is 0 + 1 = 1.
- 2: nums<sub>left</sub> is [1,1]. nums<sub>right</sub> is []. The score is 0 + 0 = 0.
Only index 0 has the highest possible division score 2.

----

 
*Constraints:*


* `n == nums.length`
* `1 <= n <= 10^5^`
* `nums[i]` is either `0` or `1`.




== 思路分析


[[src-2155]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2155_AllDivisionsWithTheHighestScoreOfABinaryArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2155_AllDivisionsWithTheHighestScoreOfABinaryArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


