[#2161-partition-array-according-to-given-pivot]
= 2161. Partition Array According to Given Pivot

{leetcode}/problems/partition-array-according-to-given-pivot/[LeetCode - 2161. Partition Array According to Given Pivot ^]

You are given a *0-indexed* integer array `nums` and an integer `pivot`. Rearrange `nums` such that the following conditions are satisfied:


* Every element less than `pivot` appears *before* every element greater than `pivot`.
* Every element equal to `pivot` appears *in between* the elements less than and greater than `pivot`.
* The *relative order* of the elements less than `pivot` and the elements greater than `pivot` is maintained.
	
	* More formally, consider every `p<sub>i</sub>`, `p<sub>j</sub>` where `p<sub>i</sub>` is the new position of the `i^th^` element and `p<sub>j</sub>` is the new position of the `j^th^` element. For elements less than `pivot`, if `i < j` and `nums[i] < pivot` and `nums[j] < pivot`, then `p<sub>i</sub> < p<sub>j</sub>`. Similarly for elements greater than `pivot`, if `i < j` and `nums[i] > pivot` and `nums[j] > pivot`, then `p<sub>i</sub> < p<sub>j</sub>`.
	
	


Return `nums`_ after the rearrangement._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [9,12,5,10,14,3,10], pivot = 10
*Output:* [9,5,3,10,10,12,14]
*Explanation:* 
The elements 9, 5, and 3 are less than the pivot so they are on the left side of the array.
The elements 12 and 14 are greater than the pivot so they are on the right side of the array.
The relative ordering of the elements less than and greater than pivot is also maintained. [9, 5, 3] and [12, 14] are the respective orderings.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [-3,4,3,2], pivot = 2
*Output:* [-3,2,4,3]
*Explanation:* 
The element -3 is less than the pivot so it is on the left side of the array.
The elements 4 and 3 are greater than the pivot so they are on the right side of the array.
The relative ordering of the elements less than and greater than pivot is also maintained. [-3] and [4, 3] are the respective orderings.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `-10^6^ <= nums[i] <= 10^6^`
* `pivot` equals to an element of `nums`.




== 思路分析


[[src-2161]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2161_PartitionArrayAccordingToGivenPivot.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2161_PartitionArrayAccordingToGivenPivot_2.java[tag=answer]
// ----
// --
====


== 参考资料


