[#2164-sort-even-and-odd-indices-independently]
= 2164. Sort Even and Odd Indices Independently

{leetcode}/problems/sort-even-and-odd-indices-independently/[LeetCode - 2164. Sort Even and Odd Indices Independently ^]

You are given a *0-indexed* integer array `nums`. Rearrange the values of `nums` according to the following rules:


* Sort the values at *odd indices* of `nums` in *non-increasing* order.

	
	* For example, if `nums = [4,*[.underline]#1#*,2,[.underline]#*3*#]` before this step, it becomes `[4,[.underline]#*3*#,2,*[.underline]#1#*]` after. The values at odd indices `1` and `3` are sorted in non-increasing order.
	
	
* Sort the values at *even indices* of `nums` in *non-decreasing* order.
	
	* For example, if `nums = [[.underline]#*4*#,1,[.underline]#*2*#,3]` before this step, it becomes `[[.underline]#*2*#,1,[.underline]#*4*#,3]` after. The values at even indices `0` and `2` are sorted in non-decreasing order.
	
	


Return _the array formed after rearranging the values of_ `nums`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [4,1,2,3]
*Output:* [2,3,4,1]
*Explanation:* 
First, we sort the values present at odd indices (1 and 3) in non-increasing order.
So, nums changes from [4,*[.underline]#1#*,2,*[.underline]#3#*] to [4,[.underline]#*3*#,2,*[.underline]#1#*].
Next, we sort the values present at even indices (0 and 2) in non-decreasing order.
So, nums changes from [[.underline]#*4*#,1,*[.underline]#2#*,3] to [[.underline]#*2*#,3,[.underline]#*4*#,1].
Thus, the array formed after rearranging the values is [2,3,4,1].
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,1]
*Output:* [2,1]
*Explanation:* 
Since there is exactly one odd index and one even index, no rearrangement of values takes place.
The resultant array formed is [2,1], which is the same as the initial array. 
----

 
*Constraints:*


* `1 <= nums.length <= 100`
* `1 <= nums[i] <= 100`




== 思路分析


[[src-2164]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2164_SortEvenAndOddIndicesIndependently.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2164_SortEvenAndOddIndicesIndependently_2.java[tag=answer]
// ----
// --
====


== 参考资料


