[#2172-maximum-and-sum-of-array]
= 2172. Maximum AND Sum of Array

{leetcode}/problems/maximum-and-sum-of-array/[LeetCode - 2172. Maximum AND Sum of Array ^]

You are given an integer array `nums` of length `n` and an integer `numSlots` such that `2 * numSlots >= n`. There are `numSlots` slots numbered from `1` to `numSlots`.

You have to place all `n` integers into the slots such that each slot contains at *most* two numbers. The *AND sum* of a given placement is the sum of the *bitwise* `AND` of every number with its respective slot number.


* For example, the *AND sum* of placing the numbers `[1, 3]` into slot [.underline]#`1`# and `[4, 6]` into slot [.underline]#`2`# is equal to `(1 AND [.underline]#1#) + (3 AND [.underline]#1#) + (4 AND [.underline]#2#) + (6 AND [.underline]#2#) = 1 + 1 + 0 + 2 = 4`.


Return _the maximum possible *AND sum* of _`nums`_ given _`numSlots`_ slots._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3,4,5,6], numSlots = 3
*Output:* 9
*Explanation:* One possible placement is [1, 4] into slot [.underline]#1#, [2, 6] into slot [.underline]#2#, and [3, 5] into slot [.underline]#3#. 
This gives the maximum AND sum of (1 AND [.underline]#1#) + (4 AND [.underline]#1#) + (2 AND [.underline]#2#) + (6 AND [.underline]#2#) + (3 AND [.underline]#3#) + (5 AND [.underline]#3#) = 1 + 0 + 2 + 2 + 3 + 1 = 9.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,3,10,4,7,1], numSlots = 9
*Output:* 24
*Explanation:* One possible placement is [1, 1] into slot [.underline]#1#, [3] into slot [.underline]#3#, [4] into slot [.underline]#4#, [7] into slot [.underline]#7#, and [10] into slot [.underline]#9#.
This gives the maximum AND sum of (1 AND [.underline]#1#) + (1 AND [.underline]#1#) + (3 AND [.underline]#3#) + (4 AND [.underline]#4#) + (7 AND [.underline]#7#) + (10 AND [.underline]#9#) = 1 + 1 + 3 + 4 + 7 + 8 = 24.
Note that slots 2, 5, 6, and 8 are empty which is permitted.
----

 
*Constraints:*


* `n == nums.length`
* `1 <= numSlots <= 9`
* `1 <= n <= 2 * numSlots`
* `1 <= nums[i] <= 15`




== 思路分析


[[src-2172]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2172_MaximumAndSumOfArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2172_MaximumAndSumOfArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


