[#2197-replace-non-coprime-numbers-in-array]
= 2197. Replace Non-Coprime Numbers in Array

https://leetcode.com/problems/replace-non-coprime-numbers-in-array/[LeetCode - 2197. Replace Non-Coprime Numbers in Array ^]

You are given an array of integers `nums`. Perform the following steps:


* Find *any* two *adjacent* numbers in `nums` that are *non-coprime*.
* If no such numbers are found, *stop* the process.
* Otherwise, delete the two numbers and *replace* them with their *LCM (Least Common Multiple)*.
* *Repeat* this process as long as you keep finding two adjacent non-coprime numbers.


Return _the *final* modified array._ It can be shown that replacing adjacent non-coprime numbers in *any* arbitrary order will lead to the same result.

The test cases are generated such that the values in the final array are *less than or equal* to `10^8^`.

Two values `x` and `y` are *non-coprime* if `GCD(x, y) > 1` where `GCD(x, y)` is the *Greatest Common Divisor* of `x` and `y`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [6,4,3,2,7,6,2]
*Output:* [12,7,6]
*Explanation:* 
- (6, 4) are non-coprime with LCM(6, 4) = 12. Now, nums = [*[.underline]#12#*,3,2,7,6,2].
- (12, 3) are non-coprime with LCM(12, 3) = 12. Now, nums = [*[.underline]#12#*,2,7,6,2].
- (12, 2) are non-coprime with LCM(12, 2) = 12. Now, nums = [*[.underline]#12#*,7,6,2].
- (6, 2) are non-coprime with LCM(6, 2) = 6. Now, nums = [12,7,[.underline]#*6*#].
There are no more adjacent non-coprime numbers in nums.
Thus, the final modified array is [12,7,6].
Note that there are other ways to obtain the same resultant array.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,2,1,1,3,3,3]
*Output:* [2,1,1,3]
*Explanation:* 
- (3, 3) are non-coprime with LCM(3, 3) = 3. Now, nums = [2,2,1,1,[.underline]#*3*#,3].
- (3, 3) are non-coprime with LCM(3, 3) = 3. Now, nums = [2,2,1,1,[.underline]#*3*#].
- (2, 2) are non-coprime with LCM(2, 2) = 2. Now, nums = [[.underline]#*2*#,1,1,3].
There are no more adjacent non-coprime numbers in nums.
Thus, the final modified array is [2,1,1,3].
Note that there are other ways to obtain the same resultant array.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^5^`
* The test cases are generated such that the values in the final array are *less than or equal* to `10^8^`.




== 思路分析


[[src-2197]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2197_ReplaceNonCoprimeNumbersInArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2197_ReplaceNonCoprimeNumbersInArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


