[#2213-longest-substring-of-one-repeating-character]
= 2213. Longest Substring of One Repeating Character

{leetcode}/problems/longest-substring-of-one-repeating-character/[LeetCode - 2213. Longest Substring of One Repeating Character ^]

You are given a *0-indexed* string `s`. You are also given a *0-indexed* string `queryCharacters` of length `k` and a *0-indexed* array of integer *indices* `queryIndices` of length `k`, both of which are used to describe `k` queries.

The `i^th^` query updates the character in `s` at index `queryIndices[i]` to the character `queryCharacters[i]`.

Return _an array_ `lengths` _of length _`k`_ where_ `lengths[i]` _is the *length* of the *longest substring* of _`s`_ consisting of *only one repeating* character *after* the_ `i^th^` _query__ is performed._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "babacc", queryCharacters = "bcb", queryIndices = [1,3,3]
*Output:* [3,3,4]
*Explanation:* 
- 1^st^ query updates s = "[.underline]#b*b*b#acc". The longest substring consisting of one repeating character is "bbb" with length 3.
- 2^nd^ query updates s = "bbb[.underline]#*c*cc#". 
  The longest substring consisting of one repeating character can be "bbb" or "ccc" with length 3.
- 3^rd^ query updates s = "[.underline]#bbb*b*#cc". The longest substring consisting of one repeating character is "bbbb" with length 4.
Thus, we return [3,3,4].
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abyzz", queryCharacters = "aa", queryIndices = [2,1]
*Output:* [2,3]
*Explanation:*
- 1^st^ query updates s = "ab*a*[.underline]#zz#". The longest substring consisting of one repeating character is "zz" with length 2.
- 2^nd^ query updates s = "[.underline]#a*a*a#zz". The longest substring consisting of one repeating character is "aaa" with length 3.
Thus, we return [2,3].
----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consists of lowercase English letters.
* `k == queryCharacters.length == queryIndices.length`
* `1 <= k <= 10^5^`
* `queryCharacters` consists of lowercase English letters.
* `0 <= queryIndices[i] < s.length`




== 思路分析


[[src-2213]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2213_LongestSubstringOfOneRepeatingCharacter.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2213_LongestSubstringOfOneRepeatingCharacter_2.java[tag=answer]
// ----
// --
====


== 参考资料


