[#2220-minimum-bit-flips-to-convert-number]
= 2220. Minimum Bit Flips to Convert Number

{leetcode}/problems/minimum-bit-flips-to-convert-number/[LeetCode - 2220. Minimum Bit Flips to Convert Number ^]

A *bit flip* of a number `x` is choosing a bit in the binary representation of `x` and *flipping* it from either `0` to `1` or `1` to `0`.


* For example, for `x = 7`, the binary representation is `111` and we may choose any bit (including any leading zeros not shown) and flip it. We can flip the first bit from the right to get `110`, flip the second bit from the right to get `101`, flip the fifth bit from the right (a leading zero) to get `10111`, etc.


Given two integers `start` and `goal`, return_ the *minimum* number of *bit flips* to convert _`start`_ to _`goal`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* start = 10, goal = 7
*Output:* 3
*Explanation:* The binary representation of 10 and 7 are 1010 and 0111 respectively. We can convert 10 to 7 in 3 steps:
- Flip the first bit from the right: 101[.underline]#0# -> 101[.underline]#1#.
- Flip the third bit from the right: 1[.underline]#0#11 -> 1[.underline]#1#11.
- Flip the fourth bit from the right: [.underline]#1#111 -> [.underline]#0#111.
It can be shown we cannot convert 10 to 7 in less than 3 steps. Hence, we return 3.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* start = 3, goal = 4
*Output:* 3
*Explanation:* The binary representation of 3 and 4 are 011 and 100 respectively. We can convert 3 to 4 in 3 steps:
- Flip the first bit from the right: 01[.underline]#1# -> 01[.underline]#0#.
- Flip the second bit from the right: 0[.underline]#1#0 -> 0[.underline]#0#0.
- Flip the third bit from the right: [.underline]#0#00 -> [.underline]#1#00.
It can be shown we cannot convert 3 to 4 in less than 3 steps. Hence, we return 3.

----

 
*Constraints:*


* `0 <= start, goal <= 10^9^`




== 思路分析


[[src-2220]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2220_MinimumBitFlipsToConvertNumber.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2220_MinimumBitFlipsToConvertNumber_2.java[tag=answer]
// ----
// --
====


== 参考资料


