[#2274-maximum-consecutive-floors-without-special-floors]
= 2274. Maximum Consecutive Floors Without Special Floors

https://leetcode.com/problems/maximum-consecutive-floors-without-special-floors/[LeetCode - 2274. Maximum Consecutive Floors Without Special Floors ^]

Alice manages a company and has rented some floors of a building as office space. Alice has decided some of these floors should be *special floors*, used for relaxation only.

You are given two integers `bottom` and `top`, which denote that Alice has rented all the floors from `bottom` to `top` (*inclusive*). You are also given the integer array `special`, where `special[i]` denotes a special floor that Alice has designated for relaxation.

Return _the *maximum* number of consecutive floors without a special floor_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* bottom = 2, top = 9, special = [4,6]
*Output:* 3
*Explanation:* The following are the ranges (inclusive) of consecutive floors without a special floor:
- (2, 3) with a total amount of 2 floors.
- (5, 5) with a total amount of 1 floor.
- (7, 9) with a total amount of 3 floors.
Therefore, we return the maximum number which is 3 floors.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* bottom = 6, top = 8, special = [7,6,8]
*Output:* 0
*Explanation:* Every floor rented is a special floor, so we return 0.
----

 
*Constraints:*


* `1 <= special.length <= 10^5^`
* `1 <= bottom <= special[i] <= top <= 10^9^`
* All the values of `special` are *unique*.




== 思路分析


[[src-2274]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2274_MaximumConsecutiveFloorsWithoutSpecialFloors.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2274_MaximumConsecutiveFloorsWithoutSpecialFloors_2.java[tag=answer]
// ----
// --
====


== 参考资料


