[#2275-largest-combination-with-bitwise-and-greater-than-zero]
= 2275. Largest Combination With Bitwise AND Greater Than Zero

{leetcode}/problems/largest-combination-with-bitwise-and-greater-than-zero/[LeetCode - 2275. Largest Combination With Bitwise AND Greater Than Zero ^]

The *bitwise AND* of an array `nums` is the bitwise AND of all integers in `nums`.


* For example, for `nums = [1, 5, 3]`, the bitwise AND is equal to `1 &amp; 5 &amp; 3 = 1`.
* Also, for `nums = [7]`, the bitwise AND is `7`.


You are given an array of positive integers `candidates`. Evaluate the *bitwise AND* of every *combination* of numbers of `candidates`. Each number in `candidates` may only be used *once* in each combination.

Return _the size of the *largest* combination of _`candidates`_ with a bitwise AND *greater* than _`0`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* candidates = [16,17,71,62,12,24,14]
*Output:* 4
*Explanation:* The combination [16,17,62,24] has a bitwise AND of 16 &amp; 17 &amp; 62 &amp; 24 = 16 > 0.
The size of the combination is 4.
It can be shown that no combination with a size greater than 4 has a bitwise AND greater than 0.
Note that more than one combination may have the largest size.
For example, the combination [62,12,24,14] has a bitwise AND of 62 &amp; 12 &amp; 24 &amp; 14 = 8 > 0.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* candidates = [8,8]
*Output:* 2
*Explanation:* The largest combination [8,8] has a bitwise AND of 8 &amp; 8 = 8 > 0.
The size of the combination is 2, so we return 2.
----

 
*Constraints:*


* `1 <= candidates.length <= 10^5^`
* `1 <= candidates[i] <= 10^7^`




== 思路分析


[[src-2275]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2275_LargestCombinationWithBitwiseAndGreaterThanZero.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2275_LargestCombinationWithBitwiseAndGreaterThanZero_2.java[tag=answer]
// ----
// --
====


== 参考资料


