[#2295-replace-elements-in-an-array]
= 2295. Replace Elements in an Array

{leetcode}/problems/replace-elements-in-an-array/[LeetCode - 2295. Replace Elements in an Array ^]

You are given a *0-indexed* array `nums` that consists of `n` *distinct* positive integers. Apply `m` operations to this array, where in the `i^th^` operation you replace the number `operations[i][0]` with `operations[i][1]`.

It is guaranteed that in the `i^th^` operation:


* `operations[i][0]` *exists* in `nums`.
* `operations[i][1]` does *not* exist in `nums`.


Return _the array obtained after applying all the operations_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,4,6], operations = [[1,3],[4,7],[6,1]]
*Output:* [3,2,7,1]
*Explanation:* We perform the following operations on nums:
- Replace the number 1 with 3. nums becomes [[.underline]#*3*#,2,4,6].
- Replace the number 4 with 7. nums becomes [3,2,[.underline]#*7*#,6].
- Replace the number 6 with 1. nums becomes [3,2,7,[.underline]#*1*#].
We return the final array [3,2,7,1].
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2], operations = [[1,3],[2,1],[3,2]]
*Output:* [2,1]
*Explanation:* We perform the following operations to nums:
- Replace the number 1 with 3. nums becomes [[.underline]#*3*#,2].
- Replace the number 2 with 1. nums becomes [3,[.underline]#*1*#].
- Replace the number 3 with 2. nums becomes [[.underline]#*2*#,1].
We return the array [2,1].
----

 
*Constraints:*


* `n == nums.length`
* `m == operations.length`
* `1 <= n, m <= 10^5^`
* All the values of `nums` are *distinct*.
* `operations[i].length == 2`
* `1 <= nums[i], operations[i][0], operations[i][1] <= 10^6^`
* `operations[i][0]` will exist in `nums` when applying the `i^th^` operation.
* `operations[i][1]` will not exist in `nums` when applying the `i^th^` operation.




== 思路分析


[[src-2295]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2295_ReplaceElementsInAnArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2295_ReplaceElementsInAnArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


