[#2299-strong-password-checker-ii]
= 2299. Strong Password Checker II

{leetcode}/problems/strong-password-checker-ii/[LeetCode - 2299. Strong Password Checker II ^]

A password is said to be *strong* if it satisfies all the following criteria:


* It has at least `8` characters.
* It contains at least *one lowercase* letter.
* It contains at least *one uppercase* letter.
* It contains at least *one digit*.
* It contains at least *one special character*. The special characters are the characters in the following string: `"!@#$%^&amp;*()-+"`.
* It does *not* contain `2` of the same character in adjacent positions (i.e., `"aab"` violates this condition, but `"aba"` does not).


Given a string `password`, return `true`_ if it is a *strong* password_. Otherwise, return `false`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* password = "IloveLe3tcode!"
*Output:* true
*Explanation:* The password meets all the requirements. Therefore, we return true.

----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* password = "Me+You--IsMyDream"
*Output:* false
*Explanation:* The password does not contain a digit and also contains 2 of the same character in adjacent positions. Therefore, we return false.

----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* password = "1aB!"
*Output:* false
*Explanation:* The password does not meet the length requirement. Therefore, we return false.
----

 
*Constraints:*


* `1 <= password.length <= 100`
* `password` consists of letters, digits, and special characters: `"!@#$%^&amp;*()-+"`.




== 思路分析


[[src-2299]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2299_StrongPasswordCheckerIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2299_StrongPasswordCheckerIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


