[#2300-successful-pairs-of-spells-and-potions]
= 2300. Successful Pairs of Spells and Potions

https://leetcode.com/problems/successful-pairs-of-spells-and-potions/[LeetCode - 2300. Successful Pairs of Spells and Potions ^]

You are given two positive integer arrays `spells` and `potions`, of length `n` and `m` respectively, where `spells[i]` represents the strength of the `i^th^` spell and `potions[j]` represents the strength of the `j^th^` potion.

You are also given an integer `success`. A spell and potion pair is considered *successful* if the *product* of their strengths is *at least* `success`.

Return _an integer array _`pairs`_ of length _`n`_ where _`pairs[i]`_ is the number of *potions* that will form a successful pair with the _`i^th^`_ spell._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* spells = [5,1,3], potions = [1,2,3,4,5], success = 7
*Output:* [4,0,3]
*Explanation:*
- 0^th^ spell: 5 * [1,2,3,4,5] = [5,[.underline]#*10*#,[.underline]#*15*#,[.underline]#*20*#,[.underline]#*25*#]. 4 pairs are successful.
- 1^st^ spell: 1 * [1,2,3,4,5] = [1,2,3,4,5]. 0 pairs are successful.
- 2^nd^ spell: 3 * [1,2,3,4,5] = [3,6,[.underline]#*9*#,[.underline]#*12*#,[.underline]#*15*#]. 3 pairs are successful.
Thus, [4,0,3] is returned.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* spells = [3,1,2], potions = [8,5,8], success = 16
*Output:* [2,0,2]
*Explanation:*
- 0^th^ spell: 3 * [8,5,8] = [[.underline]#*24*#,15,[.underline]#*24*#]. 2 pairs are successful.
- 1^st^ spell: 1 * [8,5,8] = [8,5,8]. 0 pairs are successful. 
- 2^nd^ spell: 2 * [8,5,8] = [*[.underline]#16#*,10,[.underline]#*16*#]. 2 pairs are successful. 
Thus, [2,0,2] is returned.
----

 
*Constraints:*


* `n == spells.length`
* `m == potions.length`
* `1 <= n, m <= 10^5^`
* `1 <= spells[i], potions[i] <= 10^5^`
* `1 <= success <= 10^10^`




== 思路分析


[[src-2300]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2300_SuccessfulPairsOfSpellsAndPotions.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2300_SuccessfulPairsOfSpellsAndPotions_2.java[tag=answer]
// ----
// --
====


== 参考资料


