[#2301-match-substring-after-replacement]
= 2301. Match Substring After Replacement

{leetcode}/problems/match-substring-after-replacement/[LeetCode - 2301. Match Substring After Replacement ^]

You are given two strings `s` and `sub`. You are also given a 2D character array `mappings` where `mappings[i] = [old<sub>i</sub>, new<sub>i</sub>]` indicates that you may perform the following operation *any* number of times:


* *Replace* a character `old<sub>i</sub>` of `sub` with `new<sub>i</sub>`.


Each character in `sub` *cannot* be replaced more than once.

Return `true`_ if it is possible to make _`sub`_ a substring of _`s`_ by replacing zero or more characters according to _`mappings`. Otherwise, return `false`.

A *substring* is a contiguous non-empty sequence of characters within a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "fool3e7bar", sub = "leet", mappings = [["e","3"],["t","7"],["t","8"]]
*Output:* true
*Explanation:* Replace the first 'e' in sub with '3' and 't' in sub with '7'.
Now sub = "l3e7" is a substring of s, so we return true.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "fooleetbar", sub = "f00l", mappings = [["o","0"]]
*Output:* false
*Explanation:* The string "f00l" is not a substring of s and no replacements can be made.
Note that we cannot replace '0' with 'o'.

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "Fool33tbaR", sub = "leetd", mappings = [["e","3"],["t","7"],["t","8"],["d","b"],["p","b"]]
*Output:* true
*Explanation:* Replace the first and second 'e' in sub with '3' and 'd' in sub with 'b'.
Now sub = "l33tb" is a substring of s, so we return true.


----

 
*Constraints:*


* `1 <= sub.length <= s.length <= 5000`
* `0 <= mappings.length <= 1000`
* `mappings[i].length == 2`
* `old<sub>i</sub> != new<sub>i</sub>`
* `s` and `sub` consist of uppercase and lowercase English letters and digits.
* `old<sub>i</sub>` and `new<sub>i</sub>` are either uppercase or lowercase English letters or digits.




== 思路分析


[[src-2301]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2301_MatchSubstringAfterReplacement.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2301_MatchSubstringAfterReplacement_2.java[tag=answer]
// ----
// --
====


== 参考资料


