[#2303-calculate-amount-paid-in-taxes]
= 2303. Calculate Amount Paid in Taxes

{leetcode}/problems/calculate-amount-paid-in-taxes/[LeetCode - 2303. Calculate Amount Paid in Taxes ^]

You are given a *0-indexed* 2D integer array `brackets` where `brackets[i] = [upper<sub>i</sub>, percent<sub>i</sub>]` means that the `i^th^` tax bracket has an upper bound of `upper<sub>i</sub>` and is taxed at a rate of `percent<sub>i</sub>`. The brackets are *sorted* by upper bound (i.e. `upper<sub>i-1</sub> < upper<sub>i</sub>` for `0 < i < brackets.length`).

Tax is calculated as follows:


* The first `upper<sub>0</sub>` dollars earned are taxed at a rate of `percent<sub>0</sub>`.
* The next `upper<sub>1</sub> - upper<sub>0</sub>` dollars earned are taxed at a rate of `percent<sub>1</sub>`.
* The next `upper<sub>2</sub> - upper<sub>1</sub>` dollars earned are taxed at a rate of `percent<sub>2</sub>`.
* And so on.


You are given an integer `income` representing the amount of money you earned. Return _the amount of money that you have to pay in taxes._ Answers within `10^-5^` of the actual answer will be accepted.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* brackets = [[3,50],[7,10],[12,25]], income = 10
*Output:* 2.65000
*Explanation:*
Based on your income, you have 3 dollars in the 1^st^ tax bracket, 4 dollars in the 2^nd^ tax bracket, and 3 dollars in the 3^rd^ tax bracket.
The tax rate for the three tax brackets is 50%, 10%, and 25%, respectively.
In total, you pay $3 * 50% + $4 * 10% + $3 * 25% = $2.65 in taxes.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* brackets = [[1,0],[4,25],[5,50]], income = 2
*Output:* 0.25000
*Explanation:*
Based on your income, you have 1 dollar in the 1^st^ tax bracket and 1 dollar in the 2^nd^ tax bracket.
The tax rate for the two tax brackets is 0% and 25%, respectively.
In total, you pay $1 * 0% + $1 * 25% = $0.25 in taxes.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* brackets = [[2,50]], income = 0
*Output:* 0.00000
*Explanation:*
You have no income to tax, so you have to pay a total of $0 in taxes.
----

 
*Constraints:*


* `1 <= brackets.length <= 100`
* `1 <= upper<sub>i</sub> <= 1000`
* `0 <= percent<sub>i</sub> <= 100`
* `0 <= income <= 1000`
* `upper<sub>i</sub>` is sorted in ascending order.
* All the values of `upper<sub>i</sub>` are *unique*.
* The upper bound of the last tax bracket is greater than or equal to `income`.




== 思路分析


[[src-2303]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2303_CalculateAmountPaidInTaxes.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2303_CalculateAmountPaidInTaxes_2.java[tag=answer]
// ----
// --
====


== 参考资料


