[#2318-number-of-distinct-roll-sequences]
= 2318. Number of Distinct Roll Sequences

https://leetcode.com/problems/number-of-distinct-roll-sequences/[LeetCode - 2318. Number of Distinct Roll Sequences ^]

You are given an integer `n`. You roll a fair 6-sided dice `n` times. Determine the total number of *distinct* sequences of rolls possible such that the following conditions are satisfied:


* The *greatest common divisor* of any *adjacent* values in the sequence is equal to `1`.
* There is *at least* a gap of `2` rolls between *equal* valued rolls. More formally, if the value of the `i^th^` roll is *equal* to the value of the `j^th^` roll, then `abs(i - j) > 2`.


Return _the* total number* of distinct sequences possible_. Since the answer may be very large, return it *modulo* `10^9^ + 7`.

Two sequences are considered distinct if at least one element is different.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 4
*Output:* 184
*Explanation:* Some of the possible sequences are (1, 2, 3, 4), (6, 1, 2, 3), (1, 2, 3, 1), etc.
Some invalid sequences are (1, 2, 1, 3), (1, 2, 3, 6).
(1, 2, 1, 3) is invalid since the first and third roll have an equal value and abs(1 - 3) = 2 (i and j are 1-indexed).
(1, 2, 3, 6) is invalid since the greatest common divisor of 3 and 6 = 3.
There are a total of 184 distinct sequences possible, so we return 184.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 2
*Output:* 22
*Explanation:* Some of the possible sequences are (1, 2), (2, 1), (3, 2).
Some invalid sequences are (3, 6), (2, 4) since the greatest common divisor is not equal to 1.
There are a total of 22 distinct sequences possible, so we return 22.

----

 
*Constraints:*


* `1 <= n <= 10^4^`




== 思路分析


[[src-2318]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2318_NumberOfDistinctRollSequences.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2318_NumberOfDistinctRollSequences_2.java[tag=answer]
// ----
// --
====


== 参考资料


