[#2365-task-scheduler-ii]
= 2365. Task Scheduler II

{leetcode}/problems/task-scheduler-ii/[LeetCode - 2365. Task Scheduler II ^]

You are given a *0-indexed* array of positive integers `tasks`, representing tasks that need to be completed *in order*, where `tasks[i]` represents the *type* of the `i^th^` task.

You are also given a positive integer `space`, which represents the *minimum* number of days that must pass *after* the completion of a task before another task of the *same* type can be performed.

Each day, until all tasks have been completed, you must either:


* Complete the next task from `tasks`, or
* Take a break.


Return_ the *minimum* number of days needed to complete all tasks_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* tasks = [1,2,1,2,3,1], space = 3
*Output:* 9
*Explanation:*
One way to complete all tasks in 9 days is as follows:
Day 1: Complete the 0th task.
Day 2: Complete the 1st task.
Day 3: Take a break.
Day 4: Take a break.
Day 5: Complete the 2nd task.
Day 6: Complete the 3rd task.
Day 7: Take a break.
Day 8: Complete the 4th task.
Day 9: Complete the 5th task.
It can be shown that the tasks cannot be completed in less than 9 days.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* tasks = [5,8,8,5], space = 2
*Output:* 6
*Explanation:*
One way to complete all tasks in 6 days is as follows:
Day 1: Complete the 0th task.
Day 2: Complete the 1st task.
Day 3: Take a break.
Day 4: Take a break.
Day 5: Complete the 2nd task.
Day 6: Complete the 3rd task.
It can be shown that the tasks cannot be completed in less than 6 days.
----

 
*Constraints:*


* `1 <= tasks.length <= 10^5^`
* `1 <= tasks[i] <= 10^9^`
* `1 <= space <= tasks.length`




== 思路分析


[[src-2365]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2365_TaskSchedulerIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2365_TaskSchedulerIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


