[#2369-check-if-there-is-a-valid-partition-for-the-array]
= 2369. Check if There is a Valid Partition For The Array

https://leetcode.com/problems/check-if-there-is-a-valid-partition-for-the-array/[LeetCode - 2369. Check if There is a Valid Partition For The Array ^]

You are given a *0-indexed* integer array `nums`. You have to partition the array into one or more *contiguous* subarrays.

We call a partition of the array *valid* if each of the obtained subarrays satisfies *one* of the following conditions:


* The subarray consists of *exactly* `2,` equal elements. For example, the subarray `[2,2]` is good.
* The subarray consists of *exactly* `3,` equal elements. For example, the subarray `[4,4,4]` is good.
* The subarray consists of *exactly* `3` consecutive increasing elements, that is, the difference between adjacent elements is `1`. For example, the subarray `[3,4,5]` is good, but the subarray `[1,3,5]` is not.


Return `true`_ if the array has *at least* one valid partition_. Otherwise, return `false`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [4,4,4,5,6]
*Output:* true
*Explanation:* The array can be partitioned into the subarrays [4,4] and [4,5,6].
This partition is valid, so we return true.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,1,1,2]
*Output:* false
*Explanation:* There is no valid partition for this array.
----

 
*Constraints:*


* `2 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^6^`




== 思路分析


[[src-2369]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2369_CheckIfThereIsAValidPartitionForTheArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2369_CheckIfThereIsAValidPartitionForTheArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


