[#2406-divide-intervals-into-minimum-number-of-groups]
= 2406. Divide Intervals Into Minimum Number of Groups

{leetcode}/problems/divide-intervals-into-minimum-number-of-groups/[LeetCode - 2406. Divide Intervals Into Minimum Number of Groups ^]

You are given a 2D integer array `intervals` where `intervals[i] = [left<sub>i</sub>, right<sub>i</sub>]` represents the *inclusive* interval `[left<sub>i</sub>, right<sub>i</sub>]`.

You have to divide the intervals into one or more *groups* such that each interval is in *exactly* one group, and no two intervals that are in the same group *intersect* each other.

Return _the *minimum* number of groups you need to make_.

Two intervals *intersect* if there is at least one common number between them. For example, the intervals `[1, 5]` and `[5, 8]` intersect.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* intervals = [[5,10],[6,8],[1,5],[2,3],[1,10]]
*Output:* 3
*Explanation:* We can divide the intervals into the following groups:
- Group 1: [1, 5], [6, 8].
- Group 2: [2, 3], [5, 10].
- Group 3: [1, 10].
It can be proven that it is not possible to divide the intervals into fewer than 3 groups.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* intervals = [[1,3],[5,6],[8,10],[11,13]]
*Output:* 1
*Explanation:* None of the intervals overlap, so we can put all of them in one group.
----

 
*Constraints:*


* `1 <= intervals.length <= 10^5^`
* `intervals[i].length == 2`
* `1 <= left<sub>i</sub> <= right<sub>i</sub> <= 10^6^`




== 思路分析


[[src-2406]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2406_DivideIntervalsIntoMinimumNumberOfGroups.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2406_DivideIntervalsIntoMinimumNumberOfGroups_2.java[tag=answer]
// ----
// --
====


== 参考资料


