[#2412-minimum-money-required-before-transactions]
= 2412. Minimum Money Required Before Transactions

{leetcode}/problems/minimum-money-required-before-transactions/[LeetCode - 2412. Minimum Money Required Before Transactions ^]

You are given a *0-indexed* 2D integer array `<font face="monospace">transactions`, where `transactions[i] = [cost<sub>i</sub>, cashback<sub>i</sub>]`.

The array describes transactions, where each transaction must be completed exactly once in *some order*. At any given moment, you have a certain amount of `money`. In order to complete transaction `i`, `money >= cost<sub>i</sub>` must hold true. After performing a transaction, `money` becomes `money - cost<sub>i</sub> + cashback<sub>i</sub>`.

Return_ the minimum amount of _`money`_ required before any transaction so that all of the transactions can be completed *regardless of the order* of the transactions._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* transactions = [[2,1],[5,0],[4,2]]
*Output:* 10
*Explanation:
*Starting with money = 10, the transactions can be performed in any order.
It can be shown that starting with money < 10 will fail to complete all transactions in some order.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* transactions = [[3,0],[0,3]]
*Output:* 3
*Explanation:*
- If transactions are in the order [[3,0],[0,3]], the minimum money required to complete the transactions is 3.
- If transactions are in the order [[0,3],[3,0]], the minimum money required to complete the transactions is 0.
Thus, starting with money = 3, the transactions can be performed in any order.
----

 
*Constraints:*


* `1 <= transactions.length <= 10^5^`
* `transactions[i].length == 2`
* `0 <= cost<sub>i</sub>, cashback<sub>i</sub> <= 10^9^`




== 思路分析


[[src-2412]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2412_MinimumMoneyRequiredBeforeTransactions.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2412_MinimumMoneyRequiredBeforeTransactions_2.java[tag=answer]
// ----
// --
====


== 参考资料


