[#2414-length-of-the-longest-alphabetical-continuous-substring]
= 2414. Length of the Longest Alphabetical Continuous Substring

{leetcode}/problems/length-of-the-longest-alphabetical-continuous-substring/[LeetCode - 2414. Length of the Longest Alphabetical Continuous Substring ^]

An *alphabetical continuous string* is a string consisting of consecutive letters in the alphabet. In other words, it is any substring of the string `"abcdefghijklmnopqrstuvwxyz"`.


* For example, `"abc"` is an alphabetical continuous string, while `"acb"` and `"za"` are not.


Given a string `s` consisting of lowercase letters only, return the _length of the *longest* alphabetical continuous substring._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "abacaba"
*Output:* 2
*Explanation:* There are 4 distinct continuous substrings: "a", "b", "c" and "ab".
"ab" is the longest continuous substring.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcde"
*Output:* 5
*Explanation:* "abcde" is the longest continuous substring.
----

 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consists of only English lowercase letters.




== 思路分析


[[src-2414]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2414_LengthOfTheLongestAlphabeticalContinuousSubstring.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2414_LengthOfTheLongestAlphabeticalContinuousSubstring_2.java[tag=answer]
// ----
// --
====


== 参考资料


