[#2423-remove-letter-to-equalize-frequency]
= 2423. Remove Letter To Equalize Frequency

https://leetcode.com/problems/remove-letter-to-equalize-frequency/[LeetCode - 2423. Remove Letter To Equalize Frequency ^]

You are given a *0-indexed* string `word`, consisting of lowercase English letters. You need to select *one* index and *remove* the letter at that index from `word` so that the *frequency* of every letter present in `word` is equal.

Return_ _`true`_ if it is possible to remove one letter so that the frequency of all letters in _`word`_ are equal, and _`false`_ otherwise_.

*Note:*


* The *frequency* of a letter `x` is the number of times it occurs in the string.
* You *must* remove exactly one letter and cannot choose to do nothing.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* word = "abcc"
*Output:* true
*Explanation:* Select index 3 and delete it: word becomes "abc" and each character has a frequency of 1.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* word = "aazz"
*Output:* false
*Explanation:* We must delete a character, so either the frequency of "a" is 1 and the frequency of "z" is 2, or vice versa. It is impossible to make all present letters have equal frequency.
----

 
*Constraints:*


* `2 <= word.length <= 100`
* `word` consists of lowercase English letters only.




== 思路分析


[[src-2423]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2423_RemoveLetterToEqualizeFrequency.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2423_RemoveLetterToEqualizeFrequency_2.java[tag=answer]
// ----
// --
====


== 参考资料


