[#2432-the-employee-that-worked-on-the-longest-task]
= 2432. The Employee That Worked on the Longest Task

https://leetcode.com/problems/the-employee-that-worked-on-the-longest-task/[LeetCode - 2432. The Employee That Worked on the Longest Task ^]

There are `n` employees, each with a unique id from `0` to `n - 1`.

You are given a 2D integer array `logs` where `logs[i] = [id<sub>i</sub>, leaveTime<sub>i</sub>]` where:


* `id<sub>i</sub>` is the id of the employee that worked on the `i^th^` task, and
* `leaveTime<sub>i</sub>` is the time at which the employee finished the `i^th^` task. All the values `leaveTime<sub>i</sub>` are *unique*.


Note that the `i^th^` task starts the moment right after the `(i - 1)^th^` task ends, and the `0^th^` task starts at time `0`.

Return _the id of the employee that worked the task with the longest time._ If there is a tie between two or more employees, return_ the *smallest* id among them_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 10, logs = [[0,3],[2,5],[0,9],[1,15]]
*Output:* 1
*Explanation:* 
Task 0 started at 0 and ended at 3 with 3 units of times.
Task 1 started at 3 and ended at 5 with 2 units of times.
Task 2 started at 5 and ended at 9 with 4 units of times.
Task 3 started at 9 and ended at 15 with 6 units of times.
The task with the longest time is task 3 and the employee with id 1 is the one that worked on it, so we return 1.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 26, logs = [[1,1],[3,7],[2,12],[7,17]]
*Output:* 3
*Explanation:* 
Task 0 started at 0 and ended at 1 with 1 unit of times.
Task 1 started at 1 and ended at 7 with 6 units of times.
Task 2 started at 7 and ended at 12 with 5 units of times.
Task 3 started at 12 and ended at 17 with 5 units of times.
The tasks with the longest time is task 1. The employee that worked on it is 3, so we return 3.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* n = 2, logs = [[0,10],[1,20]]
*Output:* 0
*Explanation:* 
Task 0 started at 0 and ended at 10 with 10 units of times.
Task 1 started at 10 and ended at 20 with 10 units of times.
The tasks with the longest time are tasks 0 and 1. The employees that worked on them are 0 and 1, so we return the smallest id 0.
----

 
*Constraints:*


* `2 <= n <= 500`
* `1 <= logs.length <= 500`
* `logs[i].length == 2`
* `0 <= id<sub>i</sub> <= n - 1`
* `1 <= leaveTime<sub>i</sub> <= 500`
* `id<sub>i</sub> != id<sub>i+1</sub>`
* `leaveTime<sub>i</sub>` are sorted in a strictly increasing order.




== 思路分析


[[src-2432]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2432_TheEmployeeThatWorkedOnTheLongestTask.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2432_TheEmployeeThatWorkedOnTheLongestTask_2.java[tag=answer]
// ----
// --
====


== 参考资料


