[#2437-number-of-valid-clock-times]
= 2437. Number of Valid Clock Times

{leetcode}/problems/number-of-valid-clock-times/[LeetCode - 2437. Number of Valid Clock Times ^]

You are given a string of length `5` called `time`, representing the current time on a digital clock in the format `"hh:mm"`. The *earliest* possible time is `"00:00"` and the *latest* possible time is `"23:59"`.

In the string `time`, the digits represented by the `?` symbol are *unknown*, and must be *replaced* with a digit from `0` to `9`.

Return_ an integer _`answer`_, the number of valid clock times that can be created by replacing every _`?`_ with a digit from _`0`_ to _`9`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* time = "?5:00"
*Output:* 2
*Explanation:* We can replace the ? with either a 0 or 1, producing "05:00" or "15:00". Note that we cannot replace it with a 2, since the time "25:00" is invalid. In total, we have two choices.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* time = "0?:0?"
*Output:* 100
*Explanation:* Each ? can be replaced by any digit from 0 to 9, so we have 100 total choices.
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* time = "??:??"
*Output:* 1440
*Explanation:* There are 24 possible choices for the hours, and 60 possible choices for the minutes. In total, we have 24 * 60 = 1440 choices.
----

 
*Constraints:*


* `time` is a valid string of length `5` in the format `"hh:mm"`.
* `"00" <= hh <= "23"`
* `"00" <= mm <= "59"`
* Some of the digits might be replaced with `'?'` and need to be replaced with digits from `0` to `9`.




== 思路分析


[[src-2437]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2437_NumberOfValidClockTimes.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2437_NumberOfValidClockTimes_2.java[tag=answer]
// ----
// --
====


== 参考资料


