[#2438-range-product-queries-of-powers]
= 2438. Range Product Queries of Powers

{leetcode}/problems/range-product-queries-of-powers/[LeetCode - 2438. Range Product Queries of Powers ^]

Given a positive integer `n`, there exists a *0-indexed* array called `powers`, composed of the *minimum* number of powers of `2` that sum to `n`. The array is sorted in *non-decreasing* order, and there is *only one* way to form the array.

You are also given a *0-indexed* 2D integer array `queries`, where `queries[i] = [left<sub>i</sub>, right<sub>i</sub>]`. Each `queries[i]` represents a query where you have to find the product of all `powers[j]` with `left<sub>i</sub> <= j <= right<sub>i</sub>`.

Return_ an array _`answers`_, equal in length to _`queries`_, where _`answers[i]`_ is the answer to the _`i^th^`_ query_. Since the answer to the `i^th^` query may be too large, each `answers[i]` should be returned *modulo* `10^9^ + 7`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 15, queries = [[0,1],[2,2],[0,3]]
*Output:* [2,4,64]
*Explanation:*
For n = 15, powers = [1,2,4,8]. It can be shown that powers cannot be a smaller size.
Answer to 1st query: powers[0] * powers[1] = 1 * 2 = 2.
Answer to 2nd query: powers[2] = 4.
Answer to 3rd query: powers[0] * powers[1] * powers[2] * powers[3] = 1 * 2 * 4 * 8 = 64.
Each answer modulo 10^9^ + 7 yields the same answer, so [2,4,64] is returned.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 2, queries = [[0,0]]
*Output:* [2]
*Explanation:*
For n = 2, powers = [2].
The answer to the only query is powers[0] = 2. The answer modulo 10^9^ + 7 is the same, so [2] is returned.
----

 
*Constraints:*


* `1 <= n <= 10^9^`
* `1 <= queries.length <= 10^5^`
* `0 <= start<sub>i</sub> <= end<sub>i</sub> < powers.length`




== 思路分析


[[src-2438]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2438_RangeProductQueriesOfPowers.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2438_RangeProductQueriesOfPowers_2.java[tag=answer]
// ----
// --
====


== 参考资料


