[#2446-determine-if-two-events-have-conflict]
= 2446. Determine if Two Events Have Conflict

https://leetcode.com/problems/determine-if-two-events-have-conflict/[LeetCode - 2446. Determine if Two Events Have Conflict ^]

You are given two arrays of strings that represent two inclusive events that happened *on the same day*, `event1` and `event2`, where:


* `event1 = [startTime<sub>1</sub>, endTime<sub>1</sub>]` and
* `event2 = [startTime<sub>2</sub>, endTime<sub>2</sub>]`.


Event times are valid 24 hours format in the form of `HH:MM`.

A *conflict* happens when two events have some non-empty intersection (i.e., some moment is common to both events).

Return `true`_ if there is a conflict between two events. Otherwise, return _`false`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* event1 = ["01:15","02:00"], event2 = ["02:00","03:00"]
*Output:* true
*Explanation:* The two events intersect at time 2:00.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* event1 = ["01:00","02:00"], event2 = ["01:20","03:00"]
*Output:* true
*Explanation:* The two events intersect starting from 01:20 to 02:00.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* event1 = ["10:00","11:00"], event2 = ["14:00","15:00"]
*Output:* false
*Explanation:* The two events do not intersect.
----

 
*Constraints:*


* `event1.length == event2.length == 2`
* `event1[i].length == event2[i].length == 5`
* `startTime<sub>1</sub> <= endTime<sub>1</sub>`
* `startTime<sub>2</sub> <= endTime<sub>2</sub>`
* All the event times follow the `HH:MM` format.




== 思路分析


[[src-2446]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2446_DetermineIfTwoEventsHaveConflict.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2446_DetermineIfTwoEventsHaveConflict_2.java[tag=answer]
// ----
// --
====


== 参考资料


