[#2456-most-popular-video-creator]
= 2456. Most Popular Video Creator

{leetcode}/problems/most-popular-video-creator/[LeetCode - 2456. Most Popular Video Creator ^]

You are given two string arrays `creators` and `ids`, and an integer array `views`, all of length `n`. The `i^th^` video on a platform was created by `creator[i]`, has an id of `ids[i]`, and has `views[i]` views.

The *popularity* of a creator is the *sum* of the number of views on *all* of the creator's videos. Find the creator with the *highest* popularity and the id of their *most* viewed video.


* If multiple creators have the highest popularity, find all of them.
* If multiple videos have the highest view count for a creator, find the lexicographically *smallest* id.


Return_ a 2D array of strings _`answer`_ where _`answer[i] = [creator<sub>i</sub>, id<sub>i</sub>]`_ means that _`creator<sub>i</sub>` _has the *highest* popularity and _`id<sub>i</sub>`_ is the id of their most popular video._ The answer can be returned in any order.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* creators = ["alice","bob","alice","chris"], ids = ["one","two","three","four"], views = [5,10,5,4]
*Output:* [["alice","one"],["bob","two"]]
*Explanation:*
The popularity of alice is 5 + 5 = 10.
The popularity of bob is 10.
The popularity of chris is 4.
alice and bob are the most popular creators.
For bob, the video with the highest view count is "two".
For alice, the videos with the highest view count are "one" and "three". Since "one" is lexicographically smaller than "three", it is included in the answer.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* creators = ["alice","alice","alice"], ids = ["a","b","c"], views = [1,2,2]
*Output:* [["alice","b"]]
*Explanation:*
The videos with id "b" and "c" have the highest view count.
Since "b" is lexicographically smaller than "c", it is included in the answer.
----

 
*Constraints:*


* `n == creators.length == ids.length == views.length`
* `1 <= n <= 10^5^`
* `1 <= creators[i].length, ids[i].length <= 5`
* `creators[i]` and `ids[i]` consist only of lowercase English letters.
* `0 <= views[i] <= 10^5^`




== 思路分析


[[src-2456]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2456_MostPopularVideoCreator.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2456_MostPopularVideoCreator_2.java[tag=answer]
// ----
// --
====


== 参考资料


