[#2466-count-ways-to-build-good-strings]
= 2466. Count Ways To Build Good Strings

{leetcode}/problems/count-ways-to-build-good-strings/[LeetCode - 2466. Count Ways To Build Good Strings ^]

Given the integers `zero`, `one`, `low`, and `high`, we can construct a string by starting with an empty string, and then at each step perform either of the following:


* Append the character `'0'` `zero` times.
* Append the character `'1'` `one` times.


This can be performed any number of times.

A *good* string is a string constructed by the above process having a *length* between `low` and `high` (*inclusive*).

Return _the number of *different* good strings that can be constructed satisfying these properties._ Since the answer can be large, return it *modulo* `10^9^ + 7`.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* low = 3, high = 3, zero = 1, one = 1
*Output:* 8
*Explanation:* 
One possible valid good string is "011". 
It can be constructed as follows: "" -> "0" -> "01" -> "011". 
All binary strings from "000" to "111" are good strings in this example.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* low = 2, high = 3, zero = 1, one = 2
*Output:* 5
*Explanation:* The good strings are "00", "11", "000", "110", and "011".
----

 
*Constraints:*


* `1 <= low <= high <= 10^5^`
* `1 <= zero, one <= low`




== 思路分析


[[src-2466]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2466_CountWaysToBuildGoodStrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2466_CountWaysToBuildGoodStrings_2.java[tag=answer]
// ----
// --
====


== 参考资料


