[#2472-maximum-number-of-non-overlapping-palindrome-substrings]
= 2472. Maximum Number of Non-overlapping Palindrome Substrings

{leetcode}/problems/maximum-number-of-non-overlapping-palindrome-substrings/[LeetCode - 2472. Maximum Number of Non-overlapping Palindrome Substrings ^]

You are given a string `s` and a *positive* integer `k`.

Select a set of *non-overlapping* substrings from the string `s` that satisfy the following conditions:


* The *length* of each substring is *at least* `k`.
* Each substring is a *palindrome*.


Return _the *maximum* number of substrings in an optimal selection_.

A *substring* is a contiguous sequence of characters within a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "abaccdbbd", k = 3
*Output:* 2
*Explanation:* We can select the substrings underlined in s = "[.underline]#*aba*#cc[.underline]#*dbbd*#". Both "aba" and "dbbd" are palindromes and have a length of at least k = 3.
It can be shown that we cannot find a selection with more than two valid substrings.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "adbcda", k = 2
*Output:* 0
*Explanation:* There is no palindrome substring of length at least 2 in the string.
----

 
*Constraints:*


* `1 <= k <= s.length <= 2000`
* `s` consists of lowercase English letters.




== 思路分析


[[src-2472]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2472_MaximumNumberOfNonOverlappingPalindromeSubstrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2472_MaximumNumberOfNonOverlappingPalindromeSubstrings_2.java[tag=answer]
// ----
// --
====


== 参考资料


