[#2490-circular-sentence]
= 2490. Circular Sentence

{leetcode}/problems/circular-sentence/[LeetCode - 2490. Circular Sentence ^]

A *sentence* is a list of words that are separated by a* single* space with no leading or trailing spaces.


* For example, `"Hello World"`, `"HELLO"`, `"hello world hello world"` are all sentences.


Words consist of *only* uppercase and lowercase English letters. Uppercase and lowercase English letters are considered different.

A sentence is *circular *if:


* The last character of a word is equal to the first character of the next word.
* The last character of the last word is equal to the first character of the first word.


For example, `"leetcode exercises sound delightful"`, `"eetcode"`, `"leetcode eats soul" `are all circular sentences. However, `"Leetcode is cool"`, `"happy Leetcode"`, `"Leetcode"` and `"I like Leetcode"` are *not* circular sentences.

Given a string `sentence`, return `true`_ if it is circular_. Otherwise, return `false`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "leetcode exercises sound delightful"
*Output:* true
*Explanation:* The words in sentence are ["leetcode", "exercises", "sound", "delightful"].
- leetcod[.underline]#e#'s last character is equal to [.underline]#e#xercises's first character.
- exercise[.underline]#s#'s last character is equal to [.underline]#s#ound's first character.
- soun[.underline]#d#'s last character is equal to [.underline]#d#elightful's first character.
- delightfu[.underline]#l#'s last character is equal to [.underline]#l#eetcode's first character.
The sentence is circular.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "eetcode"
*Output:* true
*Explanation:* The words in sentence are ["eetcode"].
- eetcod[.underline]#e#'s last character is equal to [.underline]#e#etcode's first character.
The sentence is circular.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* sentence = "Leetcode is cool"
*Output:* false
*Explanation:* The words in sentence are ["Leetcode", "is", "cool"].
- Leetcod[.underline]#e#'s last character is *not* equal to [.underline]#i#s's first character.
The sentence is *not* circular.
----

 
*Constraints:*


* `1 <= sentence.length <= 500`
* `sentence` consist of only lowercase and uppercase English letters and spaces.
* The words in `sentence` are separated by a single space.
* There are no leading or trailing spaces.




== 思路分析


[[src-2490]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2490_CircularSentence.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2490_CircularSentence_2.java[tag=answer]
// ----
// --
====


== 参考资料


