[#2523-closest-prime-numbers-in-range]
= 2523. Closest Prime Numbers in Range

{leetcode}/problems/closest-prime-numbers-in-range/[LeetCode - 2523. Closest Prime Numbers in Range ^]

Given two positive integers `left` and `right`, find the two integers `num1` and `num2` such that:


* `left <= num1 < num2 <= right `.
* `num1` and `num2` are both *prime* numbers.
* `num2 - num1` is the *minimum* amongst all other pairs satisfying the above conditions.


Return _the positive integer array_ `ans = [num1, num2]`. _If there are multiple pairs satisfying these conditions, return the one with the minimum_ `num1` _value or_ `[-1, -1]` _if such numbers do not exist._

A number greater than `1` is called *prime* if it is only divisible by `1` and itself.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* left = 10, right = 19
*Output:* [11,13]
*Explanation:* The prime numbers between 10 and 19 are 11, 13, 17, and 19.
The closest gap between any pair is 2, which can be achieved by [11,13] or [17,19].
Since 11 is smaller than 17, we return the first pair.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* left = 4, right = 6
*Output:* [-1,-1]
*Explanation:* There exists only one prime number in the given range, so the conditions cannot be satisfied.
----

 
*Constraints:*


* `1 <= left <= right <= 10^6^`


 
<style type="text/css">.spoilerbutton {display:block; border:dashed; padding: 0px 0px; margin:10px 0px; font-size:150%; font-weight: bold; color:#000000; background-color:cyan; outline:0; 
}
.spoiler {overflow:hidden;}
.spoiler > div {-webkit-transition: all 0s ease;-moz-transition: margin 0s ease;-o-transition: all 0s ease;transition: margin 0s ease;}
.spoilerbutton[value="Show Message"] + .spoiler > div {margin-top:-500%;}
.spoilerbutton[value="Hide Message"] + .spoiler {padding:5px;}
</style>



== 思路分析


[[src-2523]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2523_ClosestPrimeNumbersInRange.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2523_ClosestPrimeNumbersInRange_2.java[tag=answer]
// ----
// --
====


== 参考资料


