[#2573-find-the-string-with-lcp]
= 2573. Find the String with LCP

https://leetcode.com/problems/find-the-string-with-lcp/[LeetCode - 2573. Find the String with LCP ^]

We define the `lcp` matrix of any *0-indexed* string `word` of `n` lowercase English letters as an `n x n` grid such that:


* `lcp[i][j]` is equal to the length of the *longest common prefix* between the substrings `word[i,n-1]` and `word[j,n-1]`.


Given an `n x n` matrix `lcp`, return the alphabetically smallest string `word` that corresponds to `lcp`. If there is no such string, return an empty string.

A string `a` is lexicographically smaller than a string `b` (of the same length) if in the first position where `a` and `b` differ, string `a` has a letter that appears earlier in the alphabet than the corresponding letter in `b`. For example, `"aabd"` is lexicographically smaller than `"aaca"` because the first position they differ is at the third letter, and `'b'` comes before `'c'`.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* lcp = [[4,0,2,0],[0,3,0,1],[2,0,2,0],[0,1,0,1]]
*Output:* "abab"
*Explanation:* lcp corresponds to any 4 letter string with two alternating letters. The lexicographically smallest of them is "abab".
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* lcp = [[4,3,2,1],[3,3,2,1],[2,2,2,1],[1,1,1,1]]
*Output:* "aaaa"
*Explanation:* lcp corresponds to any 4 letter string with a single distinct letter. The lexicographically smallest of them is "aaaa". 
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* lcp = [[4,3,2,1],[3,3,2,1],[2,2,2,1],[1,1,1,3]]
*Output:* ""
*Explanation:* lcp[3][3] cannot be equal to 3 since word[3,...,3] consists of only a single letter; Thus, no answer exists.
----

 
*Constraints:*


* `1 <= n == ``lcp.length == ``lcp[i].length` `<= 1000`
* `<font face="monospace">0 <= lcp[i][j] <= n`




== 思路分析


[[src-2573]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2573_FindTheStringWithLcp.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2573_FindTheStringWithLcp_2.java[tag=answer]
// ----
// --
====


== 参考资料


