[#2582-pass-the-pillow]
= 2582. Pass the Pillow

{leetcode}/problems/pass-the-pillow/[LeetCode - 2582. Pass the Pillow ^]

There are `n` people standing in a line labeled from `1` to `n`. The first person in the line is holding a pillow initially. Every second, the person holding the pillow passes it to the next person standing in the line. Once the pillow reaches the end of the line, the direction changes, and people continue passing the pillow in the opposite direction.


* For example, once the pillow reaches the `n^th^` person they pass it to the `n - 1^th^` person, then to the `n - 2^th^` person and so on.


Given the two positive integers `n` and `time`, return _the index of the person holding the pillow after _`time`_ seconds_.
 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 4, time = 5
*Output:* 2
*Explanation:* People pass the pillow in the following way: 1 -> 2 -> 3 -> 4 -> 3 -> 2.
After five seconds, the 2^nd^ person is holding the pillow.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, time = 2
*Output:* 3
*Explanation:* People pass the pillow in the following way: 1 -> 2 -> 3.
After two seconds, the 3^r^^d^ person is holding the pillow.
----

 
*Constraints:*


* `2 <= n <= 1000`
* `1 <= time <= 1000`




== 思路分析


[[src-2582]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2582_PassThePillow.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2582_PassThePillow_2.java[tag=answer]
// ----
// --
====


== 参考资料


