[#2609-find-the-longest-balanced-substring-of-a-binary-string]
= 2609. Find the Longest Balanced Substring of a Binary String

{leetcode}/problems/find-the-longest-balanced-substring-of-a-binary-string/[LeetCode - 2609. Find the Longest Balanced Substring of a Binary String ^]

You are given a binary string `s` consisting only of zeroes and ones.

A substring of `s` is considered balanced if* all zeroes are before ones* and the number of zeroes is equal to the number of ones inside the substring. Notice that the empty substring is considered a balanced substring.

Return _the length of the longest balanced substring of _`s`.

A *substring* is a contiguous sequence of characters within a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "01000111"
*Output:* 6
*Explanation:* The longest balanced substring is "000111", which has length 6.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "00111"
*Output:* 4
*Explanation:* The longest balanced substring is "0011", which has length 4. 
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "111"
*Output:* 0
*Explanation:* There is no balanced substring except the empty substring, so the answer is 0.
----

 
*Constraints:*


* `1 <= s.length <= 50`
* `'0' <= s[i] <= '1'`




== 思路分析


[[src-2609]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2609_FindTheLongestBalancedSubstringOfABinaryString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2609_FindTheLongestBalancedSubstringOfABinaryString_2.java[tag=answer]
// ----
// --
====


== 参考资料


