[#2654-minimum-number-of-operations-to-make-all-array-elements-equal-to-1]
= 2654. Minimum Number of Operations to Make All Array Elements Equal to 1

{leetcode}/problems/minimum-number-of-operations-to-make-all-array-elements-equal-to-1/[LeetCode - 2654. Minimum Number of Operations to Make All Array Elements Equal to 1 ^]

You are given a *0-indexed* array `nums` consisiting of *positive* integers. You can do the following operation on the array *any* number of times:


* Select an index `i` such that `0 <= i < n - 1` and replace either of `nums[i]` or `nums[i+1]` with their gcd value.


Return _the *minimum* number of operations to make all elements of _`nums`_ equal to _`1`. If it is impossible, return `-1`.

The gcd of two integers is the greatest common divisor of the two integers.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,6,3,4]
*Output:* 4
*Explanation:* We can do the following operations:
- Choose index i = 2 and replace nums[2] with gcd(3,4) = 1. Now we have nums = [2,6,1,4].
- Choose index i = 1 and replace nums[1] with gcd(6,1) = 1. Now we have nums = [2,1,1,4].
- Choose index i = 0 and replace nums[0] with gcd(2,1) = 1. Now we have nums = [1,1,1,4].
- Choose index i = 2 and replace nums[3] with gcd(1,4) = 1. Now we have nums = [1,1,1,1].
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,10,6,14]
*Output:* -1
*Explanation:* It can be shown that it is impossible to make all the elements equal to 1.
----

 
*Constraints:*


* `2 <= nums.length <= 50`
* `1 <= nums[i] <= 10^6^`




== 思路分析


[[src-2654]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2654_MinimumNumberOfOperationsToMakeAllArrayElementsEqualTo1.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2654_MinimumNumberOfOperationsToMakeAllArrayElementsEqualTo1_2.java[tag=answer]
// ----
// --
====


== 参考资料


