[#2660-determine-the-winner-of-a-bowling-game]
= 2660. Determine the Winner of a Bowling Game

https://leetcode.com/problems/determine-the-winner-of-a-bowling-game/[LeetCode - 2660. Determine the Winner of a Bowling Game ^]

You are given two *0-indexed* integer arrays `<font face="monospace">player1` and `player2`, representing the number of pins that player 1 and player 2 hit in a bowling game, respectively.

The bowling game consists of `n` turns, and the number of pins in each turn is exactly 10.

Assume a player hits `x<sub>i</sub>` pins in the i^th^ turn. The value of the i^th^ turn for the player is:


* `2x<sub>i</sub>` if the player hits 10 pins *in either (i - 1)^th^ or (i - 2)^th^ turn*.
* Otherwise, it is `x<sub>i</sub>`.


The *score* of the player is the sum of the values of their `n` turns.

Return


* 1 if the score of player 1 is more than the score of player 2,
* 2 if the score of player 2 is more than the score of player 1, and
* 0 in case of a draw.


 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">player1 = [5,10,3,2], player2 = [6,5,7,3]

*Output:* <span class="example-io">1

*Explanation:*

The score of player 1 is 5 + 10 + 2*3 + 2*2 = 25.

The score of player 2 is 6 + 5 + 7 + 3 = 21.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">player1 = [3,5,7,6], player2 = [8,10,10,2]

*Output:* <span class="example-io">2

*Explanation:*

The score of player 1 is 3 + 5 + 7 + 6 = 21.

The score of player 2 is 8 + 10 + 2*10 + 2*2 = 42.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">player1 = [2,3], player2 = [4,1]

*Output:* <span class="example-io">0

*Explanation:*

The score of player1 is 2 + 3 = 5.

The score of player2 is 4 + 1 = 5.


<strong class="example">Example 4:*

<div class="example-block">
*Input:* <span class="example-io">player1 = [1,1,1,10,10,10,10], player2 = [10,10,10,10,1,1,1]

*Output:* <span class="example-io">2

*Explanation:*

The score of player1 is 1 + 1 + 1 + 10 + 2*10 + 2*10 + 2*10 = 73.

The score of player2 is 10 + 2*10 + 2*10 + 2*10 + 2*1 + 2*1 + 1 = 75.


 
*Constraints:*


* `n == player1.length == player2.length`
* `1 <= n <= 1000`
* `0 <= player1[i], player2[i] <= 10`




== 思路分析


[[src-2660]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2660_DetermineTheWinnerOfABowlingGame.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2660_DetermineTheWinnerOfABowlingGame_2.java[tag=answer]
// ----
// --
====


== 参考资料


