[#2662-minimum-cost-of-a-path-with-special-roads]
= 2662. Minimum Cost of a Path With Special Roads

{leetcode}/problems/minimum-cost-of-a-path-with-special-roads/[LeetCode - 2662. Minimum Cost of a Path With Special Roads ^]

You are given an array `start` where `start = [startX, startY]` represents your initial position `(startX, startY)` in a 2D space. You are also given the array `target` where `target = [targetX, targetY]` represents your target position `(targetX, targetY)`.

The *cost* of going from a position `(x1, y1)` to any other position in the space `(x2, y2)` is `|x2 - x1| + |y2 - y1|`.

There are also some *special roads*. You are given a 2D array `specialRoads` where `specialRoads[i] = [x1<sub>i</sub>, y1<sub>i</sub>, x2<sub>i</sub>, y2<sub>i</sub>, cost<sub>i</sub>]` indicates that the `i^th^` special road goes in *one direction* from `(x1<sub>i</sub>, y1<sub>i</sub>)` to `(x2<sub>i</sub>, y2<sub>i</sub>)` with a cost equal to `cost<sub>i</sub>`. You can use each special road any number of times.

Return the *minimum* cost required to go from `(startX, startY)` to `(targetX, targetY)`.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">start = [1,1], target = [4,5], specialRoads = [[1,2,3,3,2],[3,4,4,5,1]]

*Output:* <span class="example-io">5

*Explanation:*


* (1,1) to (1,2) with a cost of |1 - 1| + |2 - 1| = 1.
* (1,2) to (3,3). Use `<span class="example-io">specialRoads[0]`<span class="example-io"> with<span class="example-io"> the cost 2.
* <span class="example-io">(3,3) to (3,4) with a cost of |3 - 3| + |4 - 3| = 1.
* <span class="example-io">(3,4) to (4,5). Use `<span class="example-io">specialRoads[1]`<span class="example-io"> with the cost<span class="example-io"> 1.


<span class="example-io">So the total cost is 1 + 2 + 1 + 1 = 5.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">start = [3,2], target = [5,7], specialRoads = [[5,7,3,2,1],[3,2,3,4,4],[3,3,5,5,5],[3,4,5,6,6]]

*Output:* <span class="example-io">7

*Explanation:*

It is optimal not to use any special edges and go directly from the starting to the ending position with a cost |5 - 3| + |7 - 2| = 7.

Note that the <span class="example-io">`specialRoads[0]` is directed from (5,7) to (3,2).


*Example 3:*

<div class="example-block">
*Input:* <span class="example-io">start = [1,1], target = [10,4], specialRoads = [[4,2,1,1,3],[1,2,7,4,4],[10,3,6,1,2],[6,1,1,2,3]]

*Output:* <span class="example-io">8

*Explanation:*


* (1,1) to (1,2) with a cost of |1 - 1| + |2 - 1| = 1.
* (1,2) to (7,4). Use `<span class="example-io">specialRoads[1]`<span class="example-io"> with the cost<span class="example-io"> 4.
* (7,4) to (10,4) with a cost of |10 - 7| + |4 - 4| = 3.



 
*Constraints:*


* `start.length == target.length == 2`
* `1 <= startX <= targetX <= 10^5^`
* `1 <= startY <= targetY <= 10^5^`
* `1 <= specialRoads.length <= 200`
* `specialRoads[i].length == 5`
* `startX <= x1<sub>i</sub>, x2<sub>i</sub> <= targetX`
* `startY <= y1<sub>i</sub>, y2<sub>i</sub> <= targetY`
* `1 <= cost<sub>i</sub> <= 10^5^`




== 思路分析


[[src-2662]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2662_MinimumCostOfAPathWithSpecialRoads.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2662_MinimumCostOfAPathWithSpecialRoads_2.java[tag=answer]
// ----
// --
====


== 参考资料


