[#2663-lexicographically-smallest-beautiful-string]
= 2663. Lexicographically Smallest Beautiful String

https://leetcode.com/problems/lexicographically-smallest-beautiful-string/[LeetCode - 2663. Lexicographically Smallest Beautiful String ^]

A string is *beautiful* if:


* It consists of the first `k` letters of the English lowercase alphabet.
* It does not contain any substring of length `2` or more which is a palindrome.


You are given a beautiful string `s` of length `n` and a positive integer `k`.

Return _the lexicographically smallest string of length _`n`_, which is larger than _`s`_ and is *beautiful*_. If there is no such string, return an empty string.

A string `a` is lexicographically larger than a string `b` (of the same length) if in the first position where `a` and `b` differ, `a` has a character strictly larger than the corresponding character in `b`.


* For example, `"abcd"` is lexicographically larger than `"abcc"` because the first position they differ is at the fourth character, and `d` is greater than `c`.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcz", k = 26
*Output:* "abda"
*Explanation:* The string "abda" is beautiful and lexicographically larger than the string "abcz".
It can be proven that there is no string that is lexicographically larger than the string "abcz", beautiful, and lexicographically smaller than the string "abda".
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "dc", k = 4
*Output:* ""
*Explanation:* It can be proven that there is no string that is lexicographically larger than the string "dc" and is beautiful.
----

 
*Constraints:*


* `1 <= n == s.length <= 10^5^`
* `4 <= k <= 26`
* `s` is a beautiful string.




== 思路分析


[[src-2663]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2663_LexicographicallySmallestBeautifulString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2663_LexicographicallySmallestBeautifulString_2.java[tag=answer]
// ----
// --
====


== 参考资料


