[#2672-number-of-adjacent-elements-with-the-same-color]
= 2672. Number of Adjacent Elements With the Same Color

{leetcode}/problems/number-of-adjacent-elements-with-the-same-color/[LeetCode - 2672. Number of Adjacent Elements With the Same Color ^]

You are given an integer `n` representing an array `colors` of length `n` where all elements are set to 0's meaning *uncolored*. You are also given a 2D integer array `queries` where `queries[i] = [index<sub>i</sub>, color<sub>i</sub>]`. For the `i^th^` *query*:


* Set `colors[index<sub>i</sub>]` to `color<sub>i</sub>`.
* Count adjacent pairs in `colors` set to the same color (regardless of `color<sub>i</sub>`).


Return an array `answer` of the same length as `queries` where `answer[i]` is the answer to the `i^th^` query.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">n = 4, queries = [[0,2],[1,2],[3,1],[1,1],[2,1]]

*Output:* <span class="example-io">[0,1,1,0,2]

*Explanation:*


* Initially array colors = [0,0,0,0], where 0 denotes uncolored elements of the array.
* After the 1^st^ query colors = [2,0,0,0]. The count of adjacent pairs with the same color is 0.
* After the 2^nd^ query colors = [2,2,0,0]. The count of adjacent pairs with the same color is 1.
* After the 3^rd^ query colors = [2,2,0,1]. The count of adjacent pairs with the same color is 1.
* After the 4^th^ query colors = [2,1,0,1]. The count of adjacent pairs with the same color is 0.
* After the 5^th^ query colors = [2,1,1,1]. The count of adjacent pairs with the same color is 2.



*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">n = 1, queries = [[0,100000]]

*Output:* <span class="example-io">[0]

*Explanation:*

After the 1^st^ query colors = [100000]. The count of adjacent pairs with the same color is 0.


 
*Constraints:*


* `1 <= n <= 10^5^`
* `1 <= queries.length <= 10^5^`
* `queries[i].length == 2`
* `0 <= index<sub>i</sub> <= n - 1`
* `1 <=  color<sub>i</sub> <= 10^5^`




== 思路分析


[[src-2672]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2672_NumberOfAdjacentElementsWithTheSameColor.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2672_NumberOfAdjacentElementsWithTheSameColor_2.java[tag=answer]
// ----
// --
====


== 参考资料


