[#2683-neighboring-bitwise-xor]
= 2683. Neighboring Bitwise XOR

https://leetcode.com/problems/neighboring-bitwise-xor/[LeetCode - 2683. Neighboring Bitwise XOR ^]

A *0-indexed* array `derived` with length `n` is derived by computing the *bitwise XOR* (&oplus;) of adjacent values in a *binary array* `original` of length `n`.

Specifically, for each index `i` in the range `[0, n - 1]`:


* If `i = n - 1`, then `derived[i] = original[i] &oplus; original[0]`.
* Otherwise, `derived[i] = original[i] &oplus; original[i + 1]`.


Given an array `derived`, your task is to determine whether there exists a *valid binary array* `original` that could have formed `derived`.

Return _*true* if such an array exists or *false* otherwise._


* A binary array is an array containing only *0's* and *1's*


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* derived = [1,1,0]
*Output:* true
*Explanation:* A valid original array that gives derived is [0,1,0].
derived[0] = original[0] &oplus; original[1] = 0 &oplus; 1 = 1 
derived[1] = original[1] &oplus; original[2] = 1 &oplus; 0 = 1
derived[2] = original[2] &oplus; original[0] = 0 &oplus; 0 = 0
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* derived = [1,1]
*Output:* true
*Explanation:* A valid original array that gives derived is [0,1].
derived[0] = original[0] &oplus; original[1] = 1
derived[1] = original[1] &oplus; original[0] = 1
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* derived = [1,0]
*Output:* false
*Explanation:* There is no valid original array that gives derived.
----

 
*Constraints:*


* `n == derived.length`
* `1 <= n <= 10^5^`
* The values in `derived` are either *0's* or *1's*




== 思路分析


[[src-2683]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2683_NeighboringBitwiseXor.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2683_NeighboringBitwiseXor_2.java[tag=answer]
// ----
// --
====


== 参考资料


