[#2697-lexicographically-smallest-palindrome]
= 2697. Lexicographically Smallest Palindrome

{leetcode}/problems/lexicographically-smallest-palindrome/[LeetCode - 2697. Lexicographically Smallest Palindrome ^]

You are given a string <code node="[object Object]">s` consisting of *lowercase English letters*, and you are allowed to perform operations on it. In one operation, you can *replace* a character in <code node="[object Object]">s` with another lowercase English letter.

Your task is to make <code node="[object Object]">s` a *palindrome* with the *minimum* *number* *of operations* possible. If there are *multiple palindromes* that can be <meta charset="utf-8" />made using the *minimum* number of operations, <meta charset="utf-8" />make the *lexicographically smallest* one.

A string `a` is lexicographically smaller than a string `b` (of the same length) if in the first position where `a` and `b` differ, string `a` has a letter that appears earlier in the alphabet than the corresponding letter in `b`.

Return _the resulting palindrome string._

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "egcfe"
*Output:* "efcfe"
*Explanation:* The minimum number of operations to make "egcfe" a palindrome is 1, and the lexicographically smallest palindrome string we can get by modifying one character is "efcfe", by changing 'g'.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcd"
*Output:* "abba"
*Explanation:* The minimum number of operations to make "abcd" a palindrome is 2, and the lexicographically smallest palindrome string we can get by modifying two characters is "abba".
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "seven"
*Output:* "neven"
*Explanation:* The minimum number of operations to make "seven" a palindrome is 1, and the lexicographically smallest palindrome string we can get by modifying one character is "neven".
----

 
*Constraints:*


* `1 <= s.length <= 1000`
* `s` consists of only lowercase English letters*.*




== 思路分析


[[src-2697]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2697_LexicographicallySmallestPalindrome.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2697_LexicographicallySmallestPalindrome_2.java[tag=answer]
// ----
// --
====


== 参考资料


