[#2716-minimize-string-length]
= 2716. Minimize String Length

https://leetcode.com/problems/minimize-string-length/[LeetCode - 2716. Minimize String Length ^]

Given a string `s`, you have two types of operation:


* Choose an index `i` in the string, and let `c` be the character in position `i`. *Delete* the *closest occurrence* of `c` to the *left* of `i` (if exists).
* Choose an index `i` in the string, and let `c` be the character in position `i`. *Delete* the *closest occurrence* of `c` to the *right* of `i` (if exists).


Your task is to *minimize* the length of `s` by performing the above operations zero or more times.

Return an integer denoting the length of the *minimized* string.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "aaabc"

*Output:* <span class="example-io">3

*Explanation:*


* Operation 2: we choose `i = 1` so `c` is 'a', then we remove `s[2]` as it is closest 'a' character to the right of `s[1]`.


	`s` becomes "aabc" after this.
* Operation 1: we choose `i = 1` so `c` is 'a', then we remove `s[0]` as it is closest 'a' character to the left of `s[1]`.


	`s` becomes "abc" after this.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "cbbd"

*Output:* <span class="example-io">3

*Explanation:*


* Operation 1: we choose `i = 2` so `c` is 'b', then we remove `s[1]` as it is closest 'b' character to the left of `s[1]`.


	`s` becomes "cbd" after this.



<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">s = "baadccab"

*Output:* 4

*Explanation:*


* Operation 1: we choose `i = 6` so `c` is 'a', then we remove `s[2]` as it is closest 'a' character to the left of `s[6]`.


	`s` becomes "badccab" after this.
* Operation 2: we choose `i = 0` so `c` is 'b', then we remove `s[6]` as it is closest 'b' character to the right of `s[0]`.


	`s` becomes "badcca" fter this.
* Operation 2: we choose `i = 3` so `c` is 'c', then we remove `s[4]` as it is closest 'c' character to the right of `s[3]`.


	`s` becomes "badca" after this.
* Operation 1: we choose `i = 4` so `c` is 'a', then we remove `s[1]` as it is closest 'a' character to the left of `s[4]`.


	`s` becomes "bdca" after this.



 
*Constraints:*


* `1 <= s.length <= 100`
* `s` contains only lowercase English letters




== 思路分析


[[src-2716]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2716_MinimizeStringLength.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2716_MinimizeStringLength_2.java[tag=answer]
// ----
// --
====


== 参考资料


