[#2734-lexicographically-smallest-string-after-substring-operation]
= 2734. Lexicographically Smallest String After Substring Operation

{leetcode}/problems/lexicographically-smallest-string-after-substring-operation/[LeetCode - 2734. Lexicographically Smallest String After Substring Operation ^]

Given a string `s` consisting of lowercase English letters. Perform the following operation:


* Select any non-empty <span data-keyword="substring-nonempty">substring then replace every letter of the substring with the preceding letter of the English alphabet. For example, 'b' is converted to 'a', and 'a' is converted to 'z'.


Return the <span data-keyword="lexicographically-smaller-string">*lexicographically smallest* string *after performing the operation*.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "cbabc"

*Output:* <span class="example-io">"baabc"

*Explanation:*

Perform the operation on the substring starting at index 0, and ending at index 1 inclusive.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "aa"

*Output:* <span class="example-io">"az"

*Explanation:*

Perform the operation on the last letter.


*Example 3:*

<div class="example-block">
*Input:* <span class="example-io">s = "acbbc"

*Output:* <span class="example-io">"abaab"

*Explanation:*

Perform the operation on the substring starting at index 1, and ending at index 4 inclusive.


*Example 4:*

<div class="example-block">
*Input:* <span class="example-io">s = "leetcode"

*Output:* <span class="example-io">"kddsbncd"

*Explanation:*

Perform the operation on the entire string.


 
*Constraints:*


* `1 <= s.length <= 3 * 10^5^`
* `s` consists of lowercase English letters




== 思路分析


[[src-2734]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2734_LexicographicallySmallestStringAfterSubstringOperation.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2734_LexicographicallySmallestStringAfterSubstringOperation_2.java[tag=answer]
// ----
// --
====


== 参考资料


