[#2760-longest-even-odd-subarray-with-threshold]
= 2760. Longest Even Odd Subarray With Threshold

{leetcode}/problems/longest-even-odd-subarray-with-threshold/[LeetCode - 2760. Longest Even Odd Subarray With Threshold ^]

You are given a *0-indexed* integer array `nums` and an integer `threshold`.

Find the length of the *longest subarray* of `nums` starting at index `l` and ending at index `r` `(0 <= l <= r < nums.length)` that satisfies the following conditions:


* `nums[l] % 2 == 0`
* For all indices `i` in the range `[l, r - 1]`, `nums[i] % 2 != nums[i + 1] % 2`
* For all indices `i` in the range `[l, r]`, `nums[i] <= threshold`


Return _an integer denoting the length of the longest such subarray._

*Note:* A *subarray* is a contiguous non-empty sequence of elements within an array.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [3,2,5,4], threshold = 5
*Output:* 3
*Explanation:* In this example, we can select the subarray that starts at l = 1 and ends at r = 3 => [2,5,4]. This subarray satisfies the conditions.
Hence, the answer is the length of the subarray, 3. We can show that 3 is the maximum possible achievable length.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2], threshold = 2
*Output:* 1
*Explanation:* In this example, we can select the subarray that starts at l = 1 and ends at r = 1 => [2]. 
It satisfies all the conditions and we can show that 1 is the maximum possible achievable length.

----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,3,4,5], threshold = 4
*Output:* 3
*Explanation:* In this example, we can select the subarray that starts at l = 0 and ends at r = 2 => [2,3,4]. 
It satisfies all the conditions.
Hence, the answer is the length of the subarray, 3. We can show that 3 is the maximum possible achievable length.

----

 
*Constraints:*


* `1 <= nums.length <= 100 `
* `1 <= nums[i] <= 100 `
* `1 <= threshold <= 100`




== 思路分析


[[src-2760]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2760_LongestEvenOddSubarrayWithThreshold.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2760_LongestEvenOddSubarrayWithThreshold_2.java[tag=answer]
// ----
// --
====


== 参考资料


