[#2800-shortest-string-that-contains-three-strings]
= 2800. 包含三个字符串的最短字符串

https://leetcode.cn/problems/shortest-string-that-contains-three-strings/[LeetCode - 2800. 包含三个字符串的最短字符串 ^]

给你三个字符串 `a` ，`b` 和 `c`，你的任务是找到长度 *最短* 的字符串，且这三个字符串都是它的 *子字符串* 。

如果有多个这样的字符串，请你返回 *字典序最小* 的一个。

请你返回满足题目要求的字符串。

*注意：*

* 两个长度相同的字符串 `a` 和 `b` ，如果在第一个不相同的字符处，`a` 的字母在字母表中比 `b` 的字母 *靠前* ，那么字符串 `a` 比字符串 `b` *字典序小* 。
* *子字符串* 是一个字符串中一段连续的字符序列。

*示例 1：*

....
输入：a = "abc", b = "bca", c = "aaa"
输出："aaabca"
解释：字符串 "aaabca" 包含所有三个字符串：a = ans[2...4] ，b = ans[3..5] ，c = ans[0..2] 。结果字符串的长度至少为 6 ，且"aaabca" 是字典序最小的一个。
....

*示例 2：*

....
输入：a = "ab", b = "ba", c = "aba"
输出："aba"
解释：字符串 "aba" 包含所有三个字符串：a = ans[0..1] ，b = ans[1..2] ，c = ans[0..2] 。由于 c 的长度为 3 ，结果字符串的长度至少为 3 。"aba" 是字典序最小的一个。
....

*提示：*

* `+1 <= a.length, b.length, c.length <= 100+`
* `a` ，`b` ，`c` 只包含小写英文字母。


== 思路分析

先使用回溯获取三个字符串的所有全排列，然后在这些全排列中，通过合并字符串首尾相同的部分来获取更短的子串，在这些子串中选择最短，字典排序最小的字符串。

NOTE: 合并字符串时，注意处理首尾的相同子串。

最初思路是直接合并三个字符，这样会因为没有处理“首尾相同”的子串而让结果变长。


[[src-2800]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2800_ShortestStringThatContainsThreeStrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2800_ShortestStringThatContainsThreeStrings_2.java[tag=answer]
// ----
// --
====


== 参考资料

. https://leetcode.cn/problems/shortest-string-that-contains-three-strings/solutions/2364733/mei-ju-by-endlesscheng-qc44/[2800. 包含三个字符串的最短字符串 - 枚举^]
