[#2800-shortest-string-that-contains-three-strings]
= 2800. Shortest String That Contains Three Strings

{leetcode}/problems/shortest-string-that-contains-three-strings/[LeetCode - 2800. Shortest String That Contains Three Strings ^]

Given three strings `a`, `b`, and `c`, your task is to find a string that has the* minimum* length and contains all three strings as *substrings*.
If there are multiple such strings, return the_ _*lexicographically_ _smallest *one.

Return _a string denoting the answer to the problem._

*Notes*


* A string `a` is *lexicographically smaller* than a string `b` (of the same length) if in the first position where `a` and `b` differ, string `a` has a letter that appears *earlier *in the alphabet than the corresponding letter in `b`.
* A *substring* is a contiguous sequence of characters within a string.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* a = "abc", b = "bca", c = "aaa"
*Output:* "aaabca"
*Explanation:*  We show that "aaabca" contains all the given strings: a = ans[2...4], b = ans[3..5], c = ans[0..2]. It can be shown that the length of the resulting string would be at least 6 and "aaabca" is the lexicographically smallest one.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* a = "ab", b = "ba", c = "aba"
*Output:* "aba"
*Explanation: *We show that the string "aba" contains all the given strings: a = ans[0..1], b = ans[1..2], c = ans[0..2]. Since the length of c is 3, the length of the resulting string would be at least 3. It can be shown that "aba" is the lexicographically smallest one.

----

 
*Constraints:*


* `1 <= a.length, b.length, c.length <= 100`
* `a`, `b`, `c` consist only of lowercase English letters.




== 思路分析


[[src-2800]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2800_ShortestStringThatContainsThreeStrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2800_ShortestStringThatContainsThreeStrings_2.java[tag=answer]
// ----
// --
====


== 参考资料


