[#2839-check-if-strings-can-be-made-equal-with-operations-i]
= 2839. Check if Strings Can be Made Equal With Operations I

{leetcode}/problems/check-if-strings-can-be-made-equal-with-operations-i/[LeetCode - 2839. Check if Strings Can be Made Equal With Operations I ^]

You are given two strings `s1` and `s2`, both of length `4`, consisting of *lowercase* English letters.

You can apply the following operation on any of the two strings *any* number of times:


* Choose any two indices `i` and `j` such that `j - i = 2`, then *swap* the two characters at those indices in the string.


Return `true`_ if you can make the strings _`s1`_ and _`s2`_ equal, and _`false`_ otherwise_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "abcd", s2 = "cdab"
*Output:* true
*Explanation:* We can do the following operations on s1:
- Choose the indices i = 0, j = 2. The resulting string is s1 = "cbad".
- Choose the indices i = 1, j = 3. The resulting string is s1 = "cdab" = s2.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "abcd", s2 = "dacb"
*Output:* false
*Explanation:* It is not possible to make the two strings equal.
----

 
*Constraints:*


* `s1.length == s2.length == 4`
* `s1` and `s2` consist only of lowercase English letters.




== 思路分析


[[src-2839]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2839_CheckIfStringsCanBeMadeEqualWithOperationsI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2839_CheckIfStringsCanBeMadeEqualWithOperationsI_2.java[tag=answer]
// ----
// --
====


== 参考资料


