[#2840-check-if-strings-can-be-made-equal-with-operations-ii]
= 2840. Check if Strings Can be Made Equal With Operations II

{leetcode}/problems/check-if-strings-can-be-made-equal-with-operations-ii/[LeetCode - 2840. Check if Strings Can be Made Equal With Operations II ^]

You are given two strings `s1` and `s2`, both of length `n`, consisting of *lowercase* English letters.

You can apply the following operation on *any* of the two strings *any* number of times:


* Choose any two indices `i` and `j` such that `i < j` and the difference `j - i` is *even*, then *swap* the two characters at those indices in the string.


Return `true`_ if you can make the strings _`s1`_ and _`s2`_ equal, and _`false`_ otherwise_.

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "abcdba", s2 = "cabdab"
*Output:* true
*Explanation:* We can apply the following operations on s1:
- Choose the indices i = 0, j = 2. The resulting string is s1 = "cbadba".
- Choose the indices i = 2, j = 4. The resulting string is s1 = "cbbdaa".
- Choose the indices i = 1, j = 5. The resulting string is s1 = "cabdab" = s2.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s1 = "abe", s2 = "bea"
*Output:* false
*Explanation:* It is not possible to make the two strings equal.
----

 
*Constraints:*


* `n == s1.length == s2.length`
* `1 <= n <= 10^5^`
* `s1` and `s2` consist only of lowercase English letters.




== 思路分析


[[src-2840]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2840_CheckIfStringsCanBeMadeEqualWithOperationsIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2840_CheckIfStringsCanBeMadeEqualWithOperationsIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


