[#2842-count-k-subsequences-of-a-string-with-maximum-beauty]
= 2842. Count K-Subsequences of a String With Maximum Beauty

{leetcode}/problems/count-k-subsequences-of-a-string-with-maximum-beauty/[LeetCode - 2842. Count K-Subsequences of a String With Maximum Beauty ^]

You are given a string `s` and an integer `k`.

A *k-subsequence* is a *subsequence* of `s`, having length `k`, and all its characters are *unique*, *i.e*., every character occurs once.

Let `f(c)` denote the number of times the character `c` occurs in `s`.

The *beauty* of a *k-subsequence* is the *sum* of `f(c)` for every character `c` in the k-subsequence.

For example, consider `s = "abbbdd"` and `k = 2`:


* `f('a') = 1`, `f('b') = 3`, `f('d') = 2`
* Some k-subsequences of `s` are:
	
	* `"[.underline]#*ab*#bbdd"` -> `"ab"` having a beauty of `f('a') + f('b') = 4`
	* `"[.underline]#*a*#bbb*[.underline]#d#*d"` -> `"ad"` having a beauty of `f('a') + f('d') = 3`
	* `"a*[.underline]#b#*bb[.underline]#*d*#d"` -> `"bd"` having a beauty of `f('b') + f('d') = 5`
	
	


Return _an integer denoting the number of k-subsequences __whose *beauty* is the *maximum* among all *k-subsequences*_. Since the answer may be too large, return it modulo `10^9^ + 7`.

A subsequence of a string is a new string formed from the original string by deleting some (possibly none) of the characters without disturbing the relative positions of the remaining characters.

*Notes*


* `f(c)` is the number of times a character `c` occurs in `s`, not a k-subsequence.
* Two k-subsequences are considered different if one is formed by an index that is not present in the other. So, two k-subsequences may form the same string.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "bcca", k = 2
*Output:* 4
*Explanation:* <span style="white-space: normal">From s we have f('a') = 1, f('b') = 1, and f('c') = 2.
The k-subsequences of s are: 
*[.underline]#bc#*ca having a beauty of f('b') + f('c') = 3 
*[.underline]#b#*c[.underline]#*c*#a having a beauty of f('b') + f('c') = 3 
*[.underline]#b#*cc*[.underline]#a#* having a beauty of f('b') + f('a') = 2 
b*[.underline]#c#*c[.underline]#*a*#* *having a beauty of f('c') + f('a') = 3
bc*[.underline]#ca#* having a beauty of f('c') + f('a') = 3 
There are 4 k-subsequences that have the maximum beauty, 3. 
Hence, the answer is 4. 
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abbcd", k = 4
*Output:* 2
*Explanation:* From s we have f('a') = 1, f('b') = 2, f('c') = 1, and f('d') = 1. 
The k-subsequences of s are: 
[.underline]#*ab*#b*[.underline]#cd#* having a beauty of f('a') + f('b') + f('c') + f('d') = 5
<u style="white-space: normal;">*a*#b[.underline]#*bcd*# having a beauty of f('a') + f('b') + f('c') + f('d') = 5 
There are 2 k-subsequences that have the maximum beauty, 5. 
Hence, the answer is 2. 
----

 
*Constraints:*


* `1 <= s.length <= 2 * 10^5^`
* `1 <= k <= s.length`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-2842]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2842_CountKSubsequencesOfAStringWithMaximumBeauty.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2842_CountKSubsequencesOfAStringWithMaximumBeauty_2.java[tag=answer]
// ----
// --
====


== 参考资料


