[#2865-beautiful-towers-i]
= 2865. Beautiful Towers I

{leetcode}/problems/beautiful-towers-i/[LeetCode - 2865. Beautiful Towers I ^]

You are given an array `heights` of `n` integers representing the number of bricks in `n` consecutive towers. Your task is to remove some bricks to form a *mountain-shaped* tower arrangement. In this arrangement, the tower heights are non-decreasing, reaching a maximum peak value with one or multiple consecutive towers and then non-increasing.

Return the *maximum possible sum* of heights of a mountain-shaped tower arrangement.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">heights = [5,3,4,1,1]

*Output:* <span class="example-io">13

*Explanation:*

We remove some bricks to make `heights = [5,3,3,1,1]`, the peak is at index 0.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">heights = [6,5,3,9,2,7]

*Output:* <span class="example-io">22

*Explanation:*

We remove some bricks to make `heights = [3,3,3,9,2,2]`, the peak is at index 3.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">heights = [3,2,5,5,2,3]

*Output:* <span class="example-io">18

*Explanation:*

We remove some bricks to make `heights = [2,2,5,5,2,2]`, the peak is at index 2 or 3.


 
*Constraints:*


* `1 <= n == heights <= 10^3^`
* `1 <= heights[i] <= 10^9^`




== 思路分析


[[src-2865]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2865_BeautifulTowersI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2865_BeautifulTowersI_2.java[tag=answer]
// ----
// --
====


== 参考资料


