[#2900-longest-unequal-adjacent-groups-subsequence-i]
= 2900. Longest Unequal Adjacent Groups Subsequence I

{leetcode}/problems/longest-unequal-adjacent-groups-subsequence-i/[LeetCode - 2900. Longest Unequal Adjacent Groups Subsequence I ^]

You are given a string array `words` and a *binary* array `groups` both of length `n`, where `words[i]` is associated with `groups[i]`.

Your task is to select the *longest alternating* <span data-keyword="subsequence-array">subsequence from `words`. A subsequence of `words` is alternating if for any two consecutive strings in the sequence, their corresponding elements in the binary array `groups` differ. Essentially, you are to choose strings such that adjacent elements have non-matching corresponding bits in the `groups` array.

Formally, you need to find the longest subsequence of an array of indices `[0, 1, ..., n - 1]` denoted as `[i<sub>0</sub>, i<sub>1</sub>, ..., i<sub>k-1</sub>]`, such that `groups[i<sub>j</sub>] != groups[i<sub>j+1</sub>]` for each `0 <= j < k - 1` and then find the words corresponding to these indices.

Return _the selected subsequence. If there are multiple answers, return *any* of them._

*Note:* The elements in `words` are distinct.

 
*Example 1:*

<div class="example-block" style="
    border-color: var(--border-tertiary);
    border-left-width: 2px;
    color: var(--text-secondary);
    font-size: .875rem;
    margin-bottom: 1rem;
    margin-top: 1rem;
    overflow: visible;
    padding-left: 1rem;
">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">words = ["e","a","b"], groups = [0,0,1]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">["e","b"]

*Explanation:* A subsequence that can be selected is `["e","b"]` because `groups[0] != groups[2]`. Another subsequence that can be selected is `["a","b"]` because `groups[1] != groups[2]`. It can be demonstrated that the length of the longest subsequence of indices that satisfies the condition is `2`.


*Example 2:*

<div class="example-block" style="
    border-color: var(--border-tertiary);
    border-left-width: 2px;
    color: var(--text-secondary);
    font-size: .875rem;
    margin-bottom: 1rem;
    margin-top: 1rem;
    overflow: visible;
    padding-left: 1rem;
">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">words = ["a","b","c","d"], groups = [1,0,1,1]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">["a","b","c"]

*Explanation:* A subsequence that can be selected is `["a","b","c"]` because `groups[0] != groups[1]` and `groups[1] != groups[2]`. Another subsequence that can be selected is `["a","b","d"]` because `groups[0] != groups[1]` and `groups[1] != groups[3]`. It can be shown that the length of the longest subsequence of indices that satisfies the condition is `3`.


 
*Constraints:*


* `1 <= n == words.length == groups.length <= 100`
* `1 <= words[i].length <= 10`
* `groups[i]` is either `0` or `1.`
* `words` consists of *distinct* strings.
* `words[i]` consists of lowercase English letters.




== 思路分析


[[src-2900]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2900_LongestUnequalAdjacentGroupsSubsequenceI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2900_LongestUnequalAdjacentGroupsSubsequenceI_2.java[tag=answer]
// ----
// --
====


== 参考资料


