[#2905-find-indices-with-index-and-value-difference-ii]
= 2905. Find Indices With Index and Value Difference II

{leetcode}/problems/find-indices-with-index-and-value-difference-ii/[LeetCode - 2905. Find Indices With Index and Value Difference II ^]

You are given a *0-indexed* integer array `nums` having length `n`, an integer `indexDifference`, and an integer `valueDifference`.

Your task is to find *two* indices `i` and `j`, both in the range `[0, n - 1]`, that satisfy the following conditions:


* `abs(i - j) >= indexDifference`, and
* `abs(nums[i] - nums[j]) >= valueDifference`


Return _an integer array_ `answer`, _where_ `answer = [i, j]` _if there are two such indices_, _and_ `answer = [-1, -1]` _otherwise_. If there are multiple choices for the two indices, return _any of them_.

*Note:* `i` and `j` may be *equal*.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [5,1,4,1], indexDifference = 2, valueDifference = 4
*Output:* [0,3]
*Explanation:* In this example, i = 0 and j = 3 can be selected.
abs(0 - 3) >= 2 and abs(nums[0] - nums[3]) >= 4.
Hence, a valid answer is [0,3].
[3,0] is also a valid answer.

----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [2,1], indexDifference = 0, valueDifference = 0
*Output:* [0,0]
*Explanation:* In this example, i = 0 and j = 0 can be selected.
abs(0 - 0) >= 0 and abs(nums[0] - nums[0]) >= 0.
Hence, a valid answer is [0,0].
Other valid answers are [0,1], [1,0], and [1,1].

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3], indexDifference = 2, valueDifference = 4
*Output:* [-1,-1]
*Explanation:* In this example, it can be shown that it is impossible to find two indices that satisfy both conditions.
Hence, [-1,-1] is returned.
----

 
*Constraints:*


* `1 <= n == nums.length <= 10^5^`
* `0 <= nums[i] <= 10^9^`
* `0 <= indexDifference <= 10^5^`
* `0 <= valueDifference <= 10^9^`




== 思路分析


[[src-2905]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2905_FindIndicesWithIndexAndValueDifferenceIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2905_FindIndicesWithIndexAndValueDifferenceIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


