[#2926-maximum-balanced-subsequence-sum]
= 2926. Maximum Balanced Subsequence Sum

https://leetcode.com/problems/maximum-balanced-subsequence-sum/[LeetCode - 2926. Maximum Balanced Subsequence Sum ^]

You are given a *0-indexed* integer array `nums`.

A *subsequence* of `nums` having length `k` and consisting of *indices* `i<sub>0</sub> < i<sub>1</sub> < ... < i<sub>k-1</sub>` is *balanced* if the following holds:


* `nums[i<sub>j</sub>] - nums[i<sub>j-1</sub>] >= i<sub>j</sub> - i<sub>j-1</sub>`, for every `j` in the range `[1, k - 1]`.


A *subsequence* of `nums` having length `1` is considered balanced.

Return _an integer denoting the *maximum* possible *sum of elements* in a *balanced* subsequence of _`nums`.

A *subsequence* of an array is a new *non-empty* array that is formed from the original array by deleting some (*possibly none*) of the elements without disturbing the relative positions of the remaining elements.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [3,3,5,6]
*Output:* 14
*Explanation:* In this example, the subsequence [3,5,6] consisting of indices 0, 2, and 3 can be selected.
nums[2] - nums[0] >= 2 - 0.
nums[3] - nums[2] >= 3 - 2.
Hence, it is a balanced subsequence, and its sum is the maximum among the balanced subsequences of nums.
The subsequence consisting of indices 1, 2, and 3 is also valid.
It can be shown that it is not possible to get a balanced subsequence with a sum greater than 14.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [5,-1,-3,8]
*Output:* 13
*Explanation:* In this example, the subsequence [5,8] consisting of indices 0 and 3 can be selected.
nums[3] - nums[0] >= 3 - 0.
Hence, it is a balanced subsequence, and its sum is the maximum among the balanced subsequences of nums.
It can be shown that it is not possible to get a balanced subsequence with a sum greater than 13.

----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [-2,-1]
*Output:* -1
*Explanation:* In this example, the subsequence [-1] can be selected.
It is a balanced subsequence, and its sum is the maximum among the balanced subsequences of nums.

----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `-10^9^ <= nums[i] <= 10^9^`




== 思路分析


[[src-2926]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2926_MaximumBalancedSubsequenceSum.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2926_MaximumBalancedSubsequenceSum_2.java[tag=answer]
// ----
// --
====


== 参考资料


