[#2953-count-complete-substrings]
= 2953. Count Complete Substrings

{leetcode}/problems/count-complete-substrings/[LeetCode - 2953. Count Complete Substrings ^]

You are given a string `word` and an integer `k`.

A substring `s` of `word` is *complete* if:


* Each character in `s` occurs *exactly* `k` times.
* The difference between two adjacent characters is *at most* `2`. That is, for any two adjacent characters `c1` and `c2` in `s`, the absolute difference in their positions in the alphabet is *at most* `2`.


Return _the number of *complete *substrings of_ `word`.

A *substring* is a *non-empty* contiguous sequence of characters in a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* word = "igigee", k = 2
*Output:* 3
*Explanation:* The complete substrings where each character appears exactly twice and the difference between adjacent characters is at most 2 are: [.underline]#*igig*#ee, igig[.underline]#*ee*#, [.underline]#*igigee*#.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* word = "aaabbbccc", k = 3
*Output:* 6
*Explanation:* The complete substrings where each character appears exactly three times and the difference between adjacent characters is at most 2 are: *[.underline]#aaa#*bbbccc, aaa[.underline]#*bbb*#ccc, aaabbb[.underline]#*ccc*#, *[.underline]#aaabbb#*ccc, aaa[.underline]#*bbbccc*#, [.underline]#*aaabbbccc*#.
----

 
*Constraints:*


* `1 <= word.length <= 10^5^`
* `word` consists only of lowercase English letters.
* `1 <= k <= word.length`




== 思路分析


[[src-2953]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2953_CountCompleteSubstrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2953_CountCompleteSubstrings_2.java[tag=answer]
// ----
// --
====


== 参考资料


