[#2972-count-the-number-of-incremovable-subarrays-ii]
= 2972. Count the Number of Incremovable Subarrays II

{leetcode}/problems/count-the-number-of-incremovable-subarrays-ii/[LeetCode - 2972. Count the Number of Incremovable Subarrays II ^]

You are given a *0-indexed* array of *positive* integers `nums`.

A subarray of `nums` is called *incremovable* if `nums` becomes *strictly increasing* on removing the subarray. For example, the subarray `[3, 4]` is an incremovable subarray of `[5, 3, 4, 6, 7]` because removing this subarray changes the array `[5, 3, 4, 6, 7]` to `[5, 6, 7]` which is strictly increasing.

Return _the total number of *incremovable* subarrays of_ `nums`.

*Note* that an empty array is considered strictly increasing.

A *subarray* is a contiguous non-empty sequence of elements within an array.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,2,3,4]
*Output:* 10
*Explanation:* The 10 incremovable subarrays are: [1], [2], [3], [4], [1,2], [2,3], [3,4], [1,2,3], [2,3,4], and [1,2,3,4], because on removing any one of these subarrays nums becomes strictly increasing. Note that you cannot select an empty subarray.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [6,5,7,8]
*Output:* 7
*Explanation:* The 7 incremovable subarrays are: [5], [6], [5,7], [6,5], [5,7,8], [6,5,7] and [6,5,7,8].
It can be shown that there are only 7 incremovable subarrays in nums.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [8,7,6,6]
*Output:* 3
*Explanation:* The 3 incremovable subarrays are: [8,7,6], [7,6,6], and [8,7,6,6]. Note that [8,7] is not an incremovable subarray because after removing [8,7] nums becomes [6,6], which is sorted in ascending order but not strictly increasing.
----

 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^9^`




== 思路分析


[[src-2972]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2972_CountTheNumberOfIncremovableSubarraysIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2972_CountTheNumberOfIncremovableSubarraysIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


