[#2981-find-longest-special-substring-that-occurs-thrice-i]
= 2981. Find Longest Special Substring That Occurs Thrice I

https://leetcode.com/problems/find-longest-special-substring-that-occurs-thrice-i/[LeetCode - 2981. Find Longest Special Substring That Occurs Thrice I ^]

You are given a string `s` that consists of lowercase English letters.

A string is called *special* if it is made up of only a single character. For example, the string `"abc"` is not special, whereas the strings `"ddd"`, `"zz"`, and `"f"` are special.

Return _the length of the *longest special substring* of _`s` _which occurs *at least thrice*_, _or _`-1`_ if no special substring occurs at least thrice_.

A *substring* is a contiguous *non-empty* sequence of characters within a string.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "aaaa"
*Output:* 2
*Explanation:* The longest special substring which occurs thrice is "aa": substrings "[.underline]#*aa*#aa", "a[.underline]#*aa*#a", and "aa[.underline]#*aa*#".
It can be shown that the maximum length achievable is 2.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcdef"
*Output:* -1
*Explanation:* There exists no special substring which occurs at least thrice. Hence return -1.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcaba"
*Output:* 1
*Explanation:* The longest special substring which occurs thrice is "a": substrings "[.underline]#*a*#bcaba", "abc[.underline]#*a*#ba", and "abcab[.underline]#*a*#".
It can be shown that the maximum length achievable is 1.
----

 
*Constraints:*


* `3 <= s.length <= 50`
* `s` consists of only lowercase English letters.




== 思路分析


[[src-2981]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2981_FindLongestSpecialSubstringThatOccursThriceI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2981_FindLongestSpecialSubstringThatOccursThriceI_2.java[tag=answer]
// ----
// --
====


== 参考资料


