[#2983-palindrome-rearrangement-queries]
= 2983. Palindrome Rearrangement Queries

{leetcode}/problems/palindrome-rearrangement-queries/[LeetCode - 2983. Palindrome Rearrangement Queries ^]

You are given a *0-indexed* string `s` having an *even* length `n`.

You are also given a *0-indexed* 2D integer array, `queries`, where `queries[i] = [a<sub>i</sub>, b<sub>i</sub>, c<sub>i</sub>, d<sub>i</sub>]`.

For each query `i`, you are allowed to perform the following operations:


* Rearrange the characters within the *substring* `s[a<sub>i</sub>:b<sub>i</sub>]`, where `0 <= a<sub>i</sub> <= b<sub>i</sub> < n / 2`.
* Rearrange the characters within the *substring* `s[c<sub>i</sub>:d<sub>i</sub>]`, where `n / 2 <= c<sub>i</sub> <= d<sub>i</sub> < n`.


For each query, your task is to determine whether it is possible to make `s` a *palindrome* by performing the operations.

Each query is answered *independently* of the others.

Return _a *0-indexed* array _`answer`_, where _`answer[i] == true`_ if it is possible to make _`s`_ a palindrome by performing operations specified by the _`i^th^`_ query, and _`false`_ otherwise._


* A *substring* is a contiguous sequence of characters within a string.
* `s[x:y]` represents the substring consisting of characters from the index `x` to index `y` in `s`, *both inclusive*.


 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* s = "abcabc", queries = [[1,1,3,5],[0,2,5,5]]
*Output:* [true,true]
*Explanation:* In this example, there are two queries:
In the first query:
- a<sub>0</sub> = 1, b<sub>0</sub> = 1, c<sub>0</sub> = 3, d<sub>0</sub> = 5.
- So, you are allowed to rearrange s[1:1] => a[.underline]#b#cabc and s[3:5] => abc[.underline]#abc#.
- To make s a palindrome, s[3:5] can be rearranged to become => abc[.underline]#cba#.
- Now, s is a palindrome. So, answer[0] = true.
In the second query:
- a<sub>1</sub> = 0, b<sub>1</sub> = 2, c<sub>1</sub> = 5, d<sub>1</sub> = 5.
- So, you are allowed to rearrange s[0:2] => [.underline]#abc#abc and s[5:5] => abcab[.underline]#c#.
- To make s a palindrome, s[0:2] can be rearranged to become => [.underline]#cba#abc.
- Now, s is a palindrome. So, answer[1] = true.

----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* s = "abbcdecbba", queries = [[0,2,7,9]]
*Output:* [false]
*Explanation:* In this example, there is only one query.
a<sub>0</sub> = 0, b<sub>0</sub> = 2, c<sub>0</sub> = 7, d<sub>0</sub> = 9.
So, you are allowed to rearrange s[0:2] => [.underline]#abb#cdecbba and s[7:9] => abbcdec[.underline]#bba#.
It is not possible to make s a palindrome by rearranging these substrings because s[3:6] is not a palindrome.
So, answer[0] = false.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* s = "acbcab", queries = [[1,2,4,5]]
*Output:* [true]
*Explanation: *In this example, there is only one query.
a<sub>0</sub> = 1, b<sub>0</sub> = 2, c<sub>0</sub> = 4, d<sub>0</sub> = 5.
So, you are allowed to rearrange s[1:2] => a[.underline]#cb#cab and s[4:5] => acbc[.underline]#ab#.
To make s a palindrome s[1:2] can be rearranged to become a[.underline]#bc#cab.
Then, s[4:5] can be rearranged to become abcc[.underline]#ba#.
Now, s is a palindrome. So, answer[0] = true.
----

 
*Constraints:*


* `2 <= n == s.length <= 10^5^`
* `1 <= queries.length <= 10^5^`
* `queries[i].length == 4`
* `a<sub>i</sub> == queries[i][0], b<sub>i</sub> == queries[i][1]`
* `c<sub>i</sub> == queries[i][2], d<sub>i</sub> == queries[i][3]`
* `0 <= a<sub>i</sub> <= b<sub>i</sub> < n / 2`
* `n / 2 <= c<sub>i</sub> <= d<sub>i</sub> < n `
* `n` is even.
* `s` consists of only lowercase English letters.




== 思路分析


[[src-2983]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_2983_PalindromeRearrangementQueries.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_2983_PalindromeRearrangementQueries_2.java[tag=answer]
// ----
// --
====


== 参考资料


