[#3013-divide-an-array-into-subarrays-with-minimum-cost-ii]
= 3013. Divide an Array Into Subarrays With Minimum Cost II

{leetcode}/problems/divide-an-array-into-subarrays-with-minimum-cost-ii/[LeetCode - 3013. Divide an Array Into Subarrays With Minimum Cost II ^]

You are given a *0-indexed* array of integers `nums` of length `n`, and two *positive* integers `k` and `dist`.

The *cost* of an array is the value of its *first* element. For example, the cost of `[1,2,3]` is `1` while the cost of `[3,4,1]` is `3`.

You need to divide `nums` into `k` *disjoint contiguous *<span data-keyword="subarray-nonempty">subarrays, such that the difference between the starting index of the *second* subarray and the starting index of the `kth` subarray should be *less than or equal to* `dist`. In other words, if you divide `nums` into the subarrays `nums[0..(i<sub>1</sub> - 1)], nums[i<sub>1</sub>..(i<sub>2</sub> - 1)], ..., nums[i<sub>k-1</sub>..(n - 1)]`, then `i<sub>k-1</sub> - i<sub>1</sub> <= dist`.

Return _the *minimum* possible sum of the cost of these_ _subarrays_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* nums = [1,3,2,6,4,2], k = 3, dist = 3
*Output:* 5
*Explanation:* The best possible way to divide nums into 3 subarrays is: [1,3], [2,6,4], and [2]. This choice is valid because i<sub>k-1</sub> - i<sub>1</sub> is 5 - 2 = 3 which is equal to dist. The total cost is nums[0] + nums[2] + nums[5] which is 1 + 2 + 2 = 5.
It can be shown that there is no possible way to divide nums into 3 subarrays at a cost lower than 5.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* nums = [10,1,2,2,2,1], k = 4, dist = 3
*Output:* 15
*Explanation:* The best possible way to divide nums into 4 subarrays is: [10], [1], [2], and [2,2,1]. This choice is valid because i<sub>k-1</sub> - i<sub>1</sub> is 3 - 1 = 2 which is less than dist. The total cost is nums[0] + nums[1] + nums[2] + nums[3] which is 10 + 1 + 2 + 2 = 15.
The division [10], [1], [2,2,2], and [1] is not valid, because the difference between i<sub>k-1</sub> and i<sub>1</sub> is 5 - 1 = 4, which is greater than dist.
It can be shown that there is no possible way to divide nums into 4 subarrays at a cost lower than 15.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* nums = [10,8,18,9], k = 3, dist = 1
*Output:* 36
*Explanation:* The best possible way to divide nums into 4 subarrays is: [10], [8], and [18,9]. This choice is valid because i<sub>k-1</sub> - i<sub>1</sub> is 2 - 1 = 1 which is equal to dist.The total cost is nums[0] + nums[1] + nums[2] which is 10 + 8 + 18 = 36.
The division [10], [8,18], and [9] is not valid, because the difference between i<sub>k-1</sub> and i<sub>1</sub> is 3 - 1 = 2, which is greater than dist.
It can be shown that there is no possible way to divide nums into 3 subarrays at a cost lower than 36.
----

 
*Constraints:*


* `3 <= n <= 10^5^`
* `1 <= nums[i] <= 10^9^`
* `3 <= k <= n`
* `k - 2 <= dist <= n - 2`




== 思路分析


[[src-3013]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3013_DivideAnArrayIntoSubarraysWithMinimumCostIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3013_DivideAnArrayIntoSubarraysWithMinimumCostIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


