[#3021-alice-and-bob-playing-flower-game]
= 3021. Alice and Bob Playing Flower Game

https://leetcode.com/problems/alice-and-bob-playing-flower-game/[LeetCode - 3021. Alice and Bob Playing Flower Game ^]

Alice and Bob are playing a turn-based game on a circular field surrounded by flowers. The circle represents the field, and there are `x` flowers in the clockwise direction between Alice and Bob, and `y` flowers in the anti-clockwise direction between them.

The game proceeds as follows:


* Alice takes the first turn.
* In each turn, a player must choose either the clockwise or anti-clockwise direction and pick one flower from that side.
* At the end of the turn, if there are no flowers left at all, the *current* player captures their opponent and wins the game.


Given two integers, `n` and `m`, the task is to compute the number of possible pairs `(x, y)` that satisfy the conditions:


* Alice must win the game according to the described rules.
* The number of flowers `x` in the clockwise direction must be in the range `[1,n]`.
* The number of flowers `y` in the anti-clockwise direction must be in the range `[1,m]`.


Return _the number of possible pairs_ `(x, y)` _that satisfy the conditions mentioned in the statement_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* n = 3, m = 2
*Output:* 3
*Explanation:* The following pairs satisfy conditions described in the statement: (1,2), (3,2), (2,1).
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* n = 1, m = 1
*Output:* 0
*Explanation:* No pairs satisfy the conditions described in the statement.
----

 
*Constraints:*


* `1 <= n, m <= 10^5^`




== 思路分析


[[src-3021]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3021_AliceAndBobPlayingFlowerGame.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3021_AliceAndBobPlayingFlowerGame_2.java[tag=answer]
// ----
// --
====


== 参考资料


