[#3042-count-prefix-and-suffix-pairs-i]
= 3042. Count Prefix and Suffix Pairs I

{leetcode}/problems/count-prefix-and-suffix-pairs-i/[LeetCode - 3042. Count Prefix and Suffix Pairs I ^]

You are given a *0-indexed* string array `words`.

Let's define a *boolean* function `isPrefixAndSuffix` that takes two strings, `str1` and `str2`:


* `isPrefixAndSuffix(str1, str2)` returns `true` if `str1` is *both* a <span data-keyword="string-prefix">prefix and a <span data-keyword="string-suffix">suffix of `str2`, and `false` otherwise.


For example, `isPrefixAndSuffix("aba", "ababa")` is `true` because `"aba"` is a prefix of `"ababa"` and also a suffix, but `isPrefixAndSuffix("abc", "abcd")` is `false`.

Return _an integer denoting the *number* of index pairs _`(i, j)`_ such that _`i < j`_, and _`isPrefixAndSuffix(words[i], words[j])`_ is _`true`_._

 
*Example 1:*

[subs="verbatim,quotes"]
----
*Input:* words = ["a","aba","ababa","aa"]
*Output:* 4
*Explanation:* In this example, the counted index pairs are:
i = 0 and j = 1 because isPrefixAndSuffix("a", "aba") is true.
i = 0 and j = 2 because isPrefixAndSuffix("a", "ababa") is true.
i = 0 and j = 3 because isPrefixAndSuffix("a", "aa") is true.
i = 1 and j = 2 because isPrefixAndSuffix("aba", "ababa") is true.
Therefore, the answer is 4.
----

*Example 2:*

[subs="verbatim,quotes"]
----
*Input:* words = ["pa","papa","ma","mama"]
*Output:* 2
*Explanation:* In this example, the counted index pairs are:
i = 0 and j = 1 because isPrefixAndSuffix("pa", "papa") is true.
i = 2 and j = 3 because isPrefixAndSuffix("ma", "mama") is true.
Therefore, the answer is 2.  
----

*Example 3:*

[subs="verbatim,quotes"]
----
*Input:* words = ["abab","ab"]
*Output:* 0
*Explanation: *In this example, the only valid index pair is i = 0 and j = 1, and isPrefixAndSuffix("abab", "ab") is false.
Therefore, the answer is 0.
----

 
*Constraints:*


* `1 <= words.length <= 50`
* `1 <= words[i].length <= 10`
* `words[i]` consists only of lowercase English letters.




== 思路分析


[[src-3042]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3042_CountPrefixAndSuffixPairsI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3042_CountPrefixAndSuffixPairsI_2.java[tag=answer]
// ----
// --
====


== 参考资料


