[#3074-apple-redistribution-into-boxes]
= 3074. Apple Redistribution into Boxes

{leetcode}/problems/apple-redistribution-into-boxes/[LeetCode - 3074. Apple Redistribution into Boxes ^]

You are given an array `apple` of size `n` and an array `capacity` of size `m`.

There are `n` packs where the `i^th^` pack contains `apple[i]` apples. There are `m` boxes as well, and the `i^th^` box has a capacity of `capacity[i]` apples.

Return _the *minimum* number of boxes you need to select to redistribute these _`n`_ packs of apples into boxes_.

*Note* that, apples from the same pack can be distributed into different boxes.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* apple = [1,3,2], capacity = [4,3,1,5,2]
*Output:* 2
*Explanation:* We will use boxes with capacities 4 and 5.
It is possible to distribute the apples as the total capacity is greater than or equal to the total number of apples.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* apple = [5,5,5], capacity = [2,4,2,7]
*Output:* 4
*Explanation:* We will need to use all the boxes.
----

 
*Constraints:*


* `1 <= n == apple.length <= 50`
* `1 <= m == capacity.length <= 50`
* `1 <= apple[i], capacity[i] <= 50`
* The input is generated such that it's possible to redistribute packs of apples into boxes.




== 思路分析


[[src-3074]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3074_AppleRedistributionIntoBoxes.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3074_AppleRedistributionIntoBoxes_2.java[tag=answer]
// ----
// --
====


== 参考资料


