[#3075-maximize-happiness-of-selected-children]
= 3075. Maximize Happiness of Selected Children

{leetcode}/problems/maximize-happiness-of-selected-children/[LeetCode - 3075. Maximize Happiness of Selected Children ^]

You are given an array `happiness` of length `n`, and a *positive* integer `k`.

There are `n` children standing in a queue, where the `i^th^` child has *happiness value* `happiness[i]`. You want to select `k` children from these `n` children in `k` turns.

In each turn, when you select a child, the *happiness value* of all the children that have *not* been selected till now decreases by `1`. Note that the happiness value *cannot* become negative and gets decremented *only* if it is positive.

Return _the *maximum* sum of the happiness values of the selected children you can achieve by selecting _`k` _children_.

 
<strong class="example">Example 1:*

[subs="verbatim,quotes"]
----
*Input:* happiness = [1,2,3], k = 2
*Output:* 4
*Explanation:* We can pick 2 children in the following way:
- Pick the child with the happiness value == 3. The happiness value of the remaining children becomes [0,1].
- Pick the child with the happiness value == 1. The happiness value of the remaining child becomes [0]. Note that the happiness value cannot become less than 0.
The sum of the happiness values of the selected children is 3 + 1 = 4.
----

<strong class="example">Example 2:*

[subs="verbatim,quotes"]
----
*Input:* happiness = [1,1,1,1], k = 2
*Output:* 1
*Explanation:* We can pick 2 children in the following way:
- Pick any child with the happiness value == 1. The happiness value of the remaining children becomes [0,0,0].
- Pick the child with the happiness value == 0. The happiness value of the remaining child becomes [0,0].
The sum of the happiness values of the selected children is 1 + 0 = 1.
----

<strong class="example">Example 3:*

[subs="verbatim,quotes"]
----
*Input:* happiness = [2,3,4,5], k = 1
*Output:* 5
*Explanation:* We can pick 1 child in the following way:
- Pick the child with the happiness value == 5. The happiness value of the remaining children becomes [1,2,3].
The sum of the happiness values of the selected children is 5.
----

 
*Constraints:*


* `1 <= n == happiness.length <= 2 * 10^5^`
* `1 <= happiness[i] <= 10^8^`
* `1 <= k <= n`




== 思路分析


[[src-3075]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3075_MaximizeHappinessOfSelectedChildren.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3075_MaximizeHappinessOfSelectedChildren_2.java[tag=answer]
// ----
// --
====


== 参考资料


