[#3080-mark-elements-on-array-by-performing-queries]
= 3080. Mark Elements on Array by Performing Queries

{leetcode}/problems/mark-elements-on-array-by-performing-queries/[LeetCode - 3080. Mark Elements on Array by Performing Queries ^]

You are given a *0-indexed* array `nums` of size `n` consisting of positive integers.

You are also given a 2D array `queries` of size `m` where `queries[i] = [index<sub>i</sub>, k<sub>i</sub>]`.

Initially all elements of the array are *unmarked*.

You need to apply `m` queries on the array in order, where on the `i^th^` query you do the following:


* Mark the element at index `index<sub>i</sub>` if it is not already marked.
* Then mark `k<sub>i</sub>` unmarked elements in the array with the *smallest* values. If multiple such elements exist, mark the ones with the smallest indices. And if less than `k<sub>i</sub>` unmarked elements exist, then mark all of them.


Return _an array answer of size _`m`_ where _`answer[i]`_ is the *sum* of unmarked elements in the array after the _`i^th^`_ query_.

 
*Example 1:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">nums = [1,2,2,1,2,3,1], queries = [[1,2],[3,3],[4,2]]

*Output: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">[8,3,0]

*Explanation:*

We do the following queries on the array:


* Mark the element at index `1`, and `2` of the smallest unmarked elements with the smallest indices if they exist, the marked elements now are `nums = [*[.underline]#1#*,[.underline]#*2*#,2,[.underline]#*1*#,2,3,1]`. The sum of unmarked elements is `2 + 2 + 3 + 1 = 8`.
* Mark the element at index `3`, since it is already marked we skip it. Then we mark `3` of the smallest unmarked elements with the smallest indices, the marked elements now are `nums = [*[.underline]#1#*,[.underline]#*2*#,[.underline]#*2*#,[.underline]#*1*#,[.underline]#*2*#,3,*[.underline]#1#*]`. The sum of unmarked elements is `3`.
* Mark the element at index `4`, since it is already marked we skip it. Then we mark `2` of the smallest unmarked elements with the smallest indices if they exist, the marked elements now are `nums = [*[.underline]#1#*,[.underline]#*2*#,[.underline]#*2*#,[.underline]#*1*#,[.underline]#*2*#,*[.underline]#3#*,[.underline]#*1*#]`. The sum of unmarked elements is `0`.



*Example 2:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">nums = [1,4,2,3], queries = [[0,1]]

*Output: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">[7]

*Explanation: * We do one query which is mark the element at index `0` and mark the smallest element among unmarked elements. The marked elements will be `nums = [*[.underline]#1#*,4,[.underline]#*2*#,3]`, and the sum of unmarked elements is `4 + 3 = 7`.


 
*Constraints:*


* `n == nums.length`
* `m == queries.length`
* `1 <= m <= n <= 10^5^`
* `1 <= nums[i] <= 10^5^`
* `queries[i].length == 2`
* `0 <= index<sub>i</sub>, k<sub>i</sub> <= n - 1`




== 思路分析


[[src-3080]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3080_MarkElementsOnArrayByPerformingQueries.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3080_MarkElementsOnArrayByPerformingQueries_2.java[tag=answer]
// ----
// --
====


== 参考资料


