[#3081-replace-question-marks-in-string-to-minimize-its-value]
= 3081. Replace Question Marks in String to Minimize Its Value

https://leetcode.com/problems/replace-question-marks-in-string-to-minimize-its-value/[LeetCode - 3081. Replace Question Marks in String to Minimize Its Value ^]

You are given a string `s`. `s[i]` is either a lowercase English letter or `'?'`.

For a string `t` having length `m` containing *only* lowercase English letters, we define the function `cost(i)` for an index `i` as the number of characters *equal* to `t[i]` that appeared before it, i.e. in the range `[0, i - 1]`.

The *value* of `t` is the *sum* of `cost(i)` for all indices `i`.

For example, for the string `t = "aab"`:


* `cost(0) = 0`
* `cost(1) = 1`
* `cost(2) = 0`
* Hence, the value of `"aab"` is `0 + 1 + 0 = 1`.


Your task is to *replace all* occurrences of `'?'` in `s` with any lowercase English letter so that the *value* of `s` is *minimized*.

Return _a string denoting the modified string with replaced occurrences of _`'?'`_. If there are multiple strings resulting in the *minimum value*, return the <span data-keyword="lexicographically-smaller-string">lexicographically smallest one._

 
<strong class="example">Example 1:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> s = "???" 

*Output: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> "abc" 

*Explanation: * In this example, we can replace the occurrences of `'?'` to make `s` equal to `"abc"`.

For `"abc"`, `cost(0) = 0`, `cost(1) = 0`, and `cost(2) = 0`.

The value of `"abc"` is `0`.

Some other modifications of `s` that have a value of `0` are `"cba"`, `"abz"`, and, `"hey"`.

Among all of them, we choose the lexicographically smallest.


<strong class="example">Example 2:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">s = "a?a?"

*Output: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">"abac"

*Explanation: * In this example, the occurrences of `'?'` can be replaced to make `s` equal to `"abac"`.

For `"abac"`, `cost(0) = 0`, `cost(1) = 0`, `cost(2) = 1`, and `cost(3) = 0`.

The value of `"abac"` is `1`.


 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s[i]` is either a lowercase English letter or `'?'`.




== 思路分析


[[src-3081]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3081_ReplaceQuestionMarksInStringToMinimizeItsValue.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3081_ReplaceQuestionMarksInStringToMinimizeItsValue_2.java[tag=answer]
// ----
// --
====


== 参考资料


