[#3082-find-the-sum-of-the-power-of-all-subsequences]
= 3082. Find the Sum of the Power of All Subsequences

https://leetcode.com/problems/find-the-sum-of-the-power-of-all-subsequences/[LeetCode - 3082. Find the Sum of the Power of All Subsequences ^]

You are given an integer array `nums` of length `n` and a *positive* integer `k`.

The *power* of an array of integers is defined as the number of <span data-keyword="subsequence-array">subsequences with their sum *equal* to `k`.

Return _the *sum* of *power* of all subsequences of_ `nums`_._

Since the answer may be very large, return it *modulo* `10^9^ + 7`.

 
<strong class="example">Example 1:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> nums = [1,2,3], k = 3 

*Output: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> 6 

*Explanation:*

There are `5` subsequences of nums with non-zero power:


* The subsequence `[[.underline]#*1*#,[.underline]#*2*#,[.underline]#*3*#]` has `2` subsequences with `sum == 3`: `[1,2,[.underline]#3#]` and `[[.underline]#1#,[.underline]#2#,3]`.
* The subsequence `[[.underline]#*1*#,2,[.underline]#*3*#]` has `1` subsequence with `sum == 3`: `[1,2,[.underline]#3#]`.
* The subsequence `[1,[.underline]#*2*#,[.underline]#*3*#]` has `1` subsequence with `sum == 3`: `[1,2,[.underline]#3#]`.
* The subsequence `[[.underline]#*1*#,[.underline]#*2*#,3]` has `1` subsequence with `sum == 3`: `[[.underline]#1#,[.underline]#2#,3]`.
* The subsequence `[1,2,[.underline]#*3*#]` has `1` subsequence with `sum == 3`: `[1,2,[.underline]#3#]`.


Hence the answer is `2 + 1 + 1 + 1 + 1 = 6`.


<strong class="example">Example 2:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> nums = [2,3,3], k = 5 

*Output: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> 4 

*Explanation:*

There are `3` subsequences of nums with non-zero power:


* The subsequence `[[.underline]#*2*#,[.underline]#*3*#,[.underline]#*3*#]` has 2 subsequences with `sum == 5`: `[[.underline]#2#,3,[.underline]#3#]` and `[[.underline]#2#,[.underline]#3#,3]`.
* The subsequence `[[.underline]#*2*#,3,[.underline]#*3*#]` has 1 subsequence with `sum == 5`: `[[.underline]#2#,3,[.underline]#3#]`.
* The subsequence `[[.underline]#*2*#,[.underline]#*3*#,3]` has 1 subsequence with `sum == 5`: `[[.underline]#2#,[.underline]#3#,3]`.


Hence the answer is `2 + 1 + 1 = 4`.


<strong class="example">Example 3:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> nums = [1,2,3], k = 7 

*Output: * <span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;"> 0 

*Explanation: *There exists no subsequence with sum `7`. Hence all subsequences of nums have `power = 0`.


 
*Constraints:*


* `1 <= n <= 100`
* `1 <= nums[i] <= 10^4^`
* `1 <= k <= 100`




== 思路分析


[[src-3082]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3082_FindTheSumOfThePowerOfAllSubsequences.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3082_FindTheSumOfThePowerOfAllSubsequences_2.java[tag=answer]
// ----
// --
====


== 参考资料


