[#3083-existence-of-a-substring-in-a-string-and-its-reverse]
= 3083. Existence of a Substring in a String and Its Reverse

https://leetcode.com/problems/existence-of-a-substring-in-a-string-and-its-reverse/[LeetCode - 3083. Existence of a Substring in a String and Its Reverse ^]

Given a* *string `s`, find any <span data-keyword="substring">substring of length `2` which is also present in the reverse of `s`.

Return `true`_ if such a substring exists, and _`false`_ otherwise._

 
<strong class="example">Example 1:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">s = "leetcode"

*Output: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">true

*Explanation:* Substring `"ee"` is of length `2` which is also present in `reverse(s) == "edocteel"`.


<strong class="example">Example 2:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">s = "abcba"

*Output: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">true

*Explanation:* All of the substrings of length `2` `"ab"`, `"bc"`, `"cb"`, `"ba"` are also present in `reverse(s) == "abcba"`.


<strong class="example">Example 3:*

<div class="example-block" style="border-color: var(--border-tertiary); border-left-width: 2px; color: var(--text-secondary); font-size: .875rem; margin-bottom: 1rem; margin-top: 1rem; overflow: visible; padding-left: 1rem;">
*Input: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">s = "abcd"

*Output: *<span class="example-io" style="font-family: Menlo,sans-serif; font-size: 0.85rem;">false

*Explanation:* There is no substring of length `2` in `s`, which is also present in the reverse of `s`.


 
*Constraints:*


* `1 <= s.length <= 100`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3083]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3083_ExistenceOfASubstringInAStringAndItsReverse.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3083_ExistenceOfASubstringInAStringAndItsReverse_2.java[tag=answer]
// ----
// --
====


== 参考资料


