[#3090-maximum-length-substring-with-two-occurrences]
= 3090. Maximum Length Substring With Two Occurrences

{leetcode}/problems/maximum-length-substring-with-two-occurrences/[LeetCode - 3090. Maximum Length Substring With Two Occurrences ^]

Given a string `s`, return the *maximum* length of a <span data-keyword="substring">substring such that it contains _at most two occurrences_ of each character.
 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "bcbbbcba"

*Output:* <span class="example-io">4

*Explanation:*
The following substring has a length of 4 and contains at most two occurrences of each character: `"bcbb[.underline]#bcba#"`.

<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "aaaa"

*Output:* <span class="example-io">2

*Explanation:*
The following substring has a length of 2 and contains at most two occurrences of each character: `"[.underline]#aa#aa"`.

 
*Constraints:*


* `2 <= s.length <= 100`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3090]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3090_MaximumLengthSubstringWithTwoOccurrences.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3090_MaximumLengthSubstringWithTwoOccurrences_2.java[tag=answer]
// ----
// --
====


== 参考资料


