[#3092-most-frequent-ids]
= 3092. Most Frequent IDs

https://leetcode.com/problems/most-frequent-ids/[LeetCode - 3092. Most Frequent IDs ^]

The problem involves tracking the frequency of IDs in a collection that changes over time. You have two integer arrays, `nums` and `freq`, of equal length `n`. Each element in `nums` represents an ID, and the corresponding element in `freq` indicates how many times that ID should be added to or removed from the collection at each step.


* *Addition of IDs:* If `freq[i]` is positive, it means `freq[i]` IDs with the value `nums[i]` are added to the collection at step `i`.
* *Removal of IDs:* If `freq[i]` is negative, it means `-freq[i]` IDs with the value `nums[i]` are removed from the collection at step `i`.


Return an array `ans` of length `n`, where `ans[i]` represents the *count* of the _most frequent ID_ in the collection after the `i^th^` step. If the collection is empty at any step, `ans[i]` should be 0 for that step.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [2,3,2,1], freq = [3,2,-3,1]

*Output:* <span class="example-io">[3,3,2,2]

*Explanation:*

After step 0, we have 3 IDs with the value of 2. So `ans[0] = 3`.


After step 1, we have 3 IDs with the value of 2 and 2 IDs with the value of 3. So `ans[1] = 3`.


After step 2, we have 2 IDs with the value of 3. So `ans[2] = 2`.


After step 3, we have 2 IDs with the value of 3 and 1 ID with the value of 1. So `ans[3] = 2`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [5,5,3], freq = [2,-2,1]

*Output:* <span class="example-io">[2,0,1]

*Explanation:*

After step 0, we have 2 IDs with the value of 5. So `ans[0] = 2`.


After step 1, there are no IDs. So `ans[1] = 0`.


After step 2, we have 1 ID with the value of 3. So `ans[2] = 1`.


 
*Constraints:*


* `1 <= nums.length == freq.length <= 10^5^`
* `1 <= nums[i] <= 10^5^`
* `-10^5^ <= freq[i] <= 10^5^`
* `freq[i] != 0`
* The input is generated<!-- notionvc: a136b55a-f319-4fa6-9247-11be9f3b1db8 --> such that the occurrences of an ID will not be negative in any step.




== 思路分析


[[src-3092]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3092_MostFrequentIds.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3092_MostFrequentIds_2.java[tag=answer]
// ----
// --
====


== 参考资料


