[#3093-longest-common-suffix-queries]
= 3093. Longest Common Suffix Queries

https://leetcode.com/problems/longest-common-suffix-queries/[LeetCode - 3093. Longest Common Suffix Queries ^]

You are given two arrays of strings `wordsContainer` and `wordsQuery`.

For each `wordsQuery[i]`, you need to find a string from `wordsContainer` that has the *longest common suffix* with `wordsQuery[i]`. If there are two or more strings in `wordsContainer` that share the longest common suffix, find the string that is the *smallest* in length. If there are two or more such strings that have the *same* smallest length, find the one that occurred *earlier* in `wordsContainer`.

Return _an array of integers _`ans`_, where _`ans[i]`_ is the index of the string in _`wordsContainer`_ that has the *longest common suffix* with _`wordsQuery[i]`_._

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">wordsContainer = ["abcd","bcd","xbcd"], wordsQuery = ["cd","bcd","xyz"]

*Output:* <span class="example-io">[1,1,1]

*Explanation:*

Let's look at each `wordsQuery[i]` separately:


* For `wordsQuery[0] = "cd"`, strings from `wordsContainer` that share the longest common suffix `"cd"` are at indices 0, 1, and 2. Among these, the answer is the string at index 1 because it has the shortest length of 3.
* For `wordsQuery[1] = "bcd"`, strings from `wordsContainer` that share the longest common suffix `"bcd"` are at indices 0, 1, and 2. Among these, the answer is the string at index 1 because it has the shortest length of 3.
* For `wordsQuery[2] = "xyz"`, there is no string from `wordsContainer` that shares a common suffix. Hence the longest common suffix is `""`, that is shared with strings at index 0, 1, and 2. Among these, the answer is the string at index 1 because it has the shortest length of 3.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">wordsContainer = ["abcdefgh","poiuygh","ghghgh"], wordsQuery = ["gh","acbfgh","acbfegh"]

*Output:* <span class="example-io">[2,0,2]

*Explanation:*

Let's look at each `wordsQuery[i]` separately:


* For `wordsQuery[0] = "gh"`, strings from `wordsContainer` that share the longest common suffix `"gh"` are at indices 0, 1, and 2. Among these, the answer is the string at index 2 because it has the shortest length of 6.
* For `wordsQuery[1] = "acbfgh"`, only the string at index 0 shares the longest common suffix `"fgh"`. Hence it is the answer, even though the string at index 2 is shorter.
* For `wordsQuery[2] = "acbfegh"`, strings from `wordsContainer` that share the longest common suffix `"gh"` are at indices 0, 1, and 2. Among these, the answer is the string at index 2 because it has the shortest length of 6.



 
*Constraints:*


* `1 <= wordsContainer.length, wordsQuery.length <= 10^4^`
* `1 <= wordsContainer[i].length <= 5 * 10^3^`
* `1 <= wordsQuery[i].length <= 5 * 10^3^`
* `wordsContainer[i]` consists only of lowercase English letters.
* `wordsQuery[i]` consists only of lowercase English letters.
* Sum of `wordsContainer[i].length` is at most `5 * 10^5^`.
* Sum of `wordsQuery[i].length` is at most `5 * 10^5^`.




== 思路分析


[[src-3093]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3093_LongestCommonSuffixQueries.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3093_LongestCommonSuffixQueries_2.java[tag=answer]
// ----
// --
====


== 参考资料


