[#3102-minimize-manhattan-distances]
= 3102. Minimize Manhattan Distances

{leetcode}/problems/minimize-manhattan-distances/[LeetCode - 3102. Minimize Manhattan Distances ^]

You are given a array `points` representing integer coordinates of some points on a 2D plane, where `points[i] = [x<sub>i</sub>, y<sub>i</sub>]`.

The distance between two points is defined as their <span data-keyword="manhattan-distance">Manhattan distance.

Return _the *minimum* possible value for *maximum* distance between any two points by removing exactly one point_.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">points = [[3,10],[5,15],[10,2],[4,4]]

*Output:* <span class="example-io">12

*Explanation:*

The maximum distance after removing each point is the following:


* After removing the 0^th^ point the maximum distance is between points (5, 15) and (10, 2), which is `|5 - 10| + |15 - 2| = 18`.
* After removing the 1^st^ point the maximum distance is between points (3, 10) and (10, 2), which is `|3 - 10| + |10 - 2| = 15`.
* After removing the 2^nd^ point the maximum distance is between points (5, 15) and (4, 4), which is `|5 - 4| + |15 - 4| = 12`.
* After removing the 3^rd^ point the maximum distance is between points (5, 15) and (10, 2), which is `|5 - 10| + |15 - 2| = 18`.


12 is the minimum possible maximum distance between any two points after removing exactly one point.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">points = [[1,1],[1,1],[1,1]]

*Output:* <span class="example-io">0

*Explanation:*

Removing any of the points results in the maximum distance between any two points of 0.


 
*Constraints:*


* `3 <= points.length <= 10^5^`
* `points[i].length == 2`
* `1 <= points[i][0], points[i][1] <= 10^8^`




== 思路分析


[[src-3102]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3102_MinimizeManhattanDistances.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3102_MinimizeManhattanDistances_2.java[tag=answer]
// ----
// --
====


== 参考资料


