[#3106-lexicographically-smallest-string-after-operations-with-constraint]
= 3106. Lexicographically Smallest String After Operations With Constraint

{leetcode}/problems/lexicographically-smallest-string-after-operations-with-constraint/[LeetCode - 3106. Lexicographically Smallest String After Operations With Constraint ^]

You are given a string `s` and an integer `k`.

Define a function `distance(s<sub>1</sub>, s<sub>2</sub>)` between two strings `s<sub>1</sub>` and `s<sub>2</sub>` of the same length `n` as:


* The* sum* of the *minimum distance* between `s<sub>1</sub>[i]` and `s<sub>2</sub>[i]` when the characters from `'a'` to `'z'` are placed in a *cyclic* order, for all `i` in the range `[0, n - 1]`.


For example, `distance("ab", "cd") == 4`, and `distance("a", "z") == 1`.

You can *change* any letter of `s` to *any* other lowercase English letter, *any* number of times.

Return a string denoting the *<span data-keyword="lexicographically-smaller-string">lexicographically smallest* string `t` you can get after some changes, such that `distance(s, t) <= k`.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "zbbz", k = 3

*Output:* <span class="example-io">"aaaz"

*Explanation:*

Change `s` to `"aaaz"`. The distance between `"zbbz"` and `"aaaz"` is equal to `k = 3`.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "xaxcd", k = 4

*Output:* <span class="example-io">"aawcd"

*Explanation:*

The distance between "xaxcd" and "aawcd" is equal to k = 4.


*Example 3:*

<div class="example-block">
*Input:* <span class="example-io">s = "lol", k = 0

*Output:* <span class="example-io">"lol"

*Explanation:*

It's impossible to change any character as `k = 0`.


 
*Constraints:*


* `1 <= s.length <= 100`
* `0 <= k <= 2000`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3106]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3106_LexicographicallySmallestStringAfterOperationsWithConstraint.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3106_LexicographicallySmallestStringAfterOperationsWithConstraint_2.java[tag=answer]
// ----
// --
====


== 参考资料


