[#3120-count-the-number-of-special-characters-i]
= 3120. Count the Number of Special Characters I

{leetcode}/problems/count-the-number-of-special-characters-i/[LeetCode - 3120. Count the Number of Special Characters I ^]

You are given a string `word`. A letter is called *special* if it appears *both* in lowercase and uppercase in `word`.

Return the number of_ _*special* letters in_ _`word`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">word = "aaAbcBC"

*Output:* <span class="example-io">3

*Explanation:*

The special characters in `word` are `'a'`, `'b'`, and `'c'`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">word = "abc"

*Output:* <span class="example-io">0

*Explanation:*

No character in `word` appears in uppercase.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">word = "abBCab"

*Output:* 1

*Explanation:*

The only special character in `word` is `'b'`.


 
*Constraints:*


* `1 <= word.length <= 50`
* `word` consists of only lowercase and uppercase English letters.




== 思路分析


[[src-3120]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3120_CountTheNumberOfSpecialCharactersI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3120_CountTheNumberOfSpecialCharactersI_2.java[tag=answer]
// ----
// --
====


== 参考资料


