[#3131-find-the-integer-added-to-array-i]
= 3131. Find the Integer Added to Array I

{leetcode}/problems/find-the-integer-added-to-array-i/[LeetCode - 3131. Find the Integer Added to Array I ^]

You are given two arrays of equal length, `nums1` and `nums2`.

Each element in `nums1` has been increased (or decreased in the case of negative) by an integer, represented by the variable `x`.

As a result, `nums1` becomes *equal* to `nums2`. Two arrays are considered *equal* when they contain the same integers with the same frequencies.

Return the integer `x`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">nums1 = [2,6,4], nums2 = [9,7,5]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">3

*Explanation:*

The integer added to each element of `nums1` is 3.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">nums1 = [10], nums2 = [5]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">-5

*Explanation:*

The integer added to each element of `nums1` is -5.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">nums1 = [1,1,1,1], nums2 = [1,1,1,1]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">0

*Explanation:*

The integer added to each element of `nums1` is 0.


 
*Constraints:*


* `1 <= nums1.length == nums2.length <= 100`
* `0 <= nums1[i], nums2[i] <= 1000`
* The test cases are generated in a way that there is an integer `x` such that `nums1` can become equal to `nums2` by adding `x` to each element of `nums1`.




== 思路分析


[[src-3131]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3131_FindTheIntegerAddedToArrayI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3131_FindTheIntegerAddedToArrayI_2.java[tag=answer]
// ----
// --
====


== 参考资料


