[#3132-find-the-integer-added-to-array-ii]
= 3132. Find the Integer Added to Array II

{leetcode}/problems/find-the-integer-added-to-array-ii/[LeetCode - 3132. Find the Integer Added to Array II ^]

You are given two integer arrays `nums1` and `nums2`.

From `nums1` two elements have been removed, and all other elements have been increased (or decreased in the case of negative) by an integer, represented by the variable `x`.

As a result, `nums1` becomes *equal* to `nums2`. Two arrays are considered *equal* when they contain the same integers with the same frequencies.

Return the *minimum* possible integer_ _`x`_ _that achieves this equivalence.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">nums1 = [4,20,16,12,8], nums2 = [14,18,10]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">-2

*Explanation:*

After removing elements at indices `[0,4]` and adding -2, `nums1` becomes `[18,14,10]`.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">nums1 = [3,5,5,3], nums2 = [7,7]

*Output:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">2

*Explanation:*

After removing elements at indices `[0,3]` and adding 2, `nums1` becomes `[7,7]`.


 
*Constraints:*


* `3 <= nums1.length <= 200`
* `nums2.length == nums1.length - 2`
* `0 <= nums1[i], nums2[i] <= 1000`
* The test cases are generated in a way that there is an integer `x` such that `nums1` can become equal to `nums2` by removing two elements and adding `x` to each element of `nums1`.




== 思路分析


[[src-3132]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3132_FindTheIntegerAddedToArrayIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3132_FindTheIntegerAddedToArrayIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


