[#3136-valid-word]
= 3136. Valid Word

{leetcode}/problems/valid-word/[LeetCode - 3136. Valid Word ^]

A word is considered *valid* if:


* It contains a *minimum* of 3 characters.
* It contains only digits (0-9), and English letters (uppercase and lowercase).
* It includes *at least* one *vowel*.
* It includes *at least* one *consonant*.


You are given a string `word`.

Return `true` if `word` is valid, otherwise, return `false`.

*Notes:*


* `'a'`, `'e'`, `'i'`, `'o'`, `'u'`, and their uppercases are *vowels*.
* A *consonant* is an English letter that is not a vowel.


 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">word = "234Adas"

*Output:* <span class="example-io">true

*Explanation:*

This word satisfies the conditions.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">word = "b3"

*Output:* <span class="example-io">false

*Explanation:*

The length of this word is fewer than 3, and does not have a vowel.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">word = "a3$e"

*Output:* <span class="example-io">false

*Explanation:*

This word contains a `'$'` character and does not have a consonant.


 
*Constraints:*


* `1 <= word.length <= 20`
* `word` consists of English uppercase and lowercase letters, digits, `'@'`, `'#'`, and `'$'`.




== 思路分析


[[src-3136]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3136_ValidWord.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3136_ValidWord_2.java[tag=answer]
// ----
// --
====


== 参考资料


