[#3137-minimum-number-of-operations-to-make-word-k-periodic]
= 3137. Minimum Number of Operations to Make Word K-Periodic

{leetcode}/problems/minimum-number-of-operations-to-make-word-k-periodic/[LeetCode - 3137. Minimum Number of Operations to Make Word K-Periodic ^]

You are given a string `word` of size `n`, and an integer `k` such that `k` divides `n`.

In one operation, you can pick any two indices `i` and `j`, that are divisible by `k`, then replace the <span data-keyword="substring">substring of length `k` starting at `i` with the substring of length `k` starting at `j`. That is, replace the substring `word[i..i + k - 1]` with the substring `word[j..j + k - 1]`.<!-- notionvc: 49ac84f7-0724-452a-ab43-0c5e53f1db33 -->

Return _the *minimum* number of operations required to make_ `word` _*k-periodic*_.

We say that `word` is *k-periodic* if there is some string `s` of length `k` such that `word` can be obtained by concatenating `s` an arbitrary number of times. For example, if `word == &ldquo;ababab&rdquo;`, then `word` is 2-periodic for `s = "ab"`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">word = "leetcodeleet", k = 4

*Output:* <span class="example-io" style="
font-family: Menlo,sans-serif;
font-size: 0.85rem;
">1

*Explanation:*

We can obtain a 4-periodic string by picking i = 4 and j = 0. After this operation, word becomes equal to "leetleetleet".


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">word = "leetcoleet<span class="example-io" style="
    font-family: Menlo,sans-serif;
    font-size: 0.85rem;
">", k = 2

*Output:* 3

*Explanation:*

We can obtain a 2-periodic string by applying the operations in the table below.

<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" height="146" style="border-collapse:collapse; text-align: center; vertical-align: middle;">
	<tbody>
		<tr>
			<th>i</th>
			<th>j</th>
			<th>word</th>
		</tr>
		<tr>
			<td style="padding: 5px 15px;">0</td>
			<td style="padding: 5px 15px;">2</td>
			<td style="padding: 5px 15px;">etetcoleet</td>
		</tr>
		<tr>
			<td style="padding: 5px 15px;">4</td>
			<td style="padding: 5px 15px;">0</td>
			<td style="padding: 5px 15px;">etetetleet</td>
		</tr>
		<tr>
			<td style="padding: 5px 15px;">6</td>
			<td style="padding: 5px 15px;">0</td>
			<td style="padding: 5px 15px;">etetetetet</td>
		</tr>
	</tbody>
</table>


<div id="gtx-trans" style="position: absolute; left: 107px; top: 238.5px;">
<div class="gtx-trans-icon"> 


 
*Constraints:*


* `1 <= n == word.length <= 10^5^`
* `1 <= k <= word.length`
* `k` divides `word.length`.
* `word` consists only of lowercase English letters.




== 思路分析


[[src-3137]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3137_MinimumNumberOfOperationsToMakeWordKPeriodic.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3137_MinimumNumberOfOperationsToMakeWordKPeriodic_2.java[tag=answer]
// ----
// --
====


== 参考资料


