[#3138-minimum-length-of-anagram-concatenation]
= 3138. Minimum Length of Anagram Concatenation

{leetcode}/problems/minimum-length-of-anagram-concatenation/[LeetCode - 3138. Minimum Length of Anagram Concatenation ^]

You are given a string `s`, which is known to be a concatenation of *anagrams* of some string `t`.

Return the *minimum* possible length of the string `t`.

An *anagram* is formed by rearranging the letters of a string. For example, "aab", "aba", and, "baa" are anagrams of "aab".

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "abba"

*Output:* <span class="example-io">2

*Explanation:*

One possible string `t` could be `"ba"`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "cdef"

*Output:* <span class="example-io">4

*Explanation:*

One possible string `t` could be `"cdef"`, notice that `t` can be equal to `s`.


 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consist only of lowercase English letters.




== 思路分析


[[src-3138]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3138_MinimumLengthOfAnagramConcatenation.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3138_MinimumLengthOfAnagramConcatenation_2.java[tag=answer]
// ----
// --
====


== 参考资料


