[#3146-permutation-difference-between-two-strings]
= 3146. Permutation Difference between Two Strings

{leetcode}/problems/permutation-difference-between-two-strings/[LeetCode - 3146. Permutation Difference between Two Strings ^]

You are given two strings `s` and `t` such that every character occurs at most once in `s` and `t` is a permutation of `s`.

The *permutation difference* between `s` and `t` is defined as the *sum* of the absolute difference between the index of the occurrence of each character in `s` and the index of the occurrence of the same character in `t`.

Return the *permutation difference* between `s` and `t`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "abc", t = "bac"

*Output:* <span class="example-io">2

*Explanation:*

For `s = "abc"` and `t = "bac"`, the permutation difference of `s` and `t` is equal to the sum of:


* The absolute difference between the index of the occurrence of `"a"` in `s` and the index of the occurrence of `"a"` in `t`.
* The absolute difference between the index of the occurrence of `"b"` in `s` and the index of the occurrence of `"b"` in `t`.
* The absolute difference between the index of the occurrence of `"c"` in `s` and the index of the occurrence of `"c"` in `t`.


That is, the permutation difference between `s` and `t` is equal to `|0 - 1| + |2 - 2| + |1 - 0| = 2`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "abcde", t = "edbac"

*Output:* <span class="example-io">12

*Explanation:* The permutation difference between `s` and `t` is equal to `|0 - 3| + |1 - 2| + |2 - 4| + |3 - 1| + |4 - 0| = 12`.


 
*Constraints:*


* `1 <= s.length <= 26`
* Each character occurs at most once in `s`.
* `t` is a permutation of `s`.
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3146]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3146_PermutationDifferenceBetweenTwoStrings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3146_PermutationDifferenceBetweenTwoStrings_2.java[tag=answer]
// ----
// --
====


== 参考资料


