[#3152-special-array-ii]
= 3152. Special Array II

{leetcode}/problems/special-array-ii/[LeetCode - 3152. Special Array II ^]

An array is considered *special* if every pair of its adjacent elements contains two numbers with different parity.

You are given an array of integer `nums` and a 2D integer matrix `queries`, where for `queries[i] = [from<sub>i</sub>, to<sub>i</sub>]` your task is to check that <span data-keyword="subarray">subarray `nums[from<sub>i</sub>..to<sub>i</sub>]` is *special* or not.

Return an array of booleans `answer` such that `answer[i]` is `true` if `nums[from<sub>i</sub>..to<sub>i</sub>]` is special.<!-- notionvc: e5d6f4e2-d20a-4fbd-9c7f-22fbe52ef730 -->

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [3,4,1,2,6], queries = [[0,4]]

*Output:* <span class="example-io">[false]

*Explanation:*

The subarray is `[3,4,1,2,6]`. 2 and 6 are both even.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [4,3,1,6], queries = [[0,2],[2,3]]

*Output:* <span class="example-io">[false,true]

*Explanation:*


* The subarray is `[4,3,1]`. 3 and 1 are both odd. So the answer to this query is `false`.
* The subarray is `[1,6]`. There is only one pair: `(1,6)` and it contains numbers with different parity. So the answer to this query is `true`.



 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^5^`
* `1 <= queries.length <= 10^5^`
* `queries[i].length == 2`
* `0 <= queries[i][0] <= queries[i][1] <= nums.length - 1`




== 思路分析


[[src-3152]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3152_SpecialArrayIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3152_SpecialArrayIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


