[#3159-find-occurrences-of-an-element-in-an-array]
= 3159. Find Occurrences of an Element in an Array

https://leetcode.com/problems/find-occurrences-of-an-element-in-an-array/[LeetCode - 3159. Find Occurrences of an Element in an Array ^]

You are given an integer array `nums`, an integer array `queries`, and an integer `x`.

For each `queries[i]`, you need to find the index of the `queries[i]^th^` occurrence of `x` in the `nums` array. If there are fewer than `queries[i]` occurrences of `x`, the answer should be -1 for that query.

Return an integer array `answer` containing the answers to all queries.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,3,1,7], queries = [1,3,2,4], x = 1

*Output:* <span class="example-io">[0,-1,2,-1]

*Explanation:*


* For the 1^st^ query, the first occurrence of 1 is at index 0.
* For the 2^nd^ query, there are only two occurrences of 1 in `nums`, so the answer is -1.
* For the 3^rd^ query, the second occurrence of 1 is at index 2.
* For the 4^th^ query, there are only two occurrences of 1 in `nums`, so the answer is -1.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,3], queries = [10], x = 5

*Output:* <span class="example-io">[-1]

*Explanation:*


* For the 1^st^ query, 5 doesn't exist in `nums`, so the answer is -1.



 
*Constraints:*


* `1 <= nums.length, queries.length <= 10^5^`
* `1 <= queries[i] <= 10^5^`
* `1 <= nums[i], x <= 10^4^`




== 思路分析


[[src-3159]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3159_FindOccurrencesOfAnElementInAnArray.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3159_FindOccurrencesOfAnElementInAnArray_2.java[tag=answer]
// ----
// --
====


== 参考资料


