[#3169-count-days-without-meetings]
= 3169. Count Days Without Meetings

https://leetcode.com/problems/count-days-without-meetings/[LeetCode - 3169. Count Days Without Meetings ^]

You are given a positive integer `days` representing the total number of days an employee is available for work (starting from day 1). You are also given a 2D array `meetings` of size `n` where, `meetings[i] = [start_i, end_i]` represents the starting and ending days of meeting `i` (inclusive).

Return the count of days when the employee is available for work but no meetings are scheduled.

*Note: *The meetings may overlap.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">days = 10, meetings = [[5,7],[1,3],[9,10]]

*Output:* <span class="example-io">2

*Explanation:*

There is no meeting scheduled on the 4^th^ and 8^th^ days.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">days = 5, meetings = [[2,4],[1,3]]

*Output:* <span class="example-io">1

*Explanation:*

There is no meeting scheduled on the 5^th ^day.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">days = 6, meetings = [[1,6]]

*Output:* 0

*Explanation:*

Meetings are scheduled for all working days.


 
*Constraints:*


* `1 <= days <= 10^9^`
* `1 <= meetings.length <= 10^5^`
* `meetings[i].length == 2`
* `<font face="monospace">1 <= meetings[i][0] <= meetings[i][1] <= days`




== 思路分析


[[src-3169]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3169_CountDaysWithoutMeetings.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3169_CountDaysWithoutMeetings_2.java[tag=answer]
// ----
// --
====


== 参考资料


