[#3170-lexicographically-minimum-string-after-removing-stars]
= 3170. Lexicographically Minimum String After Removing Stars

{leetcode}/problems/lexicographically-minimum-string-after-removing-stars/[LeetCode - 3170. Lexicographically Minimum String After Removing Stars ^]

You are given a string `s`. It may contain any number of `'*'` characters. Your task is to remove all `'*'` characters.

While there is a `'*'`, do the following operation:


* Delete the leftmost `'*'` and the *smallest* non-`'*'` character to its _left_. If there are several smallest characters, you can delete any of them.


Return the <span data-keyword="lexicographically-smaller-string">lexicographically smallest resulting string after removing all `'*'` characters.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "aaba*"

*Output:* <span class="example-io">"aab"

*Explanation:*

We should delete one of the `'a'` characters with `'*'`. If we choose `s[3]`, `s` becomes the lexicographically smallest.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "abc"

*Output:* <span class="example-io">"abc"

*Explanation:*

There is no `'*'` in the string.<!-- notionvc: ff07e34f-b1d6-41fb-9f83-5d0ba3c1ecde -->


 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consists only of lowercase English letters and `'*'`.
* The input is generated such that it is possible to delete all `'*'` characters.




== 思路分析


[[src-3170]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3170_LexicographicallyMinimumStringAfterRemovingStars.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3170_LexicographicallyMinimumStringAfterRemovingStars_2.java[tag=answer]
// ----
// --
====


== 参考资料


