[#3171-find-subarray-with-bitwise-or-closest-to-k]
= 3171. Find Subarray With Bitwise OR Closest to K

{leetcode}/problems/find-subarray-with-bitwise-or-closest-to-k/[LeetCode - 3171. Find Subarray With Bitwise OR Closest to K ^]

You are given an array `nums` and an integer `k`. You need to find a <span data-keyword="subarray-nonempty">subarray of `nums` such that the *absolute difference* between `k` and the bitwise `OR` of the subarray elements is as* small* as possible. In other words, select a subarray `nums[l..r]` such that `|k - (nums[l] OR nums[l + 1] ... OR nums[r])|` is minimum.

Return the *minimum* possible value of the absolute difference.

A *subarray* is a contiguous *non-empty* sequence of elements within an array.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,4,5], k = 3

*Output:* 0

*Explanation:*

The subarray `nums[0..1]` has `OR` value 3, which gives the minimum absolute difference `|3 - 3| = 0`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,3,1,3], k = 2

*Output:* 1

*Explanation:*

The subarray `nums[1..1]` has `OR` value 3, which gives the minimum absolute difference `|3 - 2| = 1`.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1], k = 10

*Output:* <span class="example-io">9

*Explanation:*

There is a single subarray with `OR` value 1, which gives the minimum absolute difference `|10 - 1| = 9`.


 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `1 <= nums[i] <= 10^9^`
* `1 <= k <= 10^9^`




== 思路分析


[[src-3171]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3171_FindSubarrayWithBitwiseOrClosestToK.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3171_FindSubarrayWithBitwiseOrClosestToK_2.java[tag=answer]
// ----
// --
====


== 参考资料


