[#3177-find-the-maximum-length-of-a-good-subsequence-ii]
= 3177. Find the Maximum Length of a Good Subsequence II

{leetcode}/problems/find-the-maximum-length-of-a-good-subsequence-ii/[LeetCode - 3177. Find the Maximum Length of a Good Subsequence II ^]

You are given an integer array `nums` and a *non-negative* integer `k`. A sequence of integers `seq` is called *good* if there are *at most* `k` indices `i` in the range `[0, seq.length - 2]` such that `seq[i] != seq[i + 1]`.

Return the *maximum* possible length of a *good* <span data-keyword="subsequence-array">subsequence of `nums`.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,1,1,3], k = 2

*Output:* <span class="example-io">4

*Explanation:*

The maximum length subsequence is `[[.underline]#1#,[.underline]#2#,[.underline]#1#,[.underline]#1#,3]`.


*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,3,4,5,1], k = 0

*Output:* <span class="example-io">2

*Explanation:*

The maximum length subsequence is `[[.underline]#1#,2,3,4,5,[.underline]#1#]`.


 
*Constraints:*


* `1 <= nums.length <= 5 * 10^3^`
* `1 <= nums[i] <= 10^9^`
* `0 <= k <= min(50, nums.length)`




== 思路分析


[[src-3177]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3177_FindTheMaximumLengthOfAGoodSubsequenceIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3177_FindTheMaximumLengthOfAGoodSubsequenceIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


