[#3181-maximum-total-reward-using-operations-ii]
= 3181. Maximum Total Reward Using Operations II

{leetcode}/problems/maximum-total-reward-using-operations-ii/[LeetCode - 3181. Maximum Total Reward Using Operations II ^]

You are given an integer array `rewardValues` of length `n`, representing the values of rewards.

Initially, your total reward `x` is 0, and all indices are *unmarked*. You are allowed to perform the following operation *any* number of times:


* Choose an *unmarked* index `i` from the range `[0, n - 1]`.
* If `rewardValues[i]` is *greater* than your current total reward `x`, then add `rewardValues[i]` to `x` (i.e., `x = x + rewardValues[i]`), and *mark* the index `i`.


Return an integer denoting the *maximum *_total reward_ you can collect by performing the operations optimally.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">rewardValues = [1,1,3,3]

*Output:* <span class="example-io">4

*Explanation:*

During the operations, we can choose to mark the indices 0 and 2 in order, and the total reward will be 4, which is the maximum.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">rewardValues = [1,6,4,3,2]

*Output:* <span class="example-io">11

*Explanation:*

Mark the indices 0, 2, and 1 in order. The total reward will then be 11, which is the maximum.


 
*Constraints:*


* `1 <= rewardValues.length <= 5 * 10^4^`
* `1 <= rewardValues[i] <= 5 * 10^4^`




== 思路分析


[[src-3181]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3181_MaximumTotalRewardUsingOperationsIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3181_MaximumTotalRewardUsingOperationsIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


