[#3191-minimum-operations-to-make-binary-array-elements-equal-to-one-i]
= 3191. Minimum Operations to Make Binary Array Elements Equal to One I

https://leetcode.com/problems/minimum-operations-to-make-binary-array-elements-equal-to-one-i/[LeetCode - 3191. Minimum Operations to Make Binary Array Elements Equal to One I ^]

You are given a <span data-keyword="binary-array">binary array `nums`.

You can do the following operation on the array *any* number of times (possibly zero):


* Choose *any* 3 *consecutive* elements from the array and *flip* *all* of them.


*Flipping* an element means changing its value from 0 to 1, and from 1 to 0.

Return the *minimum* number of operations required to make all elements in `nums` equal to 1. If it is impossible, return -1.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [0,1,1,1,0,0]

*Output:* <span class="example-io">3

*Explanation:*


We can do the following operations:


* Choose the elements at indices 0, 1 and 2. The resulting array is `nums = [[.underline]#*1*#,[.underline]#*0*#,[.underline]#*0*#,1,0,0]`.
* Choose the elements at indices 1, 2 and 3. The resulting array is `nums = [1,[.underline]#*1*#,[.underline]#*1*#,*[.underline]#0#*,0,0]`.
* Choose the elements at indices 3, 4 and 5. The resulting array is `nums = [1,1,1,*[.underline]#1#*,[.underline]#*1*#,[.underline]#*1*#]`.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [0,1,1,1]

*Output:* <span class="example-io">-1

*Explanation:*


It is impossible to make all elements equal to 1.


 
*Constraints:*


* `3 <= nums.length <= 10^5^`
* `0 <= nums[i] <= 1`




== 思路分析


[[src-3191]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3191_MinimumOperationsToMakeBinaryArrayElementsEqualToOneI.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3191_MinimumOperationsToMakeBinaryArrayElementsEqualToOneI_2.java[tag=answer]
// ----
// --
====


== 参考资料


