[#3192-minimum-operations-to-make-binary-array-elements-equal-to-one-ii]
= 3192. Minimum Operations to Make Binary Array Elements Equal to One II

{leetcode}/problems/minimum-operations-to-make-binary-array-elements-equal-to-one-ii/[LeetCode - 3192. Minimum Operations to Make Binary Array Elements Equal to One II ^]

You are given a <span data-keyword="binary-array">binary array `nums`.

You can do the following operation on the array *any* number of times (possibly zero):


* Choose *any* index `i` from the array and *flip* *all* the elements from index `i` to the end of the array.


*Flipping* an element means changing its value from 0 to 1, and from 1 to 0.

Return the *minimum* number of operations required to make all elements in `nums` equal to 1.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [0,1,1,0,1]

*Output:* <span class="example-io">4

*Explanation:*


We can do the following operations:


* Choose the index `i = 1`<span class="example-io">. The resulting array will be `nums = [0,[.underline]#*0*#,[.underline]#*0*#,[.underline]#*1*#,[.underline]#*0*#]`.
* Choose the index `i = 0`<span class="example-io">. The resulting array will be `nums = [[.underline]#*1*#,[.underline]#*1*#,[.underline]#*1*#,[.underline]#*0*#,[.underline]#*1*#]`.
* Choose the index `i = 4`<span class="example-io">. The resulting array will be `nums = [1,1,1,0,[.underline]#*0*#]`.
* Choose the index `i = 3`<span class="example-io">. The resulting array will be `nums = [1,1,1,[.underline]#*1*#,[.underline]#*1*#]`.



*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,0,0,0]

*Output:* <span class="example-io">1

*Explanation:*


We can do the following operation:


* Choose the index `i = 1`<span class="example-io">. The resulting array will be `nums = [1,[.underline]#*1*#,[.underline]#*1*#,[.underline]#*1*#]`.



 
*Constraints:*


* `1 <= nums.length <= 10^5^`
* `0 <= nums[i] <= 1`




== 思路分析


[[src-3192]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3192_MinimumOperationsToMakeBinaryArrayElementsEqualToOneIi.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3192_MinimumOperationsToMakeBinaryArrayElementsEqualToOneIi_2.java[tag=answer]
// ----
// --
====


== 参考资料


