[#3194-minimum-average-of-smallest-and-largest-elements]
= 3194. Minimum Average of Smallest and Largest Elements

https://leetcode.com/problems/minimum-average-of-smallest-and-largest-elements/[LeetCode - 3194. Minimum Average of Smallest and Largest Elements ^]

You have an array of floating point numbers `averages` which is initially empty. You are given an array `nums` of `n` integers where `n` is even.

You repeat the following procedure `n / 2` times:


* Remove the *smallest* element, `minElement`, and the *largest* element `maxElement`, from `nums`.
* Add `(minElement + maxElement) / 2` to `averages`.


Return the *minimum* element in `averages`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [7,8,3,4,15,13,4,1]

*Output:* <span class="example-io">5.5

*Explanation:*

<table>
	<tbody>
		<tr>
			<th>step</th>
			<th>nums</th>
			<th>averages</th>
		</tr>
		<tr>
			<td>0</td>
			<td>[7,8,3,4,15,13,4,1]</td>
			<td>[]</td>
		</tr>
		<tr>
			<td>1</td>
			<td>[7,8,3,4,13,4]</td>
			<td>[8]</td>
		</tr>
		<tr>
			<td>2</td>
			<td>[7,8,4,4]</td>
			<td>[8,8]</td>
		</tr>
		<tr>
			<td>3</td>
			<td>[7,4]</td>
			<td>[8,8,6]</td>
		</tr>
		<tr>
			<td>4</td>
			<td>[]</td>
			<td>[8,8,6,5.5]</td>
		</tr>
	</tbody>
</table>
The smallest element of averages, 5.5, is returned.

<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,9,8,3,10,5]

*Output:* <span class="example-io">5.5

*Explanation:*

<table>
	<tbody>
		<tr>
			<th>step</th>
			<th>nums</th>
			<th>averages</th>
		</tr>
		<tr>
			<td>0</td>
			<td><span class="example-io">[1,9,8,3,10,5]</td>
			<td>[]</td>
		</tr>
		<tr>
			<td>1</td>
			<td><span class="example-io">[9,8,3,5]</td>
			<td>[5.5]</td>
		</tr>
		<tr>
			<td>2</td>
			<td><span class="example-io">[8,5]</td>
			<td>[5.5,6]</td>
		</tr>
		<tr>
			<td>3</td>
			<td>[]</td>
			<td>[5.5,6,6.5]</td>
		</tr>
	</tbody>
</table>


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,3,7,8,9]

*Output:* <span class="example-io">5.0

*Explanation:*

<table>
	<tbody>
		<tr>
			<th>step</th>
			<th>nums</th>
			<th>averages</th>
		</tr>
		<tr>
			<td>0</td>
			<td><span class="example-io">[1,2,3,7,8,9]</td>
			<td>[]</td>
		</tr>
		<tr>
			<td>1</td>
			<td><span class="example-io">[2,3,7,8]</td>
			<td>[5]</td>
		</tr>
		<tr>
			<td>2</td>
			<td><span class="example-io">[3,7]</td>
			<td>[5,5]</td>
		</tr>
		<tr>
			<td>3</td>
			<td><span class="example-io">[]</td>
			<td>[5,5,5]</td>
		</tr>
	</tbody>
</table>


 
*Constraints:*


* `2 <= n == nums.length <= 50`
* `n` is even.
* `1 <= nums[i] <= 50`




== 思路分析


[[src-3194]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3194_MinimumAverageOfSmallestAndLargestElements.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3194_MinimumAverageOfSmallestAndLargestElements_2.java[tag=answer]
// ----
// --
====


== 参考资料


