[#3210-find-the-encrypted-string]
= 3210. Find the Encrypted String

{leetcode}/problems/find-the-encrypted-string/[LeetCode - 3210. Find the Encrypted String ^]

You are given a string `s` and an integer `k`. Encrypt the string using the following algorithm:


* For each character `c` in `s`, replace `c` with the `k^th^` character after `c` in the string (in a cyclic manner).


Return the _encrypted string_.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "dart", k = 3

*Output:* <span class="example-io">"tdar"

*Explanation:*


* For `i = 0`, the 3^rd^ character after `'d'` is `'t'`.
* For `i = 1`, the 3^rd^ character after `'a'` is `'d'`.
* For `i = 2`, the 3^rd^ character after `'r'` is `'a'`.
* For `i = 3`, the 3^rd^ character after `'t'` is `'r'`.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "aaa", k = 1

*Output:* <span class="example-io">"aaa"

*Explanation:*

As all the characters are the same, the encrypted string will also be the same.


 
*Constraints:*


* `1 <= s.length <= 100`
* `1 <= k <= 10^4^`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3210]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3210_FindTheEncryptedString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3210_FindTheEncryptedString_2.java[tag=answer]
// ----
// --
====


== 参考资料


