[#3216-lexicographically-smallest-string-after-a-swap]
= 3216. Lexicographically Smallest String After a Swap

https://leetcode.com/problems/lexicographically-smallest-string-after-a-swap/[LeetCode - 3216. Lexicographically Smallest String After a Swap ^]

Given a string `s` containing only digits, return the <span data-keyword="lexicographically-smaller-string">lexicographically smallest string that can be obtained after swapping *adjacent* digits in `s` with the same *parity* at most *once*.

Digits have the same parity if both are odd or both are even. For example, 5 and 9, as well as 2 and 4, have the same parity, while 6 and 9 do not.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "45320"

*Output:* <span class="example-io">"43520"

*Explanation: *

`s[1] == '5'` and `s[2] == '3'` both have the same parity, and swapping them results in the lexicographically smallest string.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "001"

*Output:* <span class="example-io">"001"

*Explanation:*

There is no need to perform a swap because `s` is already the lexicographically smallest.


 
*Constraints:*


* `2 <= s.length <= 100`
* `s` consists only of digits.




== 思路分析


[[src-3216]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3216_LexicographicallySmallestStringAfterASwap.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3216_LexicographicallySmallestStringAfterASwap_2.java[tag=answer]
// ----
// --
====


== 参考资料


