[#3220-odd-and-even-transactions]
= 3220. Odd and Even Transactions

{leetcode}/problems/odd-and-even-transactions/[LeetCode - 3220. Odd and Even Transactions ^]

Table: `transactions`

[subs="verbatim,quotes"]
----
+------------------+------+
| Column Name      | Type | 
+------------------+------+
| transaction_id   | int  |
| amount           | int  |
| transaction_date | date |
+------------------+------+
The transactions_id column uniquely identifies each row in this table.
Each row of this table contains the transaction id, amount and transaction date.

----

Write a solution to find the *sum of amounts* for *odd* and *even* transactions for each day. If there are no odd or even transactions for a specific date, display as `0`.

Return _the result table ordered by_ `transaction_date` _in *ascending* order_.

The result format is in the following example.

 
<strong class="example">Example:*

<div class="example-block">
*Input:*

`transactions` table:

<pre class="example-io">
+----------------+--------+------------------+
| transaction_id | amount | transaction_date |
+----------------+--------+------------------+
| 1              | 150    | 2024-07-01       |
| 2              | 200    | 2024-07-01       |
| 3              | 75     | 2024-07-01       |
| 4              | 300    | 2024-07-02       |
| 5              | 50     | 2024-07-02       |
| 6              | 120    | 2024-07-03       |
+----------------+--------+------------------+
  
----

*Output:*

<pre class="example-io">
+------------------+---------+----------+
| transaction_date | odd_sum | even_sum |
+------------------+---------+----------+
| 2024-07-01       | 75      | 350      |
| 2024-07-02       | 0       | 350      |
| 2024-07-03       | 0       | 120      |
+------------------+---------+----------+
  
----

*Explanation:*


* For transaction dates:
	
	* 2024-07-01:
		
		* Sum of amounts for odd transactions: 75
		* Sum of amounts for even transactions: 150 + 200 = 350
		
		
	* 2024-07-02:
		
		* Sum of amounts for odd transactions: 0
		* Sum of amounts for even transactions: 300 + 50 = 350
		
		
	* 2024-07-03:
		
		* Sum of amounts for odd transactions: 0
		* Sum of amounts for even transactions: 120
		
		
	
	


*Note:* The output table is ordered by `transaction_date` in ascending order.




== 思路分析


[[src-3220]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3220_OddAndEvenTransactions.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3220_OddAndEvenTransactions_2.java[tag=answer]
// ----
// --
====


== 参考资料


