[#3222-find-the-winning-player-in-coin-game]
= 3222. Find the Winning Player in Coin Game

https://leetcode.com/problems/find-the-winning-player-in-coin-game/[LeetCode - 3222. Find the Winning Player in Coin Game ^]

You are given two *positive* integers `x` and `y`, denoting the number of coins with values 75 and 10 _respectively_.

Alice and Bob are playing a game. Each turn, starting with *Alice*, the player must pick up coins with a *total* value 115. If the player is unable to do so, they *lose* the game.

Return the _name_ of the player who wins the game if both players play *optimally*.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">x = 2, y = 7

*Output:* <span class="example-io">"Alice"

*Explanation:*

The game ends in a single turn:


* Alice picks 1 coin with a value of 75 and 4 coins with a value of 10.



<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">x = 4, y = 11

*Output:* <span class="example-io">"Bob"

*Explanation:*

The game ends in 2 turns:


* Alice picks 1 coin with a value of 75 and 4 coins with a value of 10.
* Bob picks 1 coin with a value of 75 and 4 coins with a value of 10.



 
*Constraints:*


* `1 <= x, y <= 100`




== 思路分析


[[src-3222]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3222_FindTheWinningPlayerInCoinGame.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3222_FindTheWinningPlayerInCoinGame_2.java[tag=answer]
// ----
// --
====


== 参考资料


