[#3224-minimum-array-changes-to-make-differences-equal]
= 3224. Minimum Array Changes to Make Differences Equal

{leetcode}/problems/minimum-array-changes-to-make-differences-equal/[LeetCode - 3224. Minimum Array Changes to Make Differences Equal ^]

You are given an integer array `nums` of size `n` where `n` is *even*, and an integer `k`.

You can perform some changes on the array, where in one change you can replace *any* element in the array with *any* integer in the range from `0` to `k`.

You need to perform some changes (possibly none) such that the final array satisfies the following condition:


* There exists an integer `X` such that `abs(a[i] - a[n - i - 1]) = X` for all `(0 <= i < n)`.


Return the *minimum* number of changes required to satisfy the above condition.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,0,1,2,4,3], k = 4

*Output:* <span class="example-io">2

*Explanation:*


We can perform the following changes:


* Replace `nums[1]` by 2. The resulting array is `nums = [1,[.underline]#*2*#,1,2,4,3]`.
* Replace `nums[3]` by 3. The resulting array is `nums = [1,2,1,[.underline]#*3*#,4,3]`.


The integer `X` will be 2.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [0,1,2,3,3,6,5,4], k = 6

*Output:* <span class="example-io">2

*Explanation:*


We can perform the following operations:


* Replace `nums[3]` by 0. The resulting array is `nums = [0,1,2,[.underline]#*0*#,3,6,5,4]`.
* Replace `nums[4]` by 4. The resulting array is `nums = [0,1,2,0,*[.underline]#4#*,6,5,4]`.


The integer `X` will be 4.


 
*Constraints:*


* `2 <= n == nums.length <= 10^5^`
* `n` is even.
* `0 <= nums[i] <= k <= 10^5^`




== 思路分析


[[src-3224]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3224_MinimumArrayChangesToMakeDifferencesEqual.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3224_MinimumArrayChangesToMakeDifferencesEqual_2.java[tag=answer]
// ----
// --
====


== 参考资料


