[#3227-vowels-game-in-a-string]
= 3227. Vowels Game in a String

{leetcode}/problems/vowels-game-in-a-string/[LeetCode - 3227. Vowels Game in a String ^]

Alice and Bob are playing a game on a string.

You are given a string `s`, Alice and Bob will take turns playing the following game where Alice starts *first*:


* On Alice's turn, she has to remove any *non-empty* <span data-keyword="substring">substring from `s` that contains an *odd* number of vowels.
* On Bob's turn, he has to remove any *non-empty* <span data-keyword="substring">substring from `s` that contains an *even* number of vowels.


The first player who cannot make a move on their turn loses the game. We assume that both Alice and Bob play *optimally*.

Return `true` if Alice wins the game, and `false` otherwise.

The English vowels are: `a`, `e`, `i`, `o`, and `u`.

 
*Example 1:*

<div class="example-block">
*Input:* <span class="example-io">s = "leetcoder"

*Output:* <span class="example-io">true

*Explanation:*


Alice can win the game as follows:


* Alice plays first, she can delete the underlined substring in `s = "[.underline]#*leetco*#der"` which contains 3 vowels. The resulting string is `s = "der"`.
* Bob plays second, he can delete the underlined substring in `s = "[.underline]#*d*#er"` which contains 0 vowels. The resulting string is `s = "er"`.
* Alice plays third, she can delete the whole string `s = "*[.underline]#er#*"` which contains 1 vowel.
* Bob plays fourth, since the string is empty, there is no valid play for Bob. So Alice wins the game.



*Example 2:*

<div class="example-block">
*Input:* <span class="example-io">s = "bbcd"

*Output:* <span class="example-io">false

*Explanation:*


There is no valid play for Alice in her first turn, so Alice loses the game.


 
*Constraints:*


* `1 <= s.length <= 10^5^`
* `s` consists only of lowercase English letters.




== 思路分析


[[src-3227]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3227_VowelsGameInAString.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3227_VowelsGameInAString_2.java[tag=answer]
// ----
// --
====


== 参考资料


