[#3229-minimum-operations-to-make-array-equal-to-target]
= 3229. Minimum Operations to Make Array Equal to Target

https://leetcode.com/problems/minimum-operations-to-make-array-equal-to-target/[LeetCode - 3229. Minimum Operations to Make Array Equal to Target ^]

You are given two positive integer arrays `nums` and `target`, of the same length.

In a single operation, you can select any <span data-keyword="subarray">subarray of `nums` and increment or decrement each element within that subarray by 1.

Return the *minimum* number of operations required to make `nums` equal to the array `target`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [3,5,1,2], target = [4,6,2,4]

*Output:* <span class="example-io">2

*Explanation:*

We will perform the following operations to make `nums` equal to `target`:


- Increment `nums[0..3]` by 1, `nums = [4,6,2,3]`.


- Increment `nums[3..3]` by 1, `nums = [4,6,2,4]`.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,3,2], target = [2,1,4]

*Output:* <span class="example-io">5

*Explanation:*

We will perform the following operations to make `nums` equal to `target`:


- Increment `nums[0..0]` by 1, `nums = [2,3,2]`.


- Decrement `nums[1..1]` by 1, `nums = [2,2,2]`.


- Decrement `nums[1..1]` by 1, `nums = [2,1,2]`.


- Increment `nums[2..2]` by 1, `nums = [2,1,3]`.


- Increment `nums[2..2]` by 1, `nums = [2,1,4]`.


 
*Constraints:*


* `1 <= nums.length == target.length <= 10^5^`
* `1 <= nums[i], target[i] <= 10^8^`




== 思路分析


[[src-3229]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3229_MinimumOperationsToMakeArrayEqualToTarget.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3229_MinimumOperationsToMakeArrayEqualToTarget_2.java[tag=answer]
// ----
// --
====


== 参考资料


