[#3232-find-if-digit-game-can-be-won]
= 3232. Find if Digit Game Can Be Won

{leetcode}/problems/find-if-digit-game-can-be-won/[LeetCode - 3232. Find if Digit Game Can Be Won ^]

You are given an array of *positive* integers `nums`.

Alice and Bob are playing a game. In the game, Alice can choose *either* all single-digit numbers or all double-digit numbers from `nums`, and the rest of the numbers are given to Bob. Alice wins if the sum of her numbers is *strictly greater* than the sum of Bob's numbers.

Return `true` if Alice can win this game, otherwise, return `false`.

 
<strong class="example">Example 1:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,3,4,10]

*Output:* <span class="example-io">false

*Explanation:*

Alice cannot win by choosing either single-digit or double-digit numbers.


<strong class="example">Example 2:*

<div class="example-block">
*Input:* <span class="example-io">nums = [1,2,3,4,5,14]

*Output:* <span class="example-io">true

*Explanation:*

Alice can win by choosing single-digit numbers which have a sum equal to 15.


<strong class="example">Example 3:*

<div class="example-block">
*Input:* <span class="example-io">nums = [5,5,5,25]

*Output:* <span class="example-io">true

*Explanation:*

Alice can win by choosing double-digit numbers which have a sum equal to 25.


 
*Constraints:*


* `1 <= nums.length <= 100`
* `1 <= nums[i] <= 99`




== 思路分析


[[src-3232]]
[tabs]
====
一刷::
+
--
[{java_src_attr}]
----
include::{sourcedir}/_3232_FindIfDigitGameCanBeWon.java[tag=answer]
----
--

// 二刷::
// +
// --
// [{java_src_attr}]
// ----
// include::{sourcedir}/_3232_FindIfDigitGameCanBeWon_2.java[tag=answer]
// ----
// --
====


== 参考资料


